// ==============================================================
// Generated by Vitis HLS v2024.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bnn_dense_layer_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY,
        m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID,
        m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP,
        m_axi_gmem_0_BID,
        m_axi_gmem_0_BUSER,
        input_r,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_0_AWVALID;
input   m_axi_gmem_0_AWREADY;
output  [63:0] m_axi_gmem_0_AWADDR;
output  [0:0] m_axi_gmem_0_AWID;
output  [31:0] m_axi_gmem_0_AWLEN;
output  [2:0] m_axi_gmem_0_AWSIZE;
output  [1:0] m_axi_gmem_0_AWBURST;
output  [1:0] m_axi_gmem_0_AWLOCK;
output  [3:0] m_axi_gmem_0_AWCACHE;
output  [2:0] m_axi_gmem_0_AWPROT;
output  [3:0] m_axi_gmem_0_AWQOS;
output  [3:0] m_axi_gmem_0_AWREGION;
output  [0:0] m_axi_gmem_0_AWUSER;
output   m_axi_gmem_0_WVALID;
input   m_axi_gmem_0_WREADY;
output  [31:0] m_axi_gmem_0_WDATA;
output  [3:0] m_axi_gmem_0_WSTRB;
output   m_axi_gmem_0_WLAST;
output  [0:0] m_axi_gmem_0_WID;
output  [0:0] m_axi_gmem_0_WUSER;
output   m_axi_gmem_0_ARVALID;
input   m_axi_gmem_0_ARREADY;
output  [63:0] m_axi_gmem_0_ARADDR;
output  [0:0] m_axi_gmem_0_ARID;
output  [31:0] m_axi_gmem_0_ARLEN;
output  [2:0] m_axi_gmem_0_ARSIZE;
output  [1:0] m_axi_gmem_0_ARBURST;
output  [1:0] m_axi_gmem_0_ARLOCK;
output  [3:0] m_axi_gmem_0_ARCACHE;
output  [2:0] m_axi_gmem_0_ARPROT;
output  [3:0] m_axi_gmem_0_ARQOS;
output  [3:0] m_axi_gmem_0_ARREGION;
output  [0:0] m_axi_gmem_0_ARUSER;
input   m_axi_gmem_0_RVALID;
output   m_axi_gmem_0_RREADY;
input  [31:0] m_axi_gmem_0_RDATA;
input   m_axi_gmem_0_RLAST;
input  [0:0] m_axi_gmem_0_RID;
input  [8:0] m_axi_gmem_0_RFIFONUM;
input  [0:0] m_axi_gmem_0_RUSER;
input  [1:0] m_axi_gmem_0_RRESP;
input   m_axi_gmem_0_BVALID;
output   m_axi_gmem_0_BREADY;
input  [1:0] m_axi_gmem_0_BRESP;
input  [0:0] m_axi_gmem_0_BID;
input  [0:0] m_axi_gmem_0_BUSER;
input  [63:0] input_r;
output  [6:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [31:0] output_r_d0;

reg ap_idle;
reg m_axi_gmem_0_ARVALID;
reg m_axi_gmem_0_RREADY;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln32_reg_2381;
reg   [0:0] first_iter_0_reg_2398;
reg    ap_predicate_op41_readreq_state2;
reg    ap_block_state2_io_grp1;
reg    ap_block_pp0_stage1_subdone_grp1_done_reg;
reg    ap_block_pp0_stage1_subdone_grp1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone_grp2_done_reg;
reg    ap_block_pp0_stage1_subdone_grp2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [11:0] golden_w1_address0;
wire   [31:0] golden_w1_q0;
reg    gmem_blk_n_AR;
wire    ap_block_pp0_stage1_grp1;
reg    gmem_blk_n_R;
wire    ap_block_pp0_stage1_grp2;
wire    ap_block_pp0_stage0_11001;
reg   [63:0] gmem_addr_reg_2375;
wire   [0:0] icmp_ln32_fu_358_p2;
wire   [0:0] icmp_ln36_fu_373_p2;
reg   [0:0] icmp_ln36_reg_2385;
reg   [0:0] icmp_ln36_reg_2385_pp0_iter1_reg;
reg   [0:0] icmp_ln36_reg_2385_pp0_iter2_reg;
reg   [0:0] icmp_ln36_reg_2385_pp0_iter3_reg;
reg   [0:0] icmp_ln36_reg_2385_pp0_iter4_reg;
reg   [0:0] icmp_ln36_reg_2385_pp0_iter5_reg;
wire   [4:0] select_ln32_fu_379_p3;
reg   [4:0] select_ln32_reg_2391;
reg   [4:0] select_ln32_reg_2391_pp0_iter1_reg;
reg   [4:0] select_ln32_reg_2391_pp0_iter2_reg;
reg   [4:0] select_ln32_reg_2391_pp0_iter3_reg;
reg   [4:0] select_ln32_reg_2391_pp0_iter4_reg;
reg   [4:0] select_ln32_reg_2391_pp0_iter5_reg;
wire   [0:0] first_iter_0_fu_387_p2;
wire   [0:0] icmp_ln36_1_fu_403_p2;
reg   [0:0] icmp_ln36_1_reg_2402;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
reg   [0:0] icmp_ln36_1_reg_2402_pp0_iter1_reg;
reg   [0:0] icmp_ln36_1_reg_2402_pp0_iter2_reg;
reg   [0:0] icmp_ln36_1_reg_2402_pp0_iter3_reg;
reg   [0:0] icmp_ln36_1_reg_2402_pp0_iter4_reg;
reg   [0:0] icmp_ln36_1_reg_2402_pp0_iter5_reg;
reg   [6:0] output_addr_reg_2411;
reg   [6:0] output_addr_reg_2411_pp0_iter4_reg;
reg   [6:0] output_addr_reg_2411_pp0_iter5_reg;
reg   [6:0] output_addr_reg_2411_pp0_iter6_reg;
reg   [31:0] gmem_addr_read_reg_2421;
reg    ap_block_pp0_stage1_11001_grp2;
wire   [0:0] trunc_ln18_fu_451_p1;
reg   [0:0] trunc_ln18_reg_2491;
reg   [31:0] golden_w1_load_reg_2497;
wire   [1:0] zext_ln10_fu_1494_p1;
reg   [1:0] zext_ln10_reg_2502;
reg   [0:0] tmp_1_reg_2507;
reg   [0:0] tmp_2_reg_2513;
reg   [0:0] tmp_3_reg_2518;
reg   [0:0] tmp_4_reg_2523;
reg   [0:0] tmp_5_reg_2528;
reg   [0:0] tmp_6_reg_2533;
reg   [0:0] tmp_7_reg_2538;
reg   [0:0] tmp_8_reg_2543;
reg   [0:0] tmp_9_reg_2548;
reg   [0:0] tmp_10_reg_2553;
reg   [0:0] tmp_11_reg_2558;
reg   [0:0] tmp_12_reg_2563;
reg   [0:0] tmp_13_reg_2568;
reg   [0:0] tmp_14_reg_2573;
wire   [31:0] add_ln47_fu_1804_p2;
reg   [31:0] add_ln47_reg_2578;
wire   [2:0] add_ln47_5_fu_1830_p2;
reg   [2:0] add_ln47_5_reg_2583;
wire   [2:0] add_ln47_9_fu_1856_p2;
reg   [2:0] add_ln47_9_reg_2588;
wire   [2:0] add_ln47_12_fu_1882_p2;
reg   [2:0] add_ln47_12_reg_2593;
wire   [1:0] add_ln47_15_fu_1888_p2;
reg   [1:0] add_ln47_15_reg_2598;
wire   [31:0] add_ln43_fu_1990_p2;
reg   [31:0] add_ln43_reg_2603;
wire   [31:0] add_ln43_3_fu_2041_p2;
reg   [31:0] add_ln43_3_reg_2609;
wire   [3:0] add_ln43_14_fu_2107_p2;
reg   [3:0] add_ln43_14_reg_2614;
wire   [31:0] add_ln47_6_fu_2137_p2;
reg   [31:0] add_ln47_6_reg_2619;
wire   [4:0] add_ln47_29_fu_2276_p2;
reg   [4:0] add_ln47_29_reg_2624;
wire   [31:0] popcount_sum_2_fu_2313_p3;
reg   [31:0] popcount_sum_2_reg_2629;
wire   [63:0] zext_ln32_fu_430_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln37_fu_447_p1;
wire    ap_block_pp0_stage1_grp0;
wire  signed [63:0] p_cast_cast_fu_325_p1;
reg    ap_block_pp0_stage1_11001_grp1;
reg   [31:0] popcount_sum_fu_256;
wire    ap_loop_init;
reg   [4:0] w_fu_260;
wire   [4:0] add_ln36_fu_398_p2;
reg   [4:0] ap_sig_allocacmp_w_load;
reg   [7:0] n_fu_264;
wire   [7:0] select_ln32_2_fu_423_p3;
reg   [11:0] indvar_flatten_fu_268;
wire   [11:0] add_ln32_fu_364_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten_load;
reg    golden_w1_ce0_local;
reg    output_r_we0_local;
wire   [31:0] add_ln52_fu_2331_p2;
reg    output_r_ce0_local;
wire   [61:0] p_cast_fu_315_p4;
wire   [7:0] add_ln32_1_fu_417_p2;
wire   [11:0] grp_fu_2338_p3;
wire   [0:0] bit_sel3_fu_455_p3;
wire   [0:0] xor_ln18_fu_462_p2;
wire   [15:0] trunc_ln18_2_fu_468_p1;
wire   [0:0] bit_sel4_fu_483_p3;
wire   [0:0] xor_ln18_32_fu_490_p2;
wire   [16:0] trunc_ln18_4_fu_496_p1;
wire   [0:0] bit_sel6_fu_511_p3;
wire   [0:0] xor_ln18_33_fu_518_p2;
wire   [17:0] trunc_ln18_6_fu_524_p1;
wire   [0:0] bit_sel7_fu_539_p3;
wire   [0:0] xor_ln18_34_fu_546_p2;
wire   [18:0] trunc_ln18_8_fu_552_p1;
wire   [0:0] bit_sel9_fu_567_p3;
wire   [0:0] xor_ln18_35_fu_574_p2;
wire   [19:0] trunc_ln18_10_fu_580_p1;
wire   [0:0] bit_sel10_fu_595_p3;
wire   [0:0] xor_ln18_36_fu_602_p2;
wire   [20:0] trunc_ln18_12_fu_608_p1;
wire   [0:0] bit_sel12_fu_623_p3;
wire   [0:0] xor_ln18_37_fu_630_p2;
wire   [21:0] trunc_ln18_14_fu_636_p1;
wire   [0:0] bit_sel13_fu_651_p3;
wire   [0:0] xor_ln18_38_fu_658_p2;
wire   [22:0] trunc_ln18_16_fu_664_p1;
wire   [0:0] bit_sel15_fu_679_p3;
wire   [0:0] xor_ln18_39_fu_686_p2;
wire   [23:0] trunc_ln18_18_fu_692_p1;
wire   [0:0] bit_sel16_fu_707_p3;
wire   [0:0] xor_ln18_40_fu_714_p2;
wire   [24:0] trunc_ln18_20_fu_720_p1;
wire   [0:0] bit_sel18_fu_735_p3;
wire   [0:0] xor_ln18_41_fu_742_p2;
wire   [25:0] trunc_ln18_22_fu_748_p1;
wire   [0:0] bit_sel19_fu_763_p3;
wire   [0:0] xor_ln18_42_fu_770_p2;
wire   [26:0] trunc_ln18_24_fu_776_p1;
wire   [0:0] bit_sel21_fu_791_p3;
wire   [0:0] xor_ln18_43_fu_798_p2;
wire   [27:0] trunc_ln18_26_fu_804_p1;
wire   [0:0] bit_sel22_fu_819_p3;
wire   [0:0] xor_ln18_44_fu_826_p2;
wire   [28:0] trunc_ln18_28_fu_832_p1;
wire   [0:0] bit_sel24_fu_847_p3;
wire   [0:0] xor_ln18_45_fu_854_p2;
wire   [29:0] trunc_ln18_30_fu_860_p1;
wire   [0:0] bit_sel25_fu_875_p3;
wire   [0:0] xor_ln18_46_fu_882_p2;
wire   [0:0] bit_sel27_fu_899_p3;
wire   [0:0] xor_ln18_47_fu_906_p2;
wire   [1:0] trunc_ln18_33_fu_912_p1;
wire   [0:0] bit_sel28_fu_927_p3;
wire   [0:0] xor_ln18_48_fu_934_p2;
wire   [2:0] trunc_ln18_35_fu_940_p1;
wire   [0:0] bit_sel30_fu_955_p3;
wire   [0:0] xor_ln18_49_fu_962_p2;
wire   [3:0] trunc_ln18_37_fu_968_p1;
wire   [0:0] bit_sel29_fu_983_p3;
wire   [0:0] xor_ln18_50_fu_990_p2;
wire   [4:0] trunc_ln18_39_fu_996_p1;
wire   [0:0] bit_sel26_fu_1011_p3;
wire   [0:0] xor_ln18_51_fu_1018_p2;
wire   [5:0] trunc_ln18_41_fu_1024_p1;
wire   [0:0] bit_sel23_fu_1039_p3;
wire   [0:0] xor_ln18_52_fu_1046_p2;
wire   [6:0] trunc_ln18_43_fu_1052_p1;
wire   [0:0] bit_sel20_fu_1067_p3;
wire   [0:0] xor_ln18_53_fu_1074_p2;
wire   [7:0] trunc_ln18_45_fu_1080_p1;
wire   [0:0] bit_sel17_fu_1095_p3;
wire   [0:0] xor_ln18_54_fu_1102_p2;
wire   [8:0] trunc_ln18_47_fu_1108_p1;
wire   [0:0] bit_sel14_fu_1123_p3;
wire   [0:0] xor_ln18_55_fu_1130_p2;
wire   [9:0] trunc_ln18_49_fu_1136_p1;
wire   [0:0] bit_sel11_fu_1151_p3;
wire   [0:0] xor_ln18_56_fu_1158_p2;
wire   [10:0] trunc_ln18_51_fu_1164_p1;
wire   [0:0] bit_sel8_fu_1179_p3;
wire   [0:0] xor_ln18_57_fu_1186_p2;
wire   [11:0] trunc_ln18_53_fu_1192_p1;
wire   [0:0] bit_sel5_fu_1207_p3;
wire   [0:0] xor_ln18_58_fu_1214_p2;
wire   [12:0] trunc_ln18_55_fu_1220_p1;
wire   [0:0] bit_sel2_fu_1235_p3;
wire   [0:0] xor_ln18_59_fu_1242_p2;
wire   [13:0] trunc_ln18_57_fu_1248_p1;
wire   [0:0] bit_sel_fu_1263_p3;
wire   [0:0] xor_ln18_60_fu_1270_p2;
wire   [14:0] trunc_ln18_59_fu_1276_p1;
wire   [0:0] trunc_ln18_61_fu_1296_p1;
wire   [0:0] xor_ln18_31_fu_1291_p2;
wire   [15:0] trunc_ln18_60_fu_1287_p1;
wire   [15:0] xor_ln18_29_fu_1279_p3;
wire   [14:0] trunc_ln18_58_fu_1259_p1;
wire   [14:0] xor_ln18_28_fu_1251_p3;
wire   [13:0] trunc_ln18_56_fu_1231_p1;
wire   [13:0] xor_ln18_27_fu_1223_p3;
wire   [12:0] trunc_ln18_54_fu_1203_p1;
wire   [12:0] xor_ln18_26_fu_1195_p3;
wire   [11:0] trunc_ln18_52_fu_1175_p1;
wire   [11:0] xor_ln18_25_fu_1167_p3;
wire   [10:0] trunc_ln18_50_fu_1147_p1;
wire   [10:0] xor_ln18_24_fu_1139_p3;
wire   [9:0] trunc_ln18_48_fu_1119_p1;
wire   [9:0] xor_ln18_23_fu_1111_p3;
wire   [8:0] trunc_ln18_46_fu_1091_p1;
wire   [8:0] xor_ln18_22_fu_1083_p3;
wire   [7:0] trunc_ln18_44_fu_1063_p1;
wire   [7:0] xor_ln18_21_fu_1055_p3;
wire   [6:0] trunc_ln18_42_fu_1035_p1;
wire   [6:0] xor_ln18_20_fu_1027_p3;
wire   [5:0] trunc_ln18_40_fu_1007_p1;
wire   [5:0] xor_ln18_19_fu_999_p3;
wire   [4:0] trunc_ln18_38_fu_979_p1;
wire   [4:0] xor_ln18_18_fu_971_p3;
wire   [3:0] trunc_ln18_36_fu_951_p1;
wire   [3:0] xor_ln18_17_fu_943_p3;
wire   [2:0] trunc_ln18_34_fu_923_p1;
wire   [2:0] xor_ln18_16_fu_915_p3;
wire   [1:0] trunc_ln18_32_fu_895_p1;
wire   [1:0] xor_ln18_15_fu_888_p3;
wire   [30:0] trunc_ln18_31_fu_871_p1;
wire   [30:0] xor_ln18_14_fu_863_p3;
wire   [29:0] trunc_ln18_29_fu_843_p1;
wire   [29:0] xor_ln18_13_fu_835_p3;
wire   [28:0] trunc_ln18_27_fu_815_p1;
wire   [28:0] xor_ln18_12_fu_807_p3;
wire   [27:0] trunc_ln18_25_fu_787_p1;
wire   [27:0] xor_ln18_11_fu_779_p3;
wire   [26:0] trunc_ln18_23_fu_759_p1;
wire   [26:0] xor_ln18_10_fu_751_p3;
wire   [25:0] trunc_ln18_21_fu_731_p1;
wire   [25:0] xor_ln18_s_fu_723_p3;
wire   [24:0] trunc_ln18_19_fu_703_p1;
wire   [24:0] xor_ln18_9_fu_695_p3;
wire   [23:0] trunc_ln18_17_fu_675_p1;
wire   [23:0] xor_ln18_8_fu_667_p3;
wire   [22:0] trunc_ln18_15_fu_647_p1;
wire   [22:0] xor_ln18_7_fu_639_p3;
wire   [21:0] trunc_ln18_13_fu_619_p1;
wire   [21:0] xor_ln18_6_fu_611_p3;
wire   [20:0] trunc_ln18_11_fu_591_p1;
wire   [20:0] xor_ln18_5_fu_583_p3;
wire   [19:0] trunc_ln18_9_fu_563_p1;
wire   [19:0] xor_ln18_4_fu_555_p3;
wire   [18:0] trunc_ln18_7_fu_535_p1;
wire   [18:0] xor_ln18_3_fu_527_p3;
wire   [17:0] trunc_ln18_5_fu_507_p1;
wire   [17:0] xor_ln18_2_fu_499_p3;
wire   [16:0] trunc_ln18_3_fu_479_p1;
wire   [16:0] xor_ln18_1_fu_471_p3;
wire   [16:0] xor_ln37_30_fu_1480_p2;
wire   [0:0] tmp_fu_1486_p3;
wire   [17:0] xor_ln37_29_fu_1474_p2;
wire   [18:0] xor_ln37_28_fu_1468_p2;
wire   [19:0] xor_ln37_27_fu_1462_p2;
wire   [20:0] xor_ln37_26_fu_1456_p2;
wire   [21:0] xor_ln37_25_fu_1450_p2;
wire   [22:0] xor_ln37_24_fu_1444_p2;
wire   [23:0] xor_ln37_23_fu_1438_p2;
wire   [24:0] xor_ln37_22_fu_1432_p2;
wire   [25:0] xor_ln37_21_fu_1426_p2;
wire   [26:0] xor_ln37_20_fu_1420_p2;
wire   [27:0] xor_ln37_19_fu_1414_p2;
wire   [28:0] xor_ln37_18_fu_1408_p2;
wire   [29:0] xor_ln37_17_fu_1402_p2;
wire   [30:0] xor_ln37_16_fu_1396_p2;
wire   [1:0] xor_ln37_15_fu_1390_p2;
wire   [2:0] xor_ln37_14_fu_1384_p2;
wire   [3:0] xor_ln37_13_fu_1378_p2;
wire   [4:0] xor_ln37_12_fu_1372_p2;
wire   [5:0] xor_ln37_11_fu_1366_p2;
wire   [6:0] xor_ln37_10_fu_1360_p2;
wire   [7:0] xor_ln37_9_fu_1354_p2;
wire   [8:0] xor_ln37_8_fu_1348_p2;
wire   [9:0] xor_ln37_7_fu_1342_p2;
wire   [10:0] xor_ln37_6_fu_1336_p2;
wire   [11:0] xor_ln37_5_fu_1330_p2;
wire   [12:0] xor_ln37_4_fu_1324_p2;
wire   [13:0] xor_ln37_3_fu_1318_p2;
wire   [14:0] xor_ln37_2_fu_1312_p2;
wire   [15:0] xor_ln37_1_fu_1306_p2;
wire   [0:0] tmp_24_fu_1674_p3;
wire   [0:0] tmp_20_fu_1642_p3;
wire   [0:0] tmp_28_fu_1706_p3;
wire   [0:0] tmp_17_fu_1618_p3;
wire   [0:0] tmp_18_fu_1626_p3;
wire   [0:0] tmp_29_fu_1714_p3;
wire   [0:0] tmp_26_fu_1690_p3;
wire   [0:0] tmp_30_fu_1722_p3;
wire   [0:0] tmp_21_fu_1650_p3;
wire   [0:0] tmp_19_fu_1634_p3;
wire   [0:0] tmp_22_fu_1658_p3;
wire   [0:0] tmp_25_fu_1682_p3;
wire   [0:0] tmp_27_fu_1698_p3;
wire   [0:0] tmp_16_fu_1610_p3;
wire   [0:0] xor_ln37_fu_1300_p2;
wire   [0:0] tmp_23_fu_1666_p3;
wire   [1:0] zext_ln47_fu_1730_p1;
wire   [1:0] zext_ln47_2_fu_1738_p1;
wire   [1:0] add_ln47_1_fu_1794_p2;
wire   [31:0] zext_ln47_16_fu_1800_p1;
wire   [31:0] zext_ln47_14_fu_1786_p1;
wire   [1:0] zext_ln47_1_fu_1734_p1;
wire   [1:0] zext_ln47_4_fu_1746_p1;
wire   [1:0] add_ln47_3_fu_1810_p2;
wire   [1:0] zext_ln47_3_fu_1742_p1;
wire   [1:0] zext_ln47_6_fu_1754_p1;
wire   [1:0] add_ln47_4_fu_1820_p2;
wire   [2:0] zext_ln47_18_fu_1826_p1;
wire   [2:0] zext_ln47_17_fu_1816_p1;
wire   [1:0] zext_ln47_5_fu_1750_p1;
wire   [1:0] zext_ln47_8_fu_1762_p1;
wire   [1:0] add_ln47_7_fu_1836_p2;
wire   [1:0] zext_ln47_7_fu_1758_p1;
wire   [1:0] zext_ln47_10_fu_1770_p1;
wire   [1:0] add_ln47_8_fu_1846_p2;
wire   [2:0] zext_ln47_21_fu_1852_p1;
wire   [2:0] zext_ln47_20_fu_1842_p1;
wire   [1:0] zext_ln47_9_fu_1766_p1;
wire   [1:0] zext_ln47_12_fu_1778_p1;
wire   [1:0] add_ln47_10_fu_1862_p2;
wire   [1:0] zext_ln47_11_fu_1774_p1;
wire   [1:0] zext_ln47_13_fu_1782_p1;
wire   [1:0] add_ln47_11_fu_1872_p2;
wire   [2:0] zext_ln47_24_fu_1878_p1;
wire   [2:0] zext_ln47_23_fu_1868_p1;
wire   [1:0] zext_ln47_15_fu_1790_p1;
wire   [0:0] bit_sel1_fu_1904_p3;
wire   [0:0] xor_ln18_30_fu_1911_p2;
wire   [30:0] trunc_ln18_1_fu_1917_p1;
wire   [31:0] xor_ln_fu_1920_p3;
wire   [31:0] xnor_result_fu_1928_p2;
wire   [0:0] tmp_15_fu_1978_p3;
wire   [31:0] zext_ln10_16_fu_1986_p1;
wire   [31:0] select_ln32_1_fu_1897_p3;
wire   [1:0] zext_ln10_10_fu_1960_p1;
wire   [1:0] add_ln43_2_fu_1996_p2;
wire   [31:0] zext_ln43_fu_2001_p1;
wire   [31:0] zext_ln10_1_fu_1933_p1;
wire   [1:0] zext_ln10_6_fu_1948_p1;
wire   [1:0] zext_ln10_9_fu_1957_p1;
wire   [1:0] add_ln43_4_fu_2011_p2;
wire   [1:0] zext_ln10_15_fu_1975_p1;
wire   [1:0] zext_ln10_12_fu_1966_p1;
wire   [1:0] add_ln43_5_fu_2021_p2;
wire   [2:0] zext_ln43_2_fu_2027_p1;
wire   [2:0] zext_ln43_1_fu_2017_p1;
wire   [2:0] add_ln43_6_fu_2031_p2;
wire   [31:0] zext_ln43_3_fu_2037_p1;
wire   [31:0] add_ln43_1_fu_2005_p2;
wire   [1:0] zext_ln10_5_fu_1945_p1;
wire   [1:0] zext_ln10_14_fu_1972_p1;
wire   [1:0] add_ln43_8_fu_2047_p2;
wire   [1:0] zext_ln10_7_fu_1951_p1;
wire   [1:0] zext_ln10_13_fu_1969_p1;
wire   [1:0] add_ln43_9_fu_2057_p2;
wire   [2:0] zext_ln43_5_fu_2063_p1;
wire   [2:0] zext_ln43_4_fu_2053_p1;
wire   [2:0] add_ln43_10_fu_2067_p2;
wire   [1:0] zext_ln10_4_fu_1942_p1;
wire   [1:0] zext_ln10_11_fu_1963_p1;
wire   [1:0] add_ln43_11_fu_2077_p2;
wire   [1:0] zext_ln10_3_fu_1939_p1;
wire   [1:0] zext_ln10_8_fu_1954_p1;
wire   [1:0] add_ln43_12_fu_2087_p2;
wire   [2:0] zext_ln43_8_fu_2093_p1;
wire   [2:0] zext_ln43_7_fu_2083_p1;
wire   [2:0] add_ln43_13_fu_2097_p2;
wire   [3:0] zext_ln43_9_fu_2103_p1;
wire   [3:0] zext_ln43_6_fu_2073_p1;
wire   [31:0] zext_ln47_19_fu_2113_p1;
wire   [3:0] zext_ln47_25_fu_2124_p1;
wire   [3:0] zext_ln47_22_fu_2121_p1;
wire   [3:0] add_ln47_13_fu_2127_p2;
wire   [31:0] zext_ln47_26_fu_2133_p1;
wire   [31:0] add_ln47_2_fu_2116_p2;
wire   [1:0] zext_ln10_2_fu_1936_p1;
wire   [1:0] add_ln47_16_fu_2146_p2;
wire   [2:0] zext_ln47_28_fu_2152_p1;
wire   [2:0] zext_ln47_27_fu_2143_p1;
wire   [2:0] add_ln47_17_fu_2156_p2;
wire   [1:0] add_ln47_18_fu_2166_p2;
wire   [1:0] add_ln47_19_fu_2176_p2;
wire   [2:0] zext_ln47_31_fu_2182_p1;
wire   [2:0] zext_ln47_30_fu_2172_p1;
wire   [2:0] add_ln47_20_fu_2186_p2;
wire   [3:0] zext_ln47_32_fu_2192_p1;
wire   [3:0] zext_ln47_29_fu_2162_p1;
wire   [3:0] add_ln47_21_fu_2196_p2;
wire   [1:0] add_ln47_22_fu_2206_p2;
wire   [1:0] add_ln47_23_fu_2216_p2;
wire   [2:0] zext_ln47_35_fu_2222_p1;
wire   [2:0] zext_ln47_34_fu_2212_p1;
wire   [2:0] add_ln47_24_fu_2226_p2;
wire   [1:0] add_ln47_25_fu_2236_p2;
wire   [1:0] add_ln47_26_fu_2246_p2;
wire   [2:0] zext_ln47_38_fu_2252_p1;
wire   [2:0] zext_ln47_37_fu_2242_p1;
wire   [2:0] add_ln47_27_fu_2256_p2;
wire   [3:0] zext_ln47_39_fu_2262_p1;
wire   [3:0] zext_ln47_36_fu_2232_p1;
wire   [3:0] add_ln47_28_fu_2266_p2;
wire   [4:0] zext_ln47_40_fu_2272_p1;
wire   [4:0] zext_ln47_33_fu_2202_p1;
wire   [31:0] zext_ln43_10_fu_2287_p1;
wire   [31:0] add_ln43_7_fu_2290_p2;
wire   [31:0] zext_ln47_41_fu_2300_p1;
wire   [31:0] add_ln47_14_fu_2303_p2;
wire   [0:0] icmp_ln40_fu_2282_p2;
wire   [31:0] popcount_sum_1_fu_2295_p2;
wire   [31:0] popcount_sum_3_fu_2308_p2;
wire   [31:0] shl_ln52_fu_2326_p2;
wire   [7:0] grp_fu_2338_p0;
wire   [4:0] grp_fu_2338_p1;
wire   [4:0] grp_fu_2338_p2;
reg    grp_fu_2338_ce;
reg    ap_block_pp0_stage1_11001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to6;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [11:0] grp_fu_2338_p00;
wire   [11:0] grp_fu_2338_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp1_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp2_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 popcount_sum_fu_256 = 32'd0;
#0 w_fu_260 = 5'd0;
#0 n_fu_264 = 8'd0;
#0 indvar_flatten_fu_268 = 12'd0;
#0 ap_done_reg = 1'b0;
end

bnn_dense_layer_2_golden_w1_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 3200 ),
    .AddressWidth( 12 ))
golden_w1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(golden_w1_address0),
    .ce0(golden_w1_ce0_local),
    .q0(golden_w1_q0)
);

bnn_mac_muladd_8ns_5ns_5ns_12_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
mac_muladd_8ns_5ns_5ns_12_4_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2338_p0),
    .din1(grp_fu_2338_p1),
    .din2(grp_fu_2338_p2),
    .ce(grp_fu_2338_ce),
    .dout(grp_fu_2338_p3)
);

bnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp1)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp2)) begin
                ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln32_fu_358_p2 == 1'd0))) begin
            indvar_flatten_fu_268 <= add_ln32_fu_364_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_268 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            n_fu_264 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            n_fu_264 <= select_ln32_2_fu_423_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            popcount_sum_fu_256 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            popcount_sum_fu_256 <= popcount_sum_2_fu_2313_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w_fu_260 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (icmp_ln32_reg_2381 == 1'd0))) begin
        w_fu_260 <= add_ln36_fu_398_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        add_ln43_14_reg_2614 <= add_ln43_14_fu_2107_p2;
        add_ln43_3_reg_2609 <= add_ln43_3_fu_2041_p2;
        add_ln43_reg_2603 <= add_ln43_fu_1990_p2;
        add_ln47_29_reg_2624 <= add_ln47_29_fu_2276_p2;
        add_ln47_6_reg_2619 <= add_ln47_6_fu_2137_p2;
        icmp_ln36_1_reg_2402 <= icmp_ln36_1_fu_403_p2;
        icmp_ln36_1_reg_2402_pp0_iter1_reg <= icmp_ln36_1_reg_2402;
        icmp_ln36_1_reg_2402_pp0_iter2_reg <= icmp_ln36_1_reg_2402_pp0_iter1_reg;
        icmp_ln36_1_reg_2402_pp0_iter3_reg <= icmp_ln36_1_reg_2402_pp0_iter2_reg;
        icmp_ln36_1_reg_2402_pp0_iter4_reg <= icmp_ln36_1_reg_2402_pp0_iter3_reg;
        icmp_ln36_1_reg_2402_pp0_iter5_reg <= icmp_ln36_1_reg_2402_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln47_12_reg_2593 <= add_ln47_12_fu_1882_p2;
        add_ln47_15_reg_2598 <= add_ln47_15_fu_1888_p2;
        add_ln47_5_reg_2583 <= add_ln47_5_fu_1830_p2;
        add_ln47_9_reg_2588 <= add_ln47_9_fu_1856_p2;
        add_ln47_reg_2578 <= add_ln47_fu_1804_p2;
        first_iter_0_reg_2398 <= first_iter_0_fu_387_p2;
        gmem_addr_reg_2375 <= p_cast_cast_fu_325_p1;
        golden_w1_load_reg_2497 <= golden_w1_q0;
        icmp_ln32_reg_2381 <= icmp_ln32_fu_358_p2;
        icmp_ln36_reg_2385 <= icmp_ln36_fu_373_p2;
        icmp_ln36_reg_2385_pp0_iter1_reg <= icmp_ln36_reg_2385;
        icmp_ln36_reg_2385_pp0_iter2_reg <= icmp_ln36_reg_2385_pp0_iter1_reg;
        icmp_ln36_reg_2385_pp0_iter3_reg <= icmp_ln36_reg_2385_pp0_iter2_reg;
        icmp_ln36_reg_2385_pp0_iter4_reg <= icmp_ln36_reg_2385_pp0_iter3_reg;
        icmp_ln36_reg_2385_pp0_iter5_reg <= icmp_ln36_reg_2385_pp0_iter4_reg;
        output_addr_reg_2411 <= zext_ln32_fu_430_p1;
        output_addr_reg_2411_pp0_iter4_reg <= output_addr_reg_2411;
        output_addr_reg_2411_pp0_iter5_reg <= output_addr_reg_2411_pp0_iter4_reg;
        output_addr_reg_2411_pp0_iter6_reg <= output_addr_reg_2411_pp0_iter5_reg;
        popcount_sum_2_reg_2629 <= popcount_sum_2_fu_2313_p3;
        select_ln32_reg_2391 <= select_ln32_fu_379_p3;
        select_ln32_reg_2391_pp0_iter1_reg <= select_ln32_reg_2391;
        select_ln32_reg_2391_pp0_iter2_reg <= select_ln32_reg_2391_pp0_iter1_reg;
        select_ln32_reg_2391_pp0_iter3_reg <= select_ln32_reg_2391_pp0_iter2_reg;
        select_ln32_reg_2391_pp0_iter4_reg <= select_ln32_reg_2391_pp0_iter3_reg;
        select_ln32_reg_2391_pp0_iter5_reg <= select_ln32_reg_2391_pp0_iter4_reg;
        tmp_10_reg_2553 <= xor_ln37_20_fu_1420_p2[32'd26];
        tmp_11_reg_2558 <= xor_ln37_19_fu_1414_p2[32'd27];
        tmp_12_reg_2563 <= xor_ln37_18_fu_1408_p2[32'd28];
        tmp_13_reg_2568 <= xor_ln37_17_fu_1402_p2[32'd29];
        tmp_14_reg_2573 <= xor_ln37_16_fu_1396_p2[32'd30];
        tmp_1_reg_2507 <= xor_ln37_29_fu_1474_p2[32'd17];
        tmp_2_reg_2513 <= xor_ln37_28_fu_1468_p2[32'd18];
        tmp_3_reg_2518 <= xor_ln37_27_fu_1462_p2[32'd19];
        tmp_4_reg_2523 <= xor_ln37_26_fu_1456_p2[32'd20];
        tmp_5_reg_2528 <= xor_ln37_25_fu_1450_p2[32'd21];
        tmp_6_reg_2533 <= xor_ln37_24_fu_1444_p2[32'd22];
        tmp_7_reg_2538 <= xor_ln37_23_fu_1438_p2[32'd23];
        tmp_8_reg_2543 <= xor_ln37_22_fu_1432_p2[32'd24];
        tmp_9_reg_2548 <= xor_ln37_21_fu_1426_p2[32'd25];
        zext_ln10_reg_2502[0] <= zext_ln10_fu_1494_p1[0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg))) begin
        gmem_addr_read_reg_2421 <= m_axi_gmem_0_RDATA;
        trunc_ln18_reg_2491 <= trunc_ln18_fu_451_p1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (icmp_ln32_reg_2381 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to6 = 1'b1;
    end else begin
        ap_idle_pp0_1to6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_268;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_w_load = 5'd0;
    end else begin
        ap_sig_allocacmp_w_load = w_fu_260;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (ap_predicate_op41_readreq_state2 == 1'b1))) begin
        gmem_blk_n_AR = m_axi_gmem_0_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg))) begin
        gmem_blk_n_R = m_axi_gmem_0_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        golden_w1_ce0_local = 1'b1;
    end else begin
        golden_w1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_2338_ce = 1'b1;
    end else begin
        grp_fu_2338_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (ap_predicate_op41_readreq_state2 == 1'b1))) begin
        m_axi_gmem_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg))) begin
        m_axi_gmem_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        output_r_ce0_local = 1'b1;
    end else begin
        output_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln36_1_reg_2402_pp0_iter5_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        output_r_we0_local = 1'b1;
    end else begin
        output_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to6 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln32_1_fu_417_p2 = (n_fu_264 + 8'd1);

assign add_ln32_fu_364_p2 = (ap_sig_allocacmp_indvar_flatten_load + 12'd1);

assign add_ln36_fu_398_p2 = (select_ln32_reg_2391 + 5'd1);

assign add_ln43_10_fu_2067_p2 = (zext_ln43_5_fu_2063_p1 + zext_ln43_4_fu_2053_p1);

assign add_ln43_11_fu_2077_p2 = (zext_ln10_4_fu_1942_p1 + zext_ln10_11_fu_1963_p1);

assign add_ln43_12_fu_2087_p2 = (zext_ln10_3_fu_1939_p1 + zext_ln10_8_fu_1954_p1);

assign add_ln43_13_fu_2097_p2 = (zext_ln43_8_fu_2093_p1 + zext_ln43_7_fu_2083_p1);

assign add_ln43_14_fu_2107_p2 = (zext_ln43_9_fu_2103_p1 + zext_ln43_6_fu_2073_p1);

assign add_ln43_1_fu_2005_p2 = (zext_ln43_fu_2001_p1 + zext_ln10_1_fu_1933_p1);

assign add_ln43_2_fu_1996_p2 = (zext_ln10_reg_2502 + zext_ln10_10_fu_1960_p1);

assign add_ln43_3_fu_2041_p2 = (zext_ln43_3_fu_2037_p1 + add_ln43_1_fu_2005_p2);

assign add_ln43_4_fu_2011_p2 = (zext_ln10_6_fu_1948_p1 + zext_ln10_9_fu_1957_p1);

assign add_ln43_5_fu_2021_p2 = (zext_ln10_15_fu_1975_p1 + zext_ln10_12_fu_1966_p1);

assign add_ln43_6_fu_2031_p2 = (zext_ln43_2_fu_2027_p1 + zext_ln43_1_fu_2017_p1);

assign add_ln43_7_fu_2290_p2 = (zext_ln43_10_fu_2287_p1 + add_ln43_3_reg_2609);

assign add_ln43_8_fu_2047_p2 = (zext_ln10_5_fu_1945_p1 + zext_ln10_14_fu_1972_p1);

assign add_ln43_9_fu_2057_p2 = (zext_ln10_7_fu_1951_p1 + zext_ln10_13_fu_1969_p1);

assign add_ln43_fu_1990_p2 = (zext_ln10_16_fu_1986_p1 + select_ln32_1_fu_1897_p3);

assign add_ln47_10_fu_1862_p2 = (zext_ln47_9_fu_1766_p1 + zext_ln47_12_fu_1778_p1);

assign add_ln47_11_fu_1872_p2 = (zext_ln47_11_fu_1774_p1 + zext_ln47_13_fu_1782_p1);

assign add_ln47_12_fu_1882_p2 = (zext_ln47_24_fu_1878_p1 + zext_ln47_23_fu_1868_p1);

assign add_ln47_13_fu_2127_p2 = (zext_ln47_25_fu_2124_p1 + zext_ln47_22_fu_2121_p1);

assign add_ln47_14_fu_2303_p2 = (zext_ln47_41_fu_2300_p1 + add_ln47_6_reg_2619);

assign add_ln47_15_fu_1888_p2 = (zext_ln47_15_fu_1790_p1 + zext_ln10_fu_1494_p1);

assign add_ln47_16_fu_2146_p2 = (zext_ln10_2_fu_1936_p1 + zext_ln10_3_fu_1939_p1);

assign add_ln47_17_fu_2156_p2 = (zext_ln47_28_fu_2152_p1 + zext_ln47_27_fu_2143_p1);

assign add_ln47_18_fu_2166_p2 = (zext_ln10_4_fu_1942_p1 + zext_ln10_5_fu_1945_p1);

assign add_ln47_19_fu_2176_p2 = (zext_ln10_6_fu_1948_p1 + zext_ln10_7_fu_1951_p1);

assign add_ln47_1_fu_1794_p2 = (zext_ln47_fu_1730_p1 + zext_ln47_2_fu_1738_p1);

assign add_ln47_20_fu_2186_p2 = (zext_ln47_31_fu_2182_p1 + zext_ln47_30_fu_2172_p1);

assign add_ln47_21_fu_2196_p2 = (zext_ln47_32_fu_2192_p1 + zext_ln47_29_fu_2162_p1);

assign add_ln47_22_fu_2206_p2 = (zext_ln10_8_fu_1954_p1 + zext_ln10_9_fu_1957_p1);

assign add_ln47_23_fu_2216_p2 = (zext_ln10_10_fu_1960_p1 + zext_ln10_11_fu_1963_p1);

assign add_ln47_24_fu_2226_p2 = (zext_ln47_35_fu_2222_p1 + zext_ln47_34_fu_2212_p1);

assign add_ln47_25_fu_2236_p2 = (zext_ln10_12_fu_1966_p1 + zext_ln10_13_fu_1969_p1);

assign add_ln47_26_fu_2246_p2 = (zext_ln10_14_fu_1972_p1 + zext_ln10_15_fu_1975_p1);

assign add_ln47_27_fu_2256_p2 = (zext_ln47_38_fu_2252_p1 + zext_ln47_37_fu_2242_p1);

assign add_ln47_28_fu_2266_p2 = (zext_ln47_39_fu_2262_p1 + zext_ln47_36_fu_2232_p1);

assign add_ln47_29_fu_2276_p2 = (zext_ln47_40_fu_2272_p1 + zext_ln47_33_fu_2202_p1);

assign add_ln47_2_fu_2116_p2 = (zext_ln47_19_fu_2113_p1 + add_ln47_reg_2578);

assign add_ln47_3_fu_1810_p2 = (zext_ln47_1_fu_1734_p1 + zext_ln47_4_fu_1746_p1);

assign add_ln47_4_fu_1820_p2 = (zext_ln47_3_fu_1742_p1 + zext_ln47_6_fu_1754_p1);

assign add_ln47_5_fu_1830_p2 = (zext_ln47_18_fu_1826_p1 + zext_ln47_17_fu_1816_p1);

assign add_ln47_6_fu_2137_p2 = (zext_ln47_26_fu_2133_p1 + add_ln47_2_fu_2116_p2);

assign add_ln47_7_fu_1836_p2 = (zext_ln47_5_fu_1750_p1 + zext_ln47_8_fu_1762_p1);

assign add_ln47_8_fu_1846_p2 = (zext_ln47_7_fu_1758_p1 + zext_ln47_10_fu_1770_p1);

assign add_ln47_9_fu_1856_p2 = (zext_ln47_21_fu_1852_p1 + zext_ln47_20_fu_1842_p1);

assign add_ln47_fu_1804_p2 = (zext_ln47_16_fu_1800_p1 + zext_ln47_14_fu_1786_p1);

assign add_ln52_fu_2331_p2 = ($signed(shl_ln52_fu_2326_p2) + $signed(32'd4294966512));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((m_axi_gmem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg)) | ((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp2 = ((m_axi_gmem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((m_axi_gmem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg)) | ((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp1 = ((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp2 = ((m_axi_gmem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_state2_io_grp1 = ((m_axi_gmem_0_ARREADY == 1'b0) & (ap_predicate_op41_readreq_state2 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

always @ (*) begin
    ap_predicate_op41_readreq_state2 = ((first_iter_0_reg_2398 == 1'd1) & (icmp_ln32_reg_2381 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign bit_sel10_fu_595_p3 = gmem_addr_read_reg_2421[32'd21];

assign bit_sel11_fu_1151_p3 = gmem_addr_read_reg_2421[32'd11];

assign bit_sel12_fu_623_p3 = gmem_addr_read_reg_2421[32'd22];

assign bit_sel13_fu_651_p3 = gmem_addr_read_reg_2421[32'd23];

assign bit_sel14_fu_1123_p3 = gmem_addr_read_reg_2421[32'd10];

assign bit_sel15_fu_679_p3 = gmem_addr_read_reg_2421[32'd24];

assign bit_sel16_fu_707_p3 = gmem_addr_read_reg_2421[32'd25];

assign bit_sel17_fu_1095_p3 = gmem_addr_read_reg_2421[32'd9];

assign bit_sel18_fu_735_p3 = gmem_addr_read_reg_2421[32'd26];

assign bit_sel19_fu_763_p3 = gmem_addr_read_reg_2421[32'd27];

assign bit_sel1_fu_1904_p3 = gmem_addr_read_reg_2421[32'd31];

assign bit_sel20_fu_1067_p3 = gmem_addr_read_reg_2421[32'd8];

assign bit_sel21_fu_791_p3 = gmem_addr_read_reg_2421[32'd28];

assign bit_sel22_fu_819_p3 = gmem_addr_read_reg_2421[32'd29];

assign bit_sel23_fu_1039_p3 = gmem_addr_read_reg_2421[32'd7];

assign bit_sel24_fu_847_p3 = gmem_addr_read_reg_2421[32'd30];

assign bit_sel25_fu_875_p3 = gmem_addr_read_reg_2421[32'd1];

assign bit_sel26_fu_1011_p3 = gmem_addr_read_reg_2421[32'd6];

assign bit_sel27_fu_899_p3 = gmem_addr_read_reg_2421[32'd2];

assign bit_sel28_fu_927_p3 = gmem_addr_read_reg_2421[32'd3];

assign bit_sel29_fu_983_p3 = gmem_addr_read_reg_2421[32'd5];

assign bit_sel2_fu_1235_p3 = gmem_addr_read_reg_2421[32'd14];

assign bit_sel30_fu_955_p3 = gmem_addr_read_reg_2421[32'd4];

assign bit_sel3_fu_455_p3 = gmem_addr_read_reg_2421[32'd16];

assign bit_sel4_fu_483_p3 = gmem_addr_read_reg_2421[32'd17];

assign bit_sel5_fu_1207_p3 = gmem_addr_read_reg_2421[32'd13];

assign bit_sel6_fu_511_p3 = gmem_addr_read_reg_2421[32'd18];

assign bit_sel7_fu_539_p3 = gmem_addr_read_reg_2421[32'd19];

assign bit_sel8_fu_1179_p3 = gmem_addr_read_reg_2421[32'd12];

assign bit_sel9_fu_567_p3 = gmem_addr_read_reg_2421[32'd20];

assign bit_sel_fu_1263_p3 = gmem_addr_read_reg_2421[32'd15];

assign first_iter_0_fu_387_p2 = ((select_ln32_fu_379_p3 == 5'd0) ? 1'b1 : 1'b0);

assign golden_w1_address0 = zext_ln37_fu_447_p1;

assign grp_fu_2338_p0 = grp_fu_2338_p00;

assign grp_fu_2338_p00 = select_ln32_2_fu_423_p3;

assign grp_fu_2338_p1 = 12'd25;

assign grp_fu_2338_p2 = grp_fu_2338_p20;

assign grp_fu_2338_p20 = select_ln32_reg_2391_pp0_iter3_reg;

assign icmp_ln32_fu_358_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 12'd3200) ? 1'b1 : 1'b0);

assign icmp_ln36_1_fu_403_p2 = ((add_ln36_fu_398_p2 == 5'd25) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_373_p2 = ((ap_sig_allocacmp_w_load == 5'd25) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_2282_p2 = ((select_ln32_reg_2391_pp0_iter5_reg == 5'd24) ? 1'b1 : 1'b0);

assign m_axi_gmem_0_ARADDR = gmem_addr_reg_2375;

assign m_axi_gmem_0_ARBURST = 2'd0;

assign m_axi_gmem_0_ARCACHE = 4'd0;

assign m_axi_gmem_0_ARID = 1'd0;

assign m_axi_gmem_0_ARLEN = 64'd25;

assign m_axi_gmem_0_ARLOCK = 2'd0;

assign m_axi_gmem_0_ARPROT = 3'd0;

assign m_axi_gmem_0_ARQOS = 4'd0;

assign m_axi_gmem_0_ARREGION = 4'd0;

assign m_axi_gmem_0_ARSIZE = 3'd0;

assign m_axi_gmem_0_ARUSER = 1'd0;

assign m_axi_gmem_0_AWADDR = 64'd0;

assign m_axi_gmem_0_AWBURST = 2'd0;

assign m_axi_gmem_0_AWCACHE = 4'd0;

assign m_axi_gmem_0_AWID = 1'd0;

assign m_axi_gmem_0_AWLEN = 32'd0;

assign m_axi_gmem_0_AWLOCK = 2'd0;

assign m_axi_gmem_0_AWPROT = 3'd0;

assign m_axi_gmem_0_AWQOS = 4'd0;

assign m_axi_gmem_0_AWREGION = 4'd0;

assign m_axi_gmem_0_AWSIZE = 3'd0;

assign m_axi_gmem_0_AWUSER = 1'd0;

assign m_axi_gmem_0_AWVALID = 1'b0;

assign m_axi_gmem_0_BREADY = 1'b0;

assign m_axi_gmem_0_WDATA = 32'd0;

assign m_axi_gmem_0_WID = 1'd0;

assign m_axi_gmem_0_WLAST = 1'b0;

assign m_axi_gmem_0_WSTRB = 4'd0;

assign m_axi_gmem_0_WUSER = 1'd0;

assign m_axi_gmem_0_WVALID = 1'b0;

assign output_r_address0 = output_addr_reg_2411_pp0_iter6_reg;

assign output_r_ce0 = output_r_ce0_local;

assign output_r_d0 = add_ln52_fu_2331_p2;

assign output_r_we0 = output_r_we0_local;

assign p_cast_cast_fu_325_p1 = $signed(p_cast_fu_315_p4);

assign p_cast_fu_315_p4 = {{input_r[63:2]}};

assign popcount_sum_1_fu_2295_p2 = (add_ln43_7_fu_2290_p2 + add_ln43_reg_2603);

assign popcount_sum_2_fu_2313_p3 = ((icmp_ln40_fu_2282_p2[0:0] == 1'b1) ? popcount_sum_1_fu_2295_p2 : popcount_sum_3_fu_2308_p2);

assign popcount_sum_3_fu_2308_p2 = (add_ln47_14_fu_2303_p2 + add_ln43_reg_2603);

assign select_ln32_1_fu_1897_p3 = ((icmp_ln36_reg_2385_pp0_iter5_reg[0:0] == 1'b1) ? 32'd0 : popcount_sum_fu_256);

assign select_ln32_2_fu_423_p3 = ((icmp_ln36_reg_2385_pp0_iter2_reg[0:0] == 1'b1) ? add_ln32_1_fu_417_p2 : n_fu_264);

assign select_ln32_fu_379_p3 = ((icmp_ln36_fu_373_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_w_load);

assign shl_ln52_fu_2326_p2 = popcount_sum_2_reg_2629 << 32'd1;

assign tmp_15_fu_1978_p3 = xnor_result_fu_1928_p2[32'd31];

assign tmp_16_fu_1610_p3 = xor_ln37_15_fu_1390_p2[32'd1];

assign tmp_17_fu_1618_p3 = xor_ln37_14_fu_1384_p2[32'd2];

assign tmp_18_fu_1626_p3 = xor_ln37_13_fu_1378_p2[32'd3];

assign tmp_19_fu_1634_p3 = xor_ln37_12_fu_1372_p2[32'd4];

assign tmp_20_fu_1642_p3 = xor_ln37_11_fu_1366_p2[32'd5];

assign tmp_21_fu_1650_p3 = xor_ln37_10_fu_1360_p2[32'd6];

assign tmp_22_fu_1658_p3 = xor_ln37_9_fu_1354_p2[32'd7];

assign tmp_23_fu_1666_p3 = xor_ln37_8_fu_1348_p2[32'd8];

assign tmp_24_fu_1674_p3 = xor_ln37_7_fu_1342_p2[32'd9];

assign tmp_25_fu_1682_p3 = xor_ln37_6_fu_1336_p2[32'd10];

assign tmp_26_fu_1690_p3 = xor_ln37_5_fu_1330_p2[32'd11];

assign tmp_27_fu_1698_p3 = xor_ln37_4_fu_1324_p2[32'd12];

assign tmp_28_fu_1706_p3 = xor_ln37_3_fu_1318_p2[32'd13];

assign tmp_29_fu_1714_p3 = xor_ln37_2_fu_1312_p2[32'd14];

assign tmp_30_fu_1722_p3 = xor_ln37_1_fu_1306_p2[32'd15];

assign tmp_fu_1486_p3 = xor_ln37_30_fu_1480_p2[32'd16];

assign trunc_ln18_10_fu_580_p1 = gmem_addr_read_reg_2421[19:0];

assign trunc_ln18_11_fu_591_p1 = golden_w1_q0[20:0];

assign trunc_ln18_12_fu_608_p1 = gmem_addr_read_reg_2421[20:0];

assign trunc_ln18_13_fu_619_p1 = golden_w1_q0[21:0];

assign trunc_ln18_14_fu_636_p1 = gmem_addr_read_reg_2421[21:0];

assign trunc_ln18_15_fu_647_p1 = golden_w1_q0[22:0];

assign trunc_ln18_16_fu_664_p1 = gmem_addr_read_reg_2421[22:0];

assign trunc_ln18_17_fu_675_p1 = golden_w1_q0[23:0];

assign trunc_ln18_18_fu_692_p1 = gmem_addr_read_reg_2421[23:0];

assign trunc_ln18_19_fu_703_p1 = golden_w1_q0[24:0];

assign trunc_ln18_1_fu_1917_p1 = gmem_addr_read_reg_2421[30:0];

assign trunc_ln18_20_fu_720_p1 = gmem_addr_read_reg_2421[24:0];

assign trunc_ln18_21_fu_731_p1 = golden_w1_q0[25:0];

assign trunc_ln18_22_fu_748_p1 = gmem_addr_read_reg_2421[25:0];

assign trunc_ln18_23_fu_759_p1 = golden_w1_q0[26:0];

assign trunc_ln18_24_fu_776_p1 = gmem_addr_read_reg_2421[26:0];

assign trunc_ln18_25_fu_787_p1 = golden_w1_q0[27:0];

assign trunc_ln18_26_fu_804_p1 = gmem_addr_read_reg_2421[27:0];

assign trunc_ln18_27_fu_815_p1 = golden_w1_q0[28:0];

assign trunc_ln18_28_fu_832_p1 = gmem_addr_read_reg_2421[28:0];

assign trunc_ln18_29_fu_843_p1 = golden_w1_q0[29:0];

assign trunc_ln18_2_fu_468_p1 = gmem_addr_read_reg_2421[15:0];

assign trunc_ln18_30_fu_860_p1 = gmem_addr_read_reg_2421[29:0];

assign trunc_ln18_31_fu_871_p1 = golden_w1_q0[30:0];

assign trunc_ln18_32_fu_895_p1 = golden_w1_q0[1:0];

assign trunc_ln18_33_fu_912_p1 = gmem_addr_read_reg_2421[1:0];

assign trunc_ln18_34_fu_923_p1 = golden_w1_q0[2:0];

assign trunc_ln18_35_fu_940_p1 = gmem_addr_read_reg_2421[2:0];

assign trunc_ln18_36_fu_951_p1 = golden_w1_q0[3:0];

assign trunc_ln18_37_fu_968_p1 = gmem_addr_read_reg_2421[3:0];

assign trunc_ln18_38_fu_979_p1 = golden_w1_q0[4:0];

assign trunc_ln18_39_fu_996_p1 = gmem_addr_read_reg_2421[4:0];

assign trunc_ln18_3_fu_479_p1 = golden_w1_q0[16:0];

assign trunc_ln18_40_fu_1007_p1 = golden_w1_q0[5:0];

assign trunc_ln18_41_fu_1024_p1 = gmem_addr_read_reg_2421[5:0];

assign trunc_ln18_42_fu_1035_p1 = golden_w1_q0[6:0];

assign trunc_ln18_43_fu_1052_p1 = gmem_addr_read_reg_2421[6:0];

assign trunc_ln18_44_fu_1063_p1 = golden_w1_q0[7:0];

assign trunc_ln18_45_fu_1080_p1 = gmem_addr_read_reg_2421[7:0];

assign trunc_ln18_46_fu_1091_p1 = golden_w1_q0[8:0];

assign trunc_ln18_47_fu_1108_p1 = gmem_addr_read_reg_2421[8:0];

assign trunc_ln18_48_fu_1119_p1 = golden_w1_q0[9:0];

assign trunc_ln18_49_fu_1136_p1 = gmem_addr_read_reg_2421[9:0];

assign trunc_ln18_4_fu_496_p1 = gmem_addr_read_reg_2421[16:0];

assign trunc_ln18_50_fu_1147_p1 = golden_w1_q0[10:0];

assign trunc_ln18_51_fu_1164_p1 = gmem_addr_read_reg_2421[10:0];

assign trunc_ln18_52_fu_1175_p1 = golden_w1_q0[11:0];

assign trunc_ln18_53_fu_1192_p1 = gmem_addr_read_reg_2421[11:0];

assign trunc_ln18_54_fu_1203_p1 = golden_w1_q0[12:0];

assign trunc_ln18_55_fu_1220_p1 = gmem_addr_read_reg_2421[12:0];

assign trunc_ln18_56_fu_1231_p1 = golden_w1_q0[13:0];

assign trunc_ln18_57_fu_1248_p1 = gmem_addr_read_reg_2421[13:0];

assign trunc_ln18_58_fu_1259_p1 = golden_w1_q0[14:0];

assign trunc_ln18_59_fu_1276_p1 = gmem_addr_read_reg_2421[14:0];

assign trunc_ln18_5_fu_507_p1 = golden_w1_q0[17:0];

assign trunc_ln18_60_fu_1287_p1 = golden_w1_q0[15:0];

assign trunc_ln18_61_fu_1296_p1 = golden_w1_q0[0:0];

assign trunc_ln18_6_fu_524_p1 = gmem_addr_read_reg_2421[17:0];

assign trunc_ln18_7_fu_535_p1 = golden_w1_q0[18:0];

assign trunc_ln18_8_fu_552_p1 = gmem_addr_read_reg_2421[18:0];

assign trunc_ln18_9_fu_563_p1 = golden_w1_q0[19:0];

assign trunc_ln18_fu_451_p1 = m_axi_gmem_0_RDATA[0:0];

assign xnor_result_fu_1928_p2 = (xor_ln_fu_1920_p3 ^ golden_w1_load_reg_2497);

assign xor_ln18_10_fu_751_p3 = {{xor_ln18_41_fu_742_p2}, {trunc_ln18_22_fu_748_p1}};

assign xor_ln18_11_fu_779_p3 = {{xor_ln18_42_fu_770_p2}, {trunc_ln18_24_fu_776_p1}};

assign xor_ln18_12_fu_807_p3 = {{xor_ln18_43_fu_798_p2}, {trunc_ln18_26_fu_804_p1}};

assign xor_ln18_13_fu_835_p3 = {{xor_ln18_44_fu_826_p2}, {trunc_ln18_28_fu_832_p1}};

assign xor_ln18_14_fu_863_p3 = {{xor_ln18_45_fu_854_p2}, {trunc_ln18_30_fu_860_p1}};

assign xor_ln18_15_fu_888_p3 = {{xor_ln18_46_fu_882_p2}, {trunc_ln18_reg_2491}};

assign xor_ln18_16_fu_915_p3 = {{xor_ln18_47_fu_906_p2}, {trunc_ln18_33_fu_912_p1}};

assign xor_ln18_17_fu_943_p3 = {{xor_ln18_48_fu_934_p2}, {trunc_ln18_35_fu_940_p1}};

assign xor_ln18_18_fu_971_p3 = {{xor_ln18_49_fu_962_p2}, {trunc_ln18_37_fu_968_p1}};

assign xor_ln18_19_fu_999_p3 = {{xor_ln18_50_fu_990_p2}, {trunc_ln18_39_fu_996_p1}};

assign xor_ln18_1_fu_471_p3 = {{xor_ln18_fu_462_p2}, {trunc_ln18_2_fu_468_p1}};

assign xor_ln18_20_fu_1027_p3 = {{xor_ln18_51_fu_1018_p2}, {trunc_ln18_41_fu_1024_p1}};

assign xor_ln18_21_fu_1055_p3 = {{xor_ln18_52_fu_1046_p2}, {trunc_ln18_43_fu_1052_p1}};

assign xor_ln18_22_fu_1083_p3 = {{xor_ln18_53_fu_1074_p2}, {trunc_ln18_45_fu_1080_p1}};

assign xor_ln18_23_fu_1111_p3 = {{xor_ln18_54_fu_1102_p2}, {trunc_ln18_47_fu_1108_p1}};

assign xor_ln18_24_fu_1139_p3 = {{xor_ln18_55_fu_1130_p2}, {trunc_ln18_49_fu_1136_p1}};

assign xor_ln18_25_fu_1167_p3 = {{xor_ln18_56_fu_1158_p2}, {trunc_ln18_51_fu_1164_p1}};

assign xor_ln18_26_fu_1195_p3 = {{xor_ln18_57_fu_1186_p2}, {trunc_ln18_53_fu_1192_p1}};

assign xor_ln18_27_fu_1223_p3 = {{xor_ln18_58_fu_1214_p2}, {trunc_ln18_55_fu_1220_p1}};

assign xor_ln18_28_fu_1251_p3 = {{xor_ln18_59_fu_1242_p2}, {trunc_ln18_57_fu_1248_p1}};

assign xor_ln18_29_fu_1279_p3 = {{xor_ln18_60_fu_1270_p2}, {trunc_ln18_59_fu_1276_p1}};

assign xor_ln18_2_fu_499_p3 = {{xor_ln18_32_fu_490_p2}, {trunc_ln18_4_fu_496_p1}};

assign xor_ln18_30_fu_1911_p2 = (bit_sel1_fu_1904_p3 ^ 1'd1);

assign xor_ln18_31_fu_1291_p2 = (trunc_ln18_reg_2491 ^ 1'd1);

assign xor_ln18_32_fu_490_p2 = (bit_sel4_fu_483_p3 ^ 1'd1);

assign xor_ln18_33_fu_518_p2 = (bit_sel6_fu_511_p3 ^ 1'd1);

assign xor_ln18_34_fu_546_p2 = (bit_sel7_fu_539_p3 ^ 1'd1);

assign xor_ln18_35_fu_574_p2 = (bit_sel9_fu_567_p3 ^ 1'd1);

assign xor_ln18_36_fu_602_p2 = (bit_sel10_fu_595_p3 ^ 1'd1);

assign xor_ln18_37_fu_630_p2 = (bit_sel12_fu_623_p3 ^ 1'd1);

assign xor_ln18_38_fu_658_p2 = (bit_sel13_fu_651_p3 ^ 1'd1);

assign xor_ln18_39_fu_686_p2 = (bit_sel15_fu_679_p3 ^ 1'd1);

assign xor_ln18_3_fu_527_p3 = {{xor_ln18_33_fu_518_p2}, {trunc_ln18_6_fu_524_p1}};

assign xor_ln18_40_fu_714_p2 = (bit_sel16_fu_707_p3 ^ 1'd1);

assign xor_ln18_41_fu_742_p2 = (bit_sel18_fu_735_p3 ^ 1'd1);

assign xor_ln18_42_fu_770_p2 = (bit_sel19_fu_763_p3 ^ 1'd1);

assign xor_ln18_43_fu_798_p2 = (bit_sel21_fu_791_p3 ^ 1'd1);

assign xor_ln18_44_fu_826_p2 = (bit_sel22_fu_819_p3 ^ 1'd1);

assign xor_ln18_45_fu_854_p2 = (bit_sel24_fu_847_p3 ^ 1'd1);

assign xor_ln18_46_fu_882_p2 = (bit_sel25_fu_875_p3 ^ 1'd1);

assign xor_ln18_47_fu_906_p2 = (bit_sel27_fu_899_p3 ^ 1'd1);

assign xor_ln18_48_fu_934_p2 = (bit_sel28_fu_927_p3 ^ 1'd1);

assign xor_ln18_49_fu_962_p2 = (bit_sel30_fu_955_p3 ^ 1'd1);

assign xor_ln18_4_fu_555_p3 = {{xor_ln18_34_fu_546_p2}, {trunc_ln18_8_fu_552_p1}};

assign xor_ln18_50_fu_990_p2 = (bit_sel29_fu_983_p3 ^ 1'd1);

assign xor_ln18_51_fu_1018_p2 = (bit_sel26_fu_1011_p3 ^ 1'd1);

assign xor_ln18_52_fu_1046_p2 = (bit_sel23_fu_1039_p3 ^ 1'd1);

assign xor_ln18_53_fu_1074_p2 = (bit_sel20_fu_1067_p3 ^ 1'd1);

assign xor_ln18_54_fu_1102_p2 = (bit_sel17_fu_1095_p3 ^ 1'd1);

assign xor_ln18_55_fu_1130_p2 = (bit_sel14_fu_1123_p3 ^ 1'd1);

assign xor_ln18_56_fu_1158_p2 = (bit_sel11_fu_1151_p3 ^ 1'd1);

assign xor_ln18_57_fu_1186_p2 = (bit_sel8_fu_1179_p3 ^ 1'd1);

assign xor_ln18_58_fu_1214_p2 = (bit_sel5_fu_1207_p3 ^ 1'd1);

assign xor_ln18_59_fu_1242_p2 = (bit_sel2_fu_1235_p3 ^ 1'd1);

assign xor_ln18_5_fu_583_p3 = {{xor_ln18_35_fu_574_p2}, {trunc_ln18_10_fu_580_p1}};

assign xor_ln18_60_fu_1270_p2 = (bit_sel_fu_1263_p3 ^ 1'd1);

assign xor_ln18_6_fu_611_p3 = {{xor_ln18_36_fu_602_p2}, {trunc_ln18_12_fu_608_p1}};

assign xor_ln18_7_fu_639_p3 = {{xor_ln18_37_fu_630_p2}, {trunc_ln18_14_fu_636_p1}};

assign xor_ln18_8_fu_667_p3 = {{xor_ln18_38_fu_658_p2}, {trunc_ln18_16_fu_664_p1}};

assign xor_ln18_9_fu_695_p3 = {{xor_ln18_39_fu_686_p2}, {trunc_ln18_18_fu_692_p1}};

assign xor_ln18_fu_462_p2 = (bit_sel3_fu_455_p3 ^ 1'd1);

assign xor_ln18_s_fu_723_p3 = {{xor_ln18_40_fu_714_p2}, {trunc_ln18_20_fu_720_p1}};

assign xor_ln37_10_fu_1360_p2 = (xor_ln18_20_fu_1027_p3 ^ trunc_ln18_42_fu_1035_p1);

assign xor_ln37_11_fu_1366_p2 = (xor_ln18_19_fu_999_p3 ^ trunc_ln18_40_fu_1007_p1);

assign xor_ln37_12_fu_1372_p2 = (xor_ln18_18_fu_971_p3 ^ trunc_ln18_38_fu_979_p1);

assign xor_ln37_13_fu_1378_p2 = (xor_ln18_17_fu_943_p3 ^ trunc_ln18_36_fu_951_p1);

assign xor_ln37_14_fu_1384_p2 = (xor_ln18_16_fu_915_p3 ^ trunc_ln18_34_fu_923_p1);

assign xor_ln37_15_fu_1390_p2 = (xor_ln18_15_fu_888_p3 ^ trunc_ln18_32_fu_895_p1);

assign xor_ln37_16_fu_1396_p2 = (xor_ln18_14_fu_863_p3 ^ trunc_ln18_31_fu_871_p1);

assign xor_ln37_17_fu_1402_p2 = (xor_ln18_13_fu_835_p3 ^ trunc_ln18_29_fu_843_p1);

assign xor_ln37_18_fu_1408_p2 = (xor_ln18_12_fu_807_p3 ^ trunc_ln18_27_fu_815_p1);

assign xor_ln37_19_fu_1414_p2 = (xor_ln18_11_fu_779_p3 ^ trunc_ln18_25_fu_787_p1);

assign xor_ln37_1_fu_1306_p2 = (xor_ln18_29_fu_1279_p3 ^ trunc_ln18_60_fu_1287_p1);

assign xor_ln37_20_fu_1420_p2 = (xor_ln18_10_fu_751_p3 ^ trunc_ln18_23_fu_759_p1);

assign xor_ln37_21_fu_1426_p2 = (xor_ln18_s_fu_723_p3 ^ trunc_ln18_21_fu_731_p1);

assign xor_ln37_22_fu_1432_p2 = (xor_ln18_9_fu_695_p3 ^ trunc_ln18_19_fu_703_p1);

assign xor_ln37_23_fu_1438_p2 = (xor_ln18_8_fu_667_p3 ^ trunc_ln18_17_fu_675_p1);

assign xor_ln37_24_fu_1444_p2 = (xor_ln18_7_fu_639_p3 ^ trunc_ln18_15_fu_647_p1);

assign xor_ln37_25_fu_1450_p2 = (xor_ln18_6_fu_611_p3 ^ trunc_ln18_13_fu_619_p1);

assign xor_ln37_26_fu_1456_p2 = (xor_ln18_5_fu_583_p3 ^ trunc_ln18_11_fu_591_p1);

assign xor_ln37_27_fu_1462_p2 = (xor_ln18_4_fu_555_p3 ^ trunc_ln18_9_fu_563_p1);

assign xor_ln37_28_fu_1468_p2 = (xor_ln18_3_fu_527_p3 ^ trunc_ln18_7_fu_535_p1);

assign xor_ln37_29_fu_1474_p2 = (xor_ln18_2_fu_499_p3 ^ trunc_ln18_5_fu_507_p1);

assign xor_ln37_2_fu_1312_p2 = (xor_ln18_28_fu_1251_p3 ^ trunc_ln18_58_fu_1259_p1);

assign xor_ln37_30_fu_1480_p2 = (xor_ln18_1_fu_471_p3 ^ trunc_ln18_3_fu_479_p1);

assign xor_ln37_3_fu_1318_p2 = (xor_ln18_27_fu_1223_p3 ^ trunc_ln18_56_fu_1231_p1);

assign xor_ln37_4_fu_1324_p2 = (xor_ln18_26_fu_1195_p3 ^ trunc_ln18_54_fu_1203_p1);

assign xor_ln37_5_fu_1330_p2 = (xor_ln18_25_fu_1167_p3 ^ trunc_ln18_52_fu_1175_p1);

assign xor_ln37_6_fu_1336_p2 = (xor_ln18_24_fu_1139_p3 ^ trunc_ln18_50_fu_1147_p1);

assign xor_ln37_7_fu_1342_p2 = (xor_ln18_23_fu_1111_p3 ^ trunc_ln18_48_fu_1119_p1);

assign xor_ln37_8_fu_1348_p2 = (xor_ln18_22_fu_1083_p3 ^ trunc_ln18_46_fu_1091_p1);

assign xor_ln37_9_fu_1354_p2 = (xor_ln18_21_fu_1055_p3 ^ trunc_ln18_44_fu_1063_p1);

assign xor_ln37_fu_1300_p2 = (xor_ln18_31_fu_1291_p2 ^ trunc_ln18_61_fu_1296_p1);

assign xor_ln_fu_1920_p3 = {{xor_ln18_30_fu_1911_p2}, {trunc_ln18_1_fu_1917_p1}};

assign zext_ln10_10_fu_1960_p1 = tmp_9_reg_2548;

assign zext_ln10_11_fu_1963_p1 = tmp_10_reg_2553;

assign zext_ln10_12_fu_1966_p1 = tmp_11_reg_2558;

assign zext_ln10_13_fu_1969_p1 = tmp_12_reg_2563;

assign zext_ln10_14_fu_1972_p1 = tmp_13_reg_2568;

assign zext_ln10_15_fu_1975_p1 = tmp_14_reg_2573;

assign zext_ln10_16_fu_1986_p1 = tmp_15_fu_1978_p3;

assign zext_ln10_1_fu_1933_p1 = tmp_1_reg_2507;

assign zext_ln10_2_fu_1936_p1 = tmp_1_reg_2507;

assign zext_ln10_3_fu_1939_p1 = tmp_2_reg_2513;

assign zext_ln10_4_fu_1942_p1 = tmp_3_reg_2518;

assign zext_ln10_5_fu_1945_p1 = tmp_4_reg_2523;

assign zext_ln10_6_fu_1948_p1 = tmp_5_reg_2528;

assign zext_ln10_7_fu_1951_p1 = tmp_6_reg_2533;

assign zext_ln10_8_fu_1954_p1 = tmp_7_reg_2538;

assign zext_ln10_9_fu_1957_p1 = tmp_8_reg_2543;

assign zext_ln10_fu_1494_p1 = tmp_fu_1486_p3;

assign zext_ln32_fu_430_p1 = select_ln32_2_fu_423_p3;

assign zext_ln37_fu_447_p1 = grp_fu_2338_p3;

assign zext_ln43_10_fu_2287_p1 = add_ln43_14_reg_2614;

assign zext_ln43_1_fu_2017_p1 = add_ln43_4_fu_2011_p2;

assign zext_ln43_2_fu_2027_p1 = add_ln43_5_fu_2021_p2;

assign zext_ln43_3_fu_2037_p1 = add_ln43_6_fu_2031_p2;

assign zext_ln43_4_fu_2053_p1 = add_ln43_8_fu_2047_p2;

assign zext_ln43_5_fu_2063_p1 = add_ln43_9_fu_2057_p2;

assign zext_ln43_6_fu_2073_p1 = add_ln43_10_fu_2067_p2;

assign zext_ln43_7_fu_2083_p1 = add_ln43_11_fu_2077_p2;

assign zext_ln43_8_fu_2093_p1 = add_ln43_12_fu_2087_p2;

assign zext_ln43_9_fu_2103_p1 = add_ln43_13_fu_2097_p2;

assign zext_ln43_fu_2001_p1 = add_ln43_2_fu_1996_p2;

assign zext_ln47_10_fu_1770_p1 = tmp_22_fu_1658_p3;

assign zext_ln47_11_fu_1774_p1 = tmp_25_fu_1682_p3;

assign zext_ln47_12_fu_1778_p1 = tmp_27_fu_1698_p3;

assign zext_ln47_13_fu_1782_p1 = tmp_16_fu_1610_p3;

assign zext_ln47_14_fu_1786_p1 = xor_ln37_fu_1300_p2;

assign zext_ln47_15_fu_1790_p1 = tmp_23_fu_1666_p3;

assign zext_ln47_16_fu_1800_p1 = add_ln47_1_fu_1794_p2;

assign zext_ln47_17_fu_1816_p1 = add_ln47_3_fu_1810_p2;

assign zext_ln47_18_fu_1826_p1 = add_ln47_4_fu_1820_p2;

assign zext_ln47_19_fu_2113_p1 = add_ln47_5_reg_2583;

assign zext_ln47_1_fu_1734_p1 = tmp_20_fu_1642_p3;

assign zext_ln47_20_fu_1842_p1 = add_ln47_7_fu_1836_p2;

assign zext_ln47_21_fu_1852_p1 = add_ln47_8_fu_1846_p2;

assign zext_ln47_22_fu_2121_p1 = add_ln47_9_reg_2588;

assign zext_ln47_23_fu_1868_p1 = add_ln47_10_fu_1862_p2;

assign zext_ln47_24_fu_1878_p1 = add_ln47_11_fu_1872_p2;

assign zext_ln47_25_fu_2124_p1 = add_ln47_12_reg_2593;

assign zext_ln47_26_fu_2133_p1 = add_ln47_13_fu_2127_p2;

assign zext_ln47_27_fu_2143_p1 = add_ln47_15_reg_2598;

assign zext_ln47_28_fu_2152_p1 = add_ln47_16_fu_2146_p2;

assign zext_ln47_29_fu_2162_p1 = add_ln47_17_fu_2156_p2;

assign zext_ln47_2_fu_1738_p1 = tmp_28_fu_1706_p3;

assign zext_ln47_30_fu_2172_p1 = add_ln47_18_fu_2166_p2;

assign zext_ln47_31_fu_2182_p1 = add_ln47_19_fu_2176_p2;

assign zext_ln47_32_fu_2192_p1 = add_ln47_20_fu_2186_p2;

assign zext_ln47_33_fu_2202_p1 = add_ln47_21_fu_2196_p2;

assign zext_ln47_34_fu_2212_p1 = add_ln47_22_fu_2206_p2;

assign zext_ln47_35_fu_2222_p1 = add_ln47_23_fu_2216_p2;

assign zext_ln47_36_fu_2232_p1 = add_ln47_24_fu_2226_p2;

assign zext_ln47_37_fu_2242_p1 = add_ln47_25_fu_2236_p2;

assign zext_ln47_38_fu_2252_p1 = add_ln47_26_fu_2246_p2;

assign zext_ln47_39_fu_2262_p1 = add_ln47_27_fu_2256_p2;

assign zext_ln47_3_fu_1742_p1 = tmp_17_fu_1618_p3;

assign zext_ln47_40_fu_2272_p1 = add_ln47_28_fu_2266_p2;

assign zext_ln47_41_fu_2300_p1 = add_ln47_29_reg_2624;

assign zext_ln47_4_fu_1746_p1 = tmp_18_fu_1626_p3;

assign zext_ln47_5_fu_1750_p1 = tmp_29_fu_1714_p3;

assign zext_ln47_6_fu_1754_p1 = tmp_26_fu_1690_p3;

assign zext_ln47_7_fu_1758_p1 = tmp_30_fu_1722_p3;

assign zext_ln47_8_fu_1762_p1 = tmp_21_fu_1650_p3;

assign zext_ln47_9_fu_1766_p1 = tmp_19_fu_1634_p3;

assign zext_ln47_fu_1730_p1 = tmp_24_fu_1674_p3;

always @ (posedge ap_clk) begin
    zext_ln10_reg_2502[1] <= 1'b0;
end

endmodule //bnn_dense_layer_2
