// ==============================================================
// Generated by Vitis HLS v2024.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bnn_bnn_Pipeline_VITIS_LOOP_66_21 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer2_output_address0,
        layer2_output_ce0,
        layer2_output_q0,
        layer2_quantized_1_out,
        layer2_quantized_1_out_ap_vld,
        layer2_quantized_out,
        layer2_quantized_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] layer2_output_address0;
output   layer2_output_ce0;
input  [8:0] layer2_output_q0;
output  [31:0] layer2_quantized_1_out;
output   layer2_quantized_1_out_ap_vld;
output  [31:0] layer2_quantized_out;
output   layer2_quantized_out_ap_vld;

reg ap_idle;
reg layer2_quantized_1_out_ap_vld;
reg layer2_quantized_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln66_fu_99_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [6:0] i_1_reg_246;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln66_fu_111_p1;
wire    ap_block_pp0_stage0;
reg   [6:0] i_fu_42;
wire   [6:0] add_ln66_fu_105_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_1;
reg   [31:0] layer2_quantized_fu_46;
wire   [31:0] or_i181_fu_197_p3;
reg   [31:0] layer2_quantized_1_fu_50;
wire   [31:0] or_i184_fu_189_p3;
wire    ap_block_pp0_stage0_01001;
reg    layer2_output_ce0_local;
wire   [4:0] trunc_ln67_fu_127_p1;
wire   [4:0] bit_pos_fu_137_p2;
wire   [31:0] zext_ln68_fu_143_p1;
wire   [0:0] tmp_fu_130_p3;
wire   [31:0] select_ln71_2_fu_159_p3;
wire   [31:0] shl_ln71_fu_153_p2;
wire   [31:0] or_ln71_fu_167_p2;
wire   [0:0] icmp_ln70_fu_147_p2;
wire   [31:0] select_ln71_fu_173_p3;
wire   [31:0] select_ln71_1_fu_181_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_fu_42 = 7'd0;
#0 layer2_quantized_fu_46 = 32'd0;
#0 layer2_quantized_1_fu_50 = 32'd0;
#0 ap_done_reg = 1'b0;
end

bnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln66_fu_99_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_42 <= add_ln66_fu_105_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_42 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            layer2_quantized_1_fu_50 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            layer2_quantized_1_fu_50 <= or_i184_fu_189_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            layer2_quantized_fu_46 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            layer2_quantized_fu_46 <= or_i181_fu_197_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_1_reg_246 <= ap_sig_allocacmp_i_1;
    end
end

always @ (*) begin
    if (((icmp_ln66_fu_99_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_42;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_output_ce0_local = 1'b1;
    end else begin
        layer2_output_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln66_fu_99_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_quantized_1_out_ap_vld = 1'b1;
    end else begin
        layer2_quantized_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln66_fu_99_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_quantized_out_ap_vld = 1'b1;
    end else begin
        layer2_quantized_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln66_fu_105_p2 = (ap_sig_allocacmp_i_1 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bit_pos_fu_137_p2 = (trunc_ln67_fu_127_p1 ^ 5'd31);

assign icmp_ln66_fu_99_p2 = ((ap_sig_allocacmp_i_1 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_147_p2 = (($signed(layer2_output_q0) < $signed(9'd1)) ? 1'b1 : 1'b0);

assign layer2_output_address0 = zext_ln66_fu_111_p1;

assign layer2_output_ce0 = layer2_output_ce0_local;

assign layer2_quantized_1_out = layer2_quantized_1_fu_50;

assign layer2_quantized_out = layer2_quantized_fu_46;

assign or_i181_fu_197_p3 = ((icmp_ln70_fu_147_p2[0:0] == 1'b1) ? select_ln71_1_fu_181_p3 : layer2_quantized_fu_46);

assign or_i184_fu_189_p3 = ((icmp_ln70_fu_147_p2[0:0] == 1'b1) ? select_ln71_fu_173_p3 : layer2_quantized_1_fu_50);

assign or_ln71_fu_167_p2 = (shl_ln71_fu_153_p2 | select_ln71_2_fu_159_p3);

assign select_ln71_1_fu_181_p3 = ((tmp_fu_130_p3[0:0] == 1'b1) ? layer2_quantized_fu_46 : or_ln71_fu_167_p2);

assign select_ln71_2_fu_159_p3 = ((tmp_fu_130_p3[0:0] == 1'b1) ? layer2_quantized_1_fu_50 : layer2_quantized_fu_46);

assign select_ln71_fu_173_p3 = ((tmp_fu_130_p3[0:0] == 1'b1) ? or_ln71_fu_167_p2 : layer2_quantized_1_fu_50);

assign shl_ln71_fu_153_p2 = 32'd1 << zext_ln68_fu_143_p1;

assign tmp_fu_130_p3 = i_1_reg_246[32'd5];

assign trunc_ln67_fu_127_p1 = i_1_reg_246[4:0];

assign zext_ln66_fu_111_p1 = ap_sig_allocacmp_i_1;

assign zext_ln68_fu_143_p1 = bit_pos_fu_137_p2;

endmodule //bnn_bnn_Pipeline_VITIS_LOOP_66_21
