// ==============================================================
// Generated by Vitis HLS v2024.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bnn_bnn_Pipeline_VITIS_LOOP_66_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer1_quantized_reload,
        layer1_quantized_3_reload,
        layer1_quantized_2_reload,
        layer1_quantized_1_reload,
        layer1_output_address0,
        layer1_output_ce0,
        layer1_output_q0,
        layer1_quantized_7_out,
        layer1_quantized_7_out_ap_vld,
        layer1_quantized_6_out,
        layer1_quantized_6_out_ap_vld,
        layer1_quantized_5_out,
        layer1_quantized_5_out_ap_vld,
        layer1_quantized_4_out,
        layer1_quantized_4_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] layer1_quantized_reload;
input  [31:0] layer1_quantized_3_reload;
input  [31:0] layer1_quantized_2_reload;
input  [31:0] layer1_quantized_1_reload;
output  [6:0] layer1_output_address0;
output   layer1_output_ce0;
input  [31:0] layer1_output_q0;
output  [31:0] layer1_quantized_7_out;
output   layer1_quantized_7_out_ap_vld;
output  [31:0] layer1_quantized_6_out;
output   layer1_quantized_6_out_ap_vld;
output  [31:0] layer1_quantized_5_out;
output   layer1_quantized_5_out_ap_vld;
output  [31:0] layer1_quantized_4_out;
output   layer1_quantized_4_out_ap_vld;

reg ap_idle;
reg layer1_quantized_7_out_ap_vld;
reg layer1_quantized_6_out_ap_vld;
reg layer1_quantized_5_out_ap_vld;
reg layer1_quantized_4_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln66_fu_183_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [7:0] i_reg_444;
reg   [7:0] i_reg_444_pp0_iter1_reg;
reg   [0:0] icmp_ln66_reg_450;
wire   [0:0] icmp_ln70_fu_205_p2;
reg   [0:0] icmp_ln70_reg_459;
wire   [63:0] zext_ln66_fu_195_p1;
wire    ap_block_pp0_stage0;
reg   [7:0] i_1_fu_70;
wire   [7:0] add_ln66_fu_189_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i;
reg   [31:0] layer1_quantized_4_fu_74;
wire   [31:0] or_i10_fu_361_p3;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [31:0] layer1_quantized_5_fu_78;
wire   [31:0] or_i13_fu_348_p3;
reg   [31:0] layer1_quantized_6_fu_82;
wire   [31:0] or_i16_fu_335_p3;
reg   [31:0] layer1_quantized_7_fu_86;
wire   [31:0] or_i20_fu_322_p3;
wire    ap_block_pp0_stage0_01001;
reg    layer1_output_ce0_local;
wire   [4:0] trunc_ln67_fu_223_p1;
wire   [4:0] bit_pos_fu_235_p2;
wire   [31:0] zext_ln68_fu_241_p1;
wire   [31:0] tmp_fu_251_p9;
wire   [1:0] tmp_fu_251_p10;
wire   [1:0] trunc_ln67_3_fu_226_p4;
wire   [31:0] tmp_fu_251_p11;
wire   [31:0] shl_ln71_fu_245_p2;
wire   [0:0] icmp_ln71_1_fu_287_p2;
wire   [0:0] icmp_ln71_2_fu_293_p2;
wire   [0:0] or_ln71_1_fu_304_p2;
wire   [0:0] icmp_ln71_fu_281_p2;
wire   [0:0] or_ln71_2_fu_310_p2;
wire   [0:0] xor_ln70_fu_299_p2;
wire   [0:0] or_ln71_3_fu_316_p2;
wire   [31:0] or_ln71_fu_275_p2;
wire   [0:0] and_ln71_fu_330_p2;
wire   [0:0] and_ln71_1_fu_343_p2;
wire   [0:0] and_ln71_2_fu_356_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] tmp_fu_251_p1;
wire   [1:0] tmp_fu_251_p3;
wire  signed [1:0] tmp_fu_251_p5;
wire  signed [1:0] tmp_fu_251_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_1_fu_70 = 8'd0;
#0 layer1_quantized_4_fu_74 = 32'd0;
#0 layer1_quantized_5_fu_78 = 32'd0;
#0 layer1_quantized_6_fu_82 = 32'd0;
#0 layer1_quantized_7_fu_86 = 32'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U11(
    .din0(layer1_quantized_4_fu_74),
    .din1(layer1_quantized_5_fu_78),
    .din2(layer1_quantized_6_fu_82),
    .din3(layer1_quantized_7_fu_86),
    .def(tmp_fu_251_p9),
    .sel(tmp_fu_251_p10),
    .dout(tmp_fu_251_p11)
);

bnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln66_fu_183_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_70 <= add_ln66_fu_189_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_70 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            layer1_quantized_4_fu_74 <= layer1_quantized_1_reload;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            layer1_quantized_4_fu_74 <= or_i10_fu_361_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            layer1_quantized_5_fu_78 <= layer1_quantized_2_reload;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            layer1_quantized_5_fu_78 <= or_i13_fu_348_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            layer1_quantized_6_fu_82 <= layer1_quantized_3_reload;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            layer1_quantized_6_fu_82 <= or_i16_fu_335_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            layer1_quantized_7_fu_86 <= layer1_quantized_reload;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            layer1_quantized_7_fu_86 <= or_i20_fu_322_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        i_reg_444 <= ap_sig_allocacmp_i;
        i_reg_444_pp0_iter1_reg <= i_reg_444;
        icmp_ln66_reg_450 <= icmp_ln66_fu_183_p2;
        icmp_ln70_reg_459 <= icmp_ln70_fu_205_p2;
    end
end

always @ (*) begin
    if (((icmp_ln66_fu_183_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 8'd0;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer1_output_ce0_local = 1'b1;
    end else begin
        layer1_output_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln66_reg_450 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        layer1_quantized_4_out_ap_vld = 1'b1;
    end else begin
        layer1_quantized_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln66_reg_450 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        layer1_quantized_5_out_ap_vld = 1'b1;
    end else begin
        layer1_quantized_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln66_reg_450 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        layer1_quantized_6_out_ap_vld = 1'b1;
    end else begin
        layer1_quantized_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln66_reg_450 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        layer1_quantized_7_out_ap_vld = 1'b1;
    end else begin
        layer1_quantized_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln66_fu_189_p2 = (ap_sig_allocacmp_i + 8'd1);

assign and_ln71_1_fu_343_p2 = (icmp_ln71_1_fu_287_p2 & icmp_ln70_reg_459);

assign and_ln71_2_fu_356_p2 = (icmp_ln71_fu_281_p2 & icmp_ln70_reg_459);

assign and_ln71_fu_330_p2 = (icmp_ln71_2_fu_293_p2 & icmp_ln70_reg_459);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bit_pos_fu_235_p2 = (trunc_ln67_fu_223_p1 ^ 5'd31);

assign icmp_ln66_fu_183_p2 = ((ap_sig_allocacmp_i == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_205_p2 = (($signed(layer1_output_q0) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign icmp_ln71_1_fu_287_p2 = ((trunc_ln67_3_fu_226_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln71_2_fu_293_p2 = ((trunc_ln67_3_fu_226_p4 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_281_p2 = ((trunc_ln67_3_fu_226_p4 == 2'd0) ? 1'b1 : 1'b0);

assign layer1_output_address0 = zext_ln66_fu_195_p1;

assign layer1_output_ce0 = layer1_output_ce0_local;

assign layer1_quantized_4_out = layer1_quantized_4_fu_74;

assign layer1_quantized_5_out = layer1_quantized_5_fu_78;

assign layer1_quantized_6_out = layer1_quantized_6_fu_82;

assign layer1_quantized_7_out = layer1_quantized_7_fu_86;

assign or_i10_fu_361_p3 = ((and_ln71_2_fu_356_p2[0:0] == 1'b1) ? or_ln71_fu_275_p2 : layer1_quantized_4_fu_74);

assign or_i13_fu_348_p3 = ((and_ln71_1_fu_343_p2[0:0] == 1'b1) ? or_ln71_fu_275_p2 : layer1_quantized_5_fu_78);

assign or_i16_fu_335_p3 = ((and_ln71_fu_330_p2[0:0] == 1'b1) ? or_ln71_fu_275_p2 : layer1_quantized_6_fu_82);

assign or_i20_fu_322_p3 = ((or_ln71_3_fu_316_p2[0:0] == 1'b1) ? layer1_quantized_7_fu_86 : or_ln71_fu_275_p2);

assign or_ln71_1_fu_304_p2 = (icmp_ln71_2_fu_293_p2 | icmp_ln71_1_fu_287_p2);

assign or_ln71_2_fu_310_p2 = (or_ln71_1_fu_304_p2 | icmp_ln71_fu_281_p2);

assign or_ln71_3_fu_316_p2 = (xor_ln70_fu_299_p2 | or_ln71_2_fu_310_p2);

assign or_ln71_fu_275_p2 = (tmp_fu_251_p11 | shl_ln71_fu_245_p2);

assign shl_ln71_fu_245_p2 = 32'd1 << zext_ln68_fu_241_p1;

assign tmp_fu_251_p10 = {{i_reg_444_pp0_iter1_reg[6:5]}};

assign tmp_fu_251_p9 = 'bx;

assign trunc_ln67_3_fu_226_p4 = {{i_reg_444_pp0_iter1_reg[6:5]}};

assign trunc_ln67_fu_223_p1 = i_reg_444_pp0_iter1_reg[4:0];

assign xor_ln70_fu_299_p2 = (icmp_ln70_reg_459 ^ 1'd1);

assign zext_ln66_fu_195_p1 = ap_sig_allocacmp_i;

assign zext_ln68_fu_241_p1 = bit_pos_fu_235_p2;

endmodule //bnn_bnn_Pipeline_VITIS_LOOP_66_2
