// ==============================================================
// Generated by Vitis HLS v2024.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bnn_dense_layer_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_read;
input  [31:0] p_read1;
output  [8:0] ap_return_0;
output  [8:0] ap_return_1;
output  [8:0] ap_return_2;
output  [8:0] ap_return_3;
output  [8:0] ap_return_4;
output  [8:0] ap_return_5;
output  [8:0] ap_return_6;
output  [8:0] ap_return_7;
output  [8:0] ap_return_8;
output  [8:0] ap_return_9;

reg ap_idle;
reg[8:0] ap_return_0;
reg[8:0] ap_return_1;
reg[8:0] ap_return_2;
reg[8:0] ap_return_3;
reg[8:0] ap_return_4;
reg[8:0] ap_return_5;
reg[8:0] ap_return_6;
reg[8:0] ap_return_7;
reg[8:0] ap_return_8;
reg[8:0] ap_return_9;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln34_fu_304_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] p_ZL9golden_w3_0_address0;
wire   [31:0] p_ZL9golden_w3_0_q0;
wire   [3:0] p_ZL9golden_w3_0_address1;
wire   [31:0] p_ZL9golden_w3_0_q1;
wire   [3:0] p_ZL9golden_w3_1_address0;
wire   [31:0] p_ZL9golden_w3_1_q0;
wire   [3:0] p_ZL9golden_w3_1_address1;
wire   [31:0] p_ZL9golden_w3_1_q1;
reg   [31:0] p_read1121_reg_4382;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] p_read120_reg_4387;
wire   [30:0] trunc_ln18_fu_252_p1;
reg   [30:0] trunc_ln18_reg_4452;
wire   [30:0] trunc_ln18_1_fu_256_p1;
reg   [30:0] trunc_ln18_1_reg_4457;
reg   [3:0] n21_load_reg_4462;
reg   [3:0] n21_load_reg_4462_pp0_iter1_reg;
reg   [3:0] n21_load_reg_4462_pp0_iter2_reg;
reg   [3:0] n21_load_reg_4462_pp0_iter3_reg;
reg   [1:0] tmp_s_reg_4490;
reg   [1:0] tmp_31_reg_4495;
reg   [1:0] tmp_32_reg_4501;
reg   [1:0] tmp_33_reg_4507;
reg   [1:0] tmp_34_reg_4513;
reg   [1:0] tmp_35_reg_4519;
reg   [1:0] tmp_36_reg_4525;
wire   [1:0] trunc_ln9_fu_953_p1;
reg   [1:0] trunc_ln9_reg_4531;
reg   [1:0] tmp_37_reg_4537;
reg   [1:0] tmp_38_reg_4542;
reg   [1:0] tmp_39_reg_4548;
reg   [1:0] tmp_40_reg_4554;
reg   [1:0] tmp_41_reg_4560;
reg   [1:0] tmp_42_reg_4566;
reg   [1:0] tmp_43_reg_4572;
reg   [1:0] tmp_44_reg_4578;
reg   [1:0] tmp_81_reg_4584;
reg   [1:0] tmp_82_reg_4589;
reg   [1:0] tmp_83_reg_4595;
reg   [1:0] tmp_84_reg_4601;
reg   [1:0] tmp_85_reg_4607;
reg   [1:0] tmp_86_reg_4613;
reg   [1:0] tmp_87_reg_4619;
wire   [1:0] trunc_ln9_1_fu_1675_p1;
reg   [1:0] trunc_ln9_1_reg_4625;
reg   [1:0] tmp_88_reg_4631;
reg   [1:0] tmp_89_reg_4636;
reg   [1:0] tmp_90_reg_4642;
reg   [1:0] tmp_91_reg_4648;
reg   [1:0] tmp_92_reg_4654;
reg   [1:0] tmp_93_reg_4660;
reg   [1:0] tmp_94_reg_4666;
reg   [1:0] tmp_95_reg_4672;
reg   [1:0] tmp_133_reg_4678;
reg   [1:0] tmp_134_reg_4683;
reg   [1:0] tmp_135_reg_4689;
reg   [1:0] tmp_136_reg_4695;
reg   [1:0] tmp_137_reg_4701;
reg   [1:0] tmp_138_reg_4707;
reg   [1:0] tmp_139_reg_4713;
wire   [1:0] trunc_ln9_2_fu_2387_p1;
reg   [1:0] trunc_ln9_2_reg_4719;
reg   [1:0] tmp_140_reg_4725;
reg   [1:0] tmp_141_reg_4730;
reg   [1:0] tmp_142_reg_4736;
reg   [1:0] tmp_143_reg_4742;
reg   [1:0] tmp_144_reg_4748;
reg   [1:0] tmp_145_reg_4754;
reg   [1:0] tmp_146_reg_4760;
reg   [1:0] tmp_147_reg_4766;
reg   [1:0] tmp_184_reg_4772;
reg   [1:0] tmp_185_reg_4777;
reg   [1:0] tmp_186_reg_4783;
reg   [1:0] tmp_187_reg_4789;
reg   [1:0] tmp_188_reg_4795;
reg   [1:0] tmp_189_reg_4801;
reg   [1:0] tmp_190_reg_4807;
wire   [1:0] trunc_ln9_3_fu_3099_p1;
reg   [1:0] trunc_ln9_3_reg_4813;
reg   [1:0] tmp_191_reg_4819;
reg   [1:0] tmp_192_reg_4824;
reg   [1:0] tmp_193_reg_4830;
reg   [1:0] tmp_194_reg_4836;
reg   [1:0] tmp_195_reg_4842;
reg   [1:0] tmp_196_reg_4848;
reg   [1:0] tmp_197_reg_4854;
reg   [1:0] tmp_198_reg_4860;
reg   [3:0] tmp_46_reg_4866;
reg   [3:0] tmp_47_reg_4872;
wire   [3:0] trunc_ln10_fu_3349_p1;
reg   [3:0] trunc_ln10_reg_4879;
reg   [3:0] tmp_48_reg_4885;
reg   [3:0] tmp_97_reg_4890;
reg   [3:0] tmp_98_reg_4896;
wire   [3:0] trunc_ln10_1_fu_3529_p1;
reg   [3:0] trunc_ln10_1_reg_4903;
reg   [3:0] tmp_99_reg_4909;
reg   [3:0] tmp_149_reg_4914;
reg   [3:0] tmp_150_reg_4920;
wire   [3:0] trunc_ln11_fu_3709_p1;
reg   [3:0] trunc_ln11_reg_4927;
reg   [3:0] tmp_151_reg_4933;
reg   [3:0] tmp_200_reg_4938;
reg   [3:0] tmp_201_reg_4944;
wire   [3:0] trunc_ln11_1_fu_3889_p1;
reg   [3:0] trunc_ln11_1_reg_4951;
reg   [3:0] tmp_202_reg_4957;
wire   [5:0] s4_fu_3965_p2;
reg   [5:0] s4_reg_4962;
wire   [5:0] s4_1_fu_4033_p2;
reg   [5:0] s4_1_reg_4967;
wire   [5:0] s4_2_fu_4101_p2;
reg   [5:0] s4_2_reg_4972;
wire   [5:0] s4_3_fu_4169_p2;
reg   [5:0] s4_3_reg_4977;
wire   [63:0] zext_ln34_fu_268_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln45_fu_292_p1;
reg   [3:0] n21_fu_146;
wire   [3:0] n_fu_298_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_n21_load;
reg   [8:0] output_13_fu_150;
wire   [8:0] add_ln60_3_fu_4229_p2;
reg   [8:0] ap_sig_allocacmp_output_13_load;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [8:0] output_12_fu_154;
wire   [8:0] add_ln60_1_fu_4199_p2;
reg   [8:0] ap_sig_allocacmp_output_12_load;
reg   [8:0] output_11_fu_158;
reg   [8:0] ap_sig_allocacmp_output_11_load;
reg   [8:0] output_10_fu_162;
reg   [8:0] ap_sig_allocacmp_output_10_load;
reg   [8:0] output_9_fu_166;
reg   [8:0] ap_sig_allocacmp_output_9_load;
reg   [8:0] output_8_fu_170;
reg   [8:0] ap_sig_allocacmp_output_8_load;
reg   [8:0] output_7_fu_174;
reg   [8:0] ap_sig_allocacmp_output_7_load;
reg   [8:0] output_6_fu_178;
reg   [8:0] ap_sig_allocacmp_output_6_load;
reg   [8:0] output_5_fu_182;
reg   [8:0] ap_sig_allocacmp_output_5_load;
reg   [8:0] output_fu_186;
reg   [8:0] ap_sig_allocacmp_output_load;
reg    p_ZL9golden_w3_0_ce1_local;
reg    p_ZL9golden_w3_0_ce0_local;
reg    p_ZL9golden_w3_1_ce1_local;
reg    p_ZL9golden_w3_1_ce0_local;
wire   [2:0] tmp_101_fu_274_p4;
wire   [3:0] or_ln_fu_284_p3;
wire   [31:0] xor_ln18_fu_315_p2;
wire   [30:0] trunc_ln18_2_fu_325_p1;
wire   [30:0] xor_ln18_1_fu_320_p2;
wire   [30:0] xor_ln46_fu_335_p2;
wire   [0:0] tmp_fu_341_p3;
wire   [0:0] tmp_1_fu_349_p3;
wire   [0:0] tmp_2_fu_357_p3;
wire   [0:0] tmp_3_fu_365_p3;
wire   [0:0] tmp_4_fu_373_p3;
wire   [0:0] tmp_5_fu_381_p3;
wire   [0:0] tmp_6_fu_389_p3;
wire   [0:0] tmp_7_fu_397_p3;
wire   [0:0] tmp_8_fu_405_p3;
wire   [0:0] tmp_9_fu_413_p3;
wire   [0:0] tmp_10_fu_421_p3;
wire   [0:0] tmp_11_fu_429_p3;
wire   [0:0] tmp_12_fu_437_p3;
wire   [0:0] tmp_13_fu_445_p3;
wire   [0:0] tmp_14_fu_453_p3;
wire   [0:0] trunc_ln8_fu_461_p1;
wire   [28:0] and_ln8_cast1_fu_531_p30;
wire   [30:0] and_ln8_fu_465_p32;
wire   [31:0] xnr_fu_329_p2;
wire   [0:0] tmp_15_fu_601_p3;
wire   [0:0] tmp_16_fu_609_p3;
wire   [0:0] tmp_17_fu_617_p3;
wire   [0:0] tmp_18_fu_625_p3;
wire   [0:0] tmp_19_fu_633_p3;
wire   [0:0] tmp_20_fu_641_p3;
wire   [0:0] tmp_21_fu_649_p3;
wire   [0:0] tmp_22_fu_657_p3;
wire   [0:0] tmp_23_fu_665_p3;
wire   [0:0] tmp_24_fu_673_p3;
wire   [0:0] tmp_25_fu_681_p3;
wire   [0:0] tmp_26_fu_689_p3;
wire   [0:0] tmp_27_fu_697_p3;
wire   [0:0] tmp_28_fu_705_p3;
wire   [0:0] tmp_29_fu_713_p3;
wire   [0:0] tmp_30_fu_721_p3;
wire   [28:0] and_ln8_1_cast1_fu_795_p30;
wire   [30:0] and_ln8_1_fu_729_p32;
wire   [29:0] zext_ln8_9_fu_857_p1;
wire   [29:0] zext_ln8_8_fu_593_p1;
wire   [31:0] zext_ln8_1_fu_861_p1;
wire   [31:0] zext_ln8_fu_597_p1;
wire   [29:0] add_ln8_fu_871_p2;
wire   [28:0] add_ln8_1_fu_865_p2;
wire   [31:0] s0_fu_877_p2;
wire   [31:0] xor_ln18_2_fu_1037_p2;
wire   [30:0] trunc_ln18_3_fu_1047_p1;
wire   [30:0] xor_ln18_4_fu_1042_p2;
wire   [30:0] xor_ln46_1_fu_1057_p2;
wire   [0:0] tmp_50_fu_1063_p3;
wire   [0:0] tmp_51_fu_1071_p3;
wire   [0:0] tmp_52_fu_1079_p3;
wire   [0:0] tmp_53_fu_1087_p3;
wire   [0:0] tmp_54_fu_1095_p3;
wire   [0:0] tmp_55_fu_1103_p3;
wire   [0:0] tmp_56_fu_1111_p3;
wire   [0:0] tmp_57_fu_1119_p3;
wire   [0:0] tmp_58_fu_1127_p3;
wire   [0:0] tmp_59_fu_1135_p3;
wire   [0:0] tmp_60_fu_1143_p3;
wire   [0:0] tmp_61_fu_1151_p3;
wire   [0:0] tmp_62_fu_1159_p3;
wire   [0:0] tmp_63_fu_1167_p3;
wire   [0:0] tmp_64_fu_1175_p3;
wire   [0:0] trunc_ln8_1_fu_1183_p1;
wire   [28:0] and_ln8_2_cast1_fu_1253_p30;
wire   [30:0] and_ln8_2_fu_1187_p32;
wire   [31:0] xnr_1_fu_1051_p2;
wire   [0:0] tmp_65_fu_1323_p3;
wire   [0:0] tmp_66_fu_1331_p3;
wire   [0:0] tmp_67_fu_1339_p3;
wire   [0:0] tmp_68_fu_1347_p3;
wire   [0:0] tmp_69_fu_1355_p3;
wire   [0:0] tmp_70_fu_1363_p3;
wire   [0:0] tmp_71_fu_1371_p3;
wire   [0:0] tmp_72_fu_1379_p3;
wire   [0:0] tmp_73_fu_1387_p3;
wire   [0:0] tmp_74_fu_1395_p3;
wire   [0:0] tmp_75_fu_1403_p3;
wire   [0:0] tmp_76_fu_1411_p3;
wire   [0:0] tmp_77_fu_1419_p3;
wire   [0:0] tmp_78_fu_1427_p3;
wire   [0:0] tmp_79_fu_1435_p3;
wire   [0:0] tmp_80_fu_1443_p3;
wire   [28:0] and_ln8_3_cast1_fu_1517_p30;
wire   [30:0] and_ln8_3_fu_1451_p32;
wire   [29:0] zext_ln8_11_fu_1579_p1;
wire   [29:0] zext_ln8_10_fu_1315_p1;
wire   [31:0] zext_ln8_3_fu_1583_p1;
wire   [31:0] zext_ln8_2_fu_1319_p1;
wire   [29:0] add_ln8_4_fu_1593_p2;
wire   [28:0] add_ln8_3_fu_1587_p2;
wire   [31:0] s0_1_fu_1599_p2;
wire   [30:0] trunc_ln18_4_fu_1759_p1;
wire   [30:0] xor_ln8_fu_1769_p2;
wire   [0:0] tmp_102_fu_1775_p3;
wire   [0:0] tmp_103_fu_1783_p3;
wire   [0:0] tmp_104_fu_1791_p3;
wire   [0:0] tmp_105_fu_1799_p3;
wire   [0:0] tmp_106_fu_1807_p3;
wire   [0:0] tmp_107_fu_1815_p3;
wire   [0:0] tmp_108_fu_1823_p3;
wire   [0:0] tmp_109_fu_1831_p3;
wire   [0:0] tmp_110_fu_1839_p3;
wire   [0:0] tmp_111_fu_1847_p3;
wire   [0:0] tmp_112_fu_1855_p3;
wire   [0:0] tmp_113_fu_1863_p3;
wire   [0:0] tmp_114_fu_1871_p3;
wire   [0:0] tmp_115_fu_1879_p3;
wire   [0:0] tmp_116_fu_1887_p3;
wire   [0:0] trunc_ln8_2_fu_1895_p1;
wire   [28:0] and_ln8_4_cast1_fu_1965_p30;
wire   [30:0] and_ln8_4_fu_1899_p32;
wire   [31:0] xnr_2_fu_1763_p2;
wire   [0:0] tmp_117_fu_2035_p3;
wire   [0:0] tmp_118_fu_2043_p3;
wire   [0:0] tmp_119_fu_2051_p3;
wire   [0:0] tmp_120_fu_2059_p3;
wire   [0:0] tmp_121_fu_2067_p3;
wire   [0:0] tmp_122_fu_2075_p3;
wire   [0:0] tmp_123_fu_2083_p3;
wire   [0:0] tmp_124_fu_2091_p3;
wire   [0:0] tmp_125_fu_2099_p3;
wire   [0:0] tmp_126_fu_2107_p3;
wire   [0:0] tmp_127_fu_2115_p3;
wire   [0:0] tmp_128_fu_2123_p3;
wire   [0:0] tmp_129_fu_2131_p3;
wire   [0:0] tmp_130_fu_2139_p3;
wire   [0:0] tmp_131_fu_2147_p3;
wire   [0:0] tmp_132_fu_2155_p3;
wire   [28:0] and_ln8_5_cast1_fu_2229_p30;
wire   [30:0] and_ln8_5_fu_2163_p32;
wire   [29:0] zext_ln8_13_fu_2291_p1;
wire   [29:0] zext_ln8_12_fu_2027_p1;
wire   [31:0] zext_ln8_5_fu_2295_p1;
wire   [31:0] zext_ln8_4_fu_2031_p1;
wire   [29:0] add_ln8_7_fu_2305_p2;
wire   [28:0] add_ln8_6_fu_2299_p2;
wire   [31:0] s0_2_fu_2311_p2;
wire   [30:0] trunc_ln18_5_fu_2471_p1;
wire   [30:0] xor_ln8_1_fu_2481_p2;
wire   [0:0] tmp_153_fu_2487_p3;
wire   [0:0] tmp_154_fu_2495_p3;
wire   [0:0] tmp_155_fu_2503_p3;
wire   [0:0] tmp_156_fu_2511_p3;
wire   [0:0] tmp_157_fu_2519_p3;
wire   [0:0] tmp_158_fu_2527_p3;
wire   [0:0] tmp_159_fu_2535_p3;
wire   [0:0] tmp_160_fu_2543_p3;
wire   [0:0] tmp_161_fu_2551_p3;
wire   [0:0] tmp_162_fu_2559_p3;
wire   [0:0] tmp_163_fu_2567_p3;
wire   [0:0] tmp_164_fu_2575_p3;
wire   [0:0] tmp_165_fu_2583_p3;
wire   [0:0] tmp_166_fu_2591_p3;
wire   [0:0] tmp_167_fu_2599_p3;
wire   [0:0] trunc_ln8_3_fu_2607_p1;
wire   [28:0] and_ln8_6_cast1_fu_2677_p30;
wire   [30:0] and_ln8_6_fu_2611_p32;
wire   [31:0] xnr_3_fu_2475_p2;
wire   [0:0] tmp_168_fu_2747_p3;
wire   [0:0] tmp_169_fu_2755_p3;
wire   [0:0] tmp_170_fu_2763_p3;
wire   [0:0] tmp_171_fu_2771_p3;
wire   [0:0] tmp_172_fu_2779_p3;
wire   [0:0] tmp_173_fu_2787_p3;
wire   [0:0] tmp_174_fu_2795_p3;
wire   [0:0] tmp_175_fu_2803_p3;
wire   [0:0] tmp_176_fu_2811_p3;
wire   [0:0] tmp_177_fu_2819_p3;
wire   [0:0] tmp_178_fu_2827_p3;
wire   [0:0] tmp_179_fu_2835_p3;
wire   [0:0] tmp_180_fu_2843_p3;
wire   [0:0] tmp_181_fu_2851_p3;
wire   [0:0] tmp_182_fu_2859_p3;
wire   [0:0] tmp_183_fu_2867_p3;
wire   [28:0] and_ln8_7_cast1_fu_2941_p30;
wire   [30:0] and_ln8_7_fu_2875_p32;
wire   [29:0] zext_ln8_15_fu_3003_p1;
wire   [29:0] zext_ln8_14_fu_2739_p1;
wire   [31:0] zext_ln8_7_fu_3007_p1;
wire   [31:0] zext_ln8_6_fu_2743_p1;
wire   [29:0] add_ln8_10_fu_3017_p2;
wire   [28:0] add_ln8_9_fu_3011_p2;
wire   [31:0] s0_3_fu_3023_p2;
wire   [25:0] and_ln9_cast1_fu_3209_p14;
wire   [29:0] and_ln9_fu_3183_p16;
wire   [25:0] and_ln9_1_cast1_fu_3266_p14;
wire   [29:0] and_ln9_1_fu_3240_p16;
wire   [27:0] zext_ln9_9_fu_3289_p1;
wire   [27:0] zext_ln9_8_fu_3232_p1;
wire   [30:0] zext_ln9_1_fu_3293_p1;
wire   [30:0] zext_ln9_fu_3236_p1;
wire   [30:0] s1_fu_3303_p2;
wire   [26:0] tmp_45_fu_3309_p4;
wire   [27:0] zext_ln10_fu_3319_p1;
wire   [27:0] add_ln9_fu_3297_p2;
wire   [27:0] add_ln10_fu_3323_p2;
wire   [25:0] and_ln9_2_cast1_fu_3389_p14;
wire   [29:0] and_ln9_2_fu_3363_p16;
wire   [25:0] and_ln9_3_cast1_fu_3446_p14;
wire   [29:0] and_ln9_3_fu_3420_p16;
wire   [27:0] zext_ln9_11_fu_3469_p1;
wire   [27:0] zext_ln9_10_fu_3412_p1;
wire   [30:0] zext_ln9_3_fu_3473_p1;
wire   [30:0] zext_ln9_2_fu_3416_p1;
wire   [30:0] s1_1_fu_3483_p2;
wire   [26:0] tmp_96_fu_3489_p4;
wire   [27:0] zext_ln10_1_fu_3499_p1;
wire   [27:0] add_ln9_2_fu_3477_p2;
wire   [27:0] add_ln10_1_fu_3503_p2;
wire   [25:0] and_ln9_4_cast1_fu_3569_p14;
wire   [29:0] and_ln9_4_fu_3543_p16;
wire   [25:0] and_ln9_5_cast1_fu_3626_p14;
wire   [29:0] and_ln9_5_fu_3600_p16;
wire   [27:0] zext_ln9_13_fu_3649_p1;
wire   [27:0] zext_ln9_12_fu_3592_p1;
wire   [30:0] zext_ln9_5_fu_3653_p1;
wire   [30:0] zext_ln9_4_fu_3596_p1;
wire   [30:0] s1_2_fu_3663_p2;
wire   [26:0] tmp_148_fu_3669_p4;
wire   [27:0] zext_ln10_2_fu_3679_p1;
wire   [27:0] add_ln10_4_fu_3657_p2;
wire   [27:0] add_ln10_2_fu_3683_p2;
wire   [25:0] and_ln9_6_cast1_fu_3749_p14;
wire   [29:0] and_ln9_6_fu_3723_p16;
wire   [25:0] and_ln9_7_cast1_fu_3806_p14;
wire   [29:0] and_ln9_7_fu_3780_p16;
wire   [27:0] zext_ln9_15_fu_3829_p1;
wire   [27:0] zext_ln9_14_fu_3772_p1;
wire   [30:0] zext_ln9_7_fu_3833_p1;
wire   [30:0] zext_ln9_6_fu_3776_p1;
wire   [30:0] s1_3_fu_3843_p2;
wire   [26:0] tmp_199_fu_3849_p4;
wire   [27:0] zext_ln10_3_fu_3859_p1;
wire   [27:0] add_ln10_5_fu_3837_p2;
wire   [27:0] add_ln10_3_fu_3863_p2;
wire   [19:0] and_ln_fu_3903_p6;
wire   [19:0] and_ln1_fu_3921_p6;
wire   [5:0] zext_ln11_9_fu_3932_p1;
wire   [5:0] zext_ln11_8_fu_3914_p1;
wire   [20:0] zext_ln11_1_fu_3935_p1;
wire   [20:0] zext_ln11_fu_3917_p1;
wire   [20:0] s3_fu_3945_p2;
wire   [4:0] tmp_49_fu_3951_p4;
wire   [5:0] zext_ln12_fu_3961_p1;
wire   [5:0] add_ln11_fu_3939_p2;
wire   [19:0] and_ln10_1_fu_3971_p6;
wire   [19:0] and_ln11_1_fu_3989_p6;
wire   [5:0] zext_ln11_11_fu_4000_p1;
wire   [5:0] zext_ln11_10_fu_3982_p1;
wire   [20:0] zext_ln11_3_fu_4003_p1;
wire   [20:0] zext_ln11_2_fu_3985_p1;
wire   [20:0] s3_1_fu_4013_p2;
wire   [4:0] tmp_100_fu_4019_p4;
wire   [5:0] zext_ln12_1_fu_4029_p1;
wire   [5:0] add_ln11_2_fu_4007_p2;
wire   [19:0] and_ln11_2_fu_4039_p6;
wire   [19:0] and_ln11_3_fu_4057_p6;
wire   [5:0] zext_ln11_13_fu_4068_p1;
wire   [5:0] zext_ln11_12_fu_4050_p1;
wire   [20:0] zext_ln11_5_fu_4071_p1;
wire   [20:0] zext_ln11_4_fu_4053_p1;
wire   [20:0] s3_2_fu_4081_p2;
wire   [4:0] tmp_152_fu_4087_p4;
wire   [5:0] zext_ln12_2_fu_4097_p1;
wire   [5:0] add_ln12_fu_4075_p2;
wire   [19:0] and_ln11_4_fu_4107_p6;
wire   [19:0] and_ln11_5_fu_4125_p6;
wire   [5:0] zext_ln11_15_fu_4136_p1;
wire   [5:0] zext_ln11_14_fu_4118_p1;
wire   [20:0] zext_ln11_7_fu_4139_p1;
wire   [20:0] zext_ln11_6_fu_4121_p1;
wire   [20:0] s3_3_fu_4149_p2;
wire   [4:0] tmp_203_fu_4155_p4;
wire   [5:0] zext_ln12_3_fu_4165_p1;
wire   [5:0] add_ln12_2_fu_4143_p2;
wire   [6:0] zext_ln60_fu_4178_p1;
wire   [6:0] zext_ln56_fu_4175_p1;
wire   [6:0] add_ln60_fu_4181_p2;
wire   [7:0] shl_ln_fu_4187_p3;
wire   [8:0] zext_ln60_1_fu_4195_p1;
wire   [6:0] zext_ln60_2_fu_4208_p1;
wire   [6:0] zext_ln56_1_fu_4205_p1;
wire   [6:0] add_ln60_2_fu_4211_p2;
wire   [7:0] shl_ln60_1_fu_4217_p3;
wire   [8:0] zext_ln60_3_fu_4225_p1;
reg   [8:0] ap_return_0_preg;
reg   [8:0] ap_return_1_preg;
reg   [8:0] ap_return_2_preg;
reg   [8:0] ap_return_3_preg;
reg   [8:0] ap_return_4_preg;
reg   [8:0] ap_return_5_preg;
reg   [8:0] ap_return_6_preg;
reg   [8:0] ap_return_7_preg;
reg   [8:0] ap_return_8_preg;
reg   [8:0] ap_return_9_preg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_357;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 n21_fu_146 = 4'd0;
#0 output_13_fu_150 = 9'd0;
#0 output_12_fu_154 = 9'd0;
#0 output_11_fu_158 = 9'd0;
#0 output_10_fu_162 = 9'd0;
#0 output_9_fu_166 = 9'd0;
#0 output_8_fu_170 = 9'd0;
#0 output_7_fu_174 = 9'd0;
#0 output_6_fu_178 = 9'd0;
#0 output_5_fu_182 = 9'd0;
#0 output_fu_186 = 9'd0;
#0 ap_return_0_preg = 9'd0;
#0 ap_return_1_preg = 9'd0;
#0 ap_return_2_preg = 9'd0;
#0 ap_return_3_preg = 9'd0;
#0 ap_return_4_preg = 9'd0;
#0 ap_return_5_preg = 9'd0;
#0 ap_return_6_preg = 9'd0;
#0 ap_return_7_preg = 9'd0;
#0 ap_return_8_preg = 9'd0;
#0 ap_return_9_preg = 9'd0;
end

bnn_dense_layer_3_p_ZL9golden_w3_0_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
p_ZL9golden_w3_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL9golden_w3_0_address0),
    .ce0(p_ZL9golden_w3_0_ce0_local),
    .q0(p_ZL9golden_w3_0_q0),
    .address1(p_ZL9golden_w3_0_address1),
    .ce1(p_ZL9golden_w3_0_ce1_local),
    .q1(p_ZL9golden_w3_0_q1)
);

bnn_dense_layer_3_p_ZL9golden_w3_1_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
p_ZL9golden_w3_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL9golden_w3_1_address0),
    .ce0(p_ZL9golden_w3_1_ce0_local),
    .q0(p_ZL9golden_w3_1_q0),
    .address1(p_ZL9golden_w3_1_address1),
    .ce1(p_ZL9golden_w3_1_ce1_local),
    .q1(p_ZL9golden_w3_1_q1)
);

bnn_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_0_preg[1] <= 1'b0;
        ap_return_0_preg[2] <= 1'b0;
        ap_return_0_preg[3] <= 1'b0;
        ap_return_0_preg[4] <= 1'b0;
        ap_return_0_preg[5] <= 1'b0;
        ap_return_0_preg[6] <= 1'b0;
        ap_return_0_preg[7] <= 1'b0;
        ap_return_0_preg[8] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
                        ap_return_0_preg[8 : 1] <= ap_sig_allocacmp_output_load[8 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_1_preg[1] <= 1'b0;
        ap_return_1_preg[2] <= 1'b0;
        ap_return_1_preg[3] <= 1'b0;
        ap_return_1_preg[4] <= 1'b0;
        ap_return_1_preg[5] <= 1'b0;
        ap_return_1_preg[6] <= 1'b0;
        ap_return_1_preg[7] <= 1'b0;
        ap_return_1_preg[8] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
                        ap_return_1_preg[8 : 1] <= ap_sig_allocacmp_output_5_load[8 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_2_preg[1] <= 1'b0;
        ap_return_2_preg[2] <= 1'b0;
        ap_return_2_preg[3] <= 1'b0;
        ap_return_2_preg[4] <= 1'b0;
        ap_return_2_preg[5] <= 1'b0;
        ap_return_2_preg[6] <= 1'b0;
        ap_return_2_preg[7] <= 1'b0;
        ap_return_2_preg[8] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
                        ap_return_2_preg[8 : 1] <= ap_sig_allocacmp_output_6_load[8 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_3_preg[1] <= 1'b0;
        ap_return_3_preg[2] <= 1'b0;
        ap_return_3_preg[3] <= 1'b0;
        ap_return_3_preg[4] <= 1'b0;
        ap_return_3_preg[5] <= 1'b0;
        ap_return_3_preg[6] <= 1'b0;
        ap_return_3_preg[7] <= 1'b0;
        ap_return_3_preg[8] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
                        ap_return_3_preg[8 : 1] <= ap_sig_allocacmp_output_7_load[8 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_4_preg[1] <= 1'b0;
        ap_return_4_preg[2] <= 1'b0;
        ap_return_4_preg[3] <= 1'b0;
        ap_return_4_preg[4] <= 1'b0;
        ap_return_4_preg[5] <= 1'b0;
        ap_return_4_preg[6] <= 1'b0;
        ap_return_4_preg[7] <= 1'b0;
        ap_return_4_preg[8] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
                        ap_return_4_preg[8 : 1] <= ap_sig_allocacmp_output_8_load[8 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_5_preg[1] <= 1'b0;
        ap_return_5_preg[2] <= 1'b0;
        ap_return_5_preg[3] <= 1'b0;
        ap_return_5_preg[4] <= 1'b0;
        ap_return_5_preg[5] <= 1'b0;
        ap_return_5_preg[6] <= 1'b0;
        ap_return_5_preg[7] <= 1'b0;
        ap_return_5_preg[8] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
                        ap_return_5_preg[8 : 1] <= ap_sig_allocacmp_output_9_load[8 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_6_preg[1] <= 1'b0;
        ap_return_6_preg[2] <= 1'b0;
        ap_return_6_preg[3] <= 1'b0;
        ap_return_6_preg[4] <= 1'b0;
        ap_return_6_preg[5] <= 1'b0;
        ap_return_6_preg[6] <= 1'b0;
        ap_return_6_preg[7] <= 1'b0;
        ap_return_6_preg[8] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
                        ap_return_6_preg[8 : 1] <= ap_sig_allocacmp_output_10_load[8 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_7_preg[1] <= 1'b0;
        ap_return_7_preg[2] <= 1'b0;
        ap_return_7_preg[3] <= 1'b0;
        ap_return_7_preg[4] <= 1'b0;
        ap_return_7_preg[5] <= 1'b0;
        ap_return_7_preg[6] <= 1'b0;
        ap_return_7_preg[7] <= 1'b0;
        ap_return_7_preg[8] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
                        ap_return_7_preg[8 : 1] <= ap_sig_allocacmp_output_11_load[8 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_8_preg[1] <= 1'b0;
        ap_return_8_preg[2] <= 1'b0;
        ap_return_8_preg[3] <= 1'b0;
        ap_return_8_preg[4] <= 1'b0;
        ap_return_8_preg[5] <= 1'b0;
        ap_return_8_preg[6] <= 1'b0;
        ap_return_8_preg[7] <= 1'b0;
        ap_return_8_preg[8] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
                        ap_return_8_preg[8 : 1] <= ap_sig_allocacmp_output_12_load[8 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_9_preg[1] <= 1'b0;
        ap_return_9_preg[2] <= 1'b0;
        ap_return_9_preg[3] <= 1'b0;
        ap_return_9_preg[4] <= 1'b0;
        ap_return_9_preg[5] <= 1'b0;
        ap_return_9_preg[6] <= 1'b0;
        ap_return_9_preg[7] <= 1'b0;
        ap_return_9_preg[8] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
                        ap_return_9_preg[8 : 1] <= ap_sig_allocacmp_output_13_load[8 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_357)) begin
        n21_fu_146 <= n_fu_298_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        n21_load_reg_4462 <= ap_sig_allocacmp_n21_load;
        n21_load_reg_4462_pp0_iter1_reg <= n21_load_reg_4462;
        p_read1121_reg_4382 <= p_read1;
        p_read120_reg_4387 <= p_read;
        tmp_133_reg_4678 <= {{add_ln8_7_fu_2305_p2[29:28]}};
        tmp_134_reg_4683 <= {{add_ln8_6_fu_2299_p2[25:24]}};
        tmp_135_reg_4689 <= {{add_ln8_6_fu_2299_p2[21:20]}};
        tmp_136_reg_4695 <= {{add_ln8_6_fu_2299_p2[17:16]}};
        tmp_137_reg_4701 <= {{add_ln8_6_fu_2299_p2[13:12]}};
        tmp_138_reg_4707 <= {{add_ln8_6_fu_2299_p2[9:8]}};
        tmp_139_reg_4713 <= {{add_ln8_6_fu_2299_p2[5:4]}};
        tmp_140_reg_4725 <= {{s0_2_fu_2311_p2[31:30]}};
        tmp_141_reg_4730 <= {{add_ln8_6_fu_2299_p2[27:26]}};
        tmp_142_reg_4736 <= {{add_ln8_6_fu_2299_p2[23:22]}};
        tmp_143_reg_4742 <= {{add_ln8_6_fu_2299_p2[19:18]}};
        tmp_144_reg_4748 <= {{add_ln8_6_fu_2299_p2[15:14]}};
        tmp_145_reg_4754 <= {{add_ln8_6_fu_2299_p2[11:10]}};
        tmp_146_reg_4760 <= {{add_ln8_6_fu_2299_p2[7:6]}};
        tmp_147_reg_4766 <= {{add_ln8_6_fu_2299_p2[3:2]}};
        tmp_184_reg_4772 <= {{add_ln8_10_fu_3017_p2[29:28]}};
        tmp_185_reg_4777 <= {{add_ln8_9_fu_3011_p2[25:24]}};
        tmp_186_reg_4783 <= {{add_ln8_9_fu_3011_p2[21:20]}};
        tmp_187_reg_4789 <= {{add_ln8_9_fu_3011_p2[17:16]}};
        tmp_188_reg_4795 <= {{add_ln8_9_fu_3011_p2[13:12]}};
        tmp_189_reg_4801 <= {{add_ln8_9_fu_3011_p2[9:8]}};
        tmp_190_reg_4807 <= {{add_ln8_9_fu_3011_p2[5:4]}};
        tmp_191_reg_4819 <= {{s0_3_fu_3023_p2[31:30]}};
        tmp_192_reg_4824 <= {{add_ln8_9_fu_3011_p2[27:26]}};
        tmp_193_reg_4830 <= {{add_ln8_9_fu_3011_p2[23:22]}};
        tmp_194_reg_4836 <= {{add_ln8_9_fu_3011_p2[19:18]}};
        tmp_195_reg_4842 <= {{add_ln8_9_fu_3011_p2[15:14]}};
        tmp_196_reg_4848 <= {{add_ln8_9_fu_3011_p2[11:10]}};
        tmp_197_reg_4854 <= {{add_ln8_9_fu_3011_p2[7:6]}};
        tmp_198_reg_4860 <= {{add_ln8_9_fu_3011_p2[3:2]}};
        tmp_31_reg_4495 <= {{add_ln8_1_fu_865_p2[25:24]}};
        tmp_32_reg_4501 <= {{add_ln8_1_fu_865_p2[21:20]}};
        tmp_33_reg_4507 <= {{add_ln8_1_fu_865_p2[17:16]}};
        tmp_34_reg_4513 <= {{add_ln8_1_fu_865_p2[13:12]}};
        tmp_35_reg_4519 <= {{add_ln8_1_fu_865_p2[9:8]}};
        tmp_36_reg_4525 <= {{add_ln8_1_fu_865_p2[5:4]}};
        tmp_37_reg_4537 <= {{s0_fu_877_p2[31:30]}};
        tmp_38_reg_4542 <= {{add_ln8_1_fu_865_p2[27:26]}};
        tmp_39_reg_4548 <= {{add_ln8_1_fu_865_p2[23:22]}};
        tmp_40_reg_4554 <= {{add_ln8_1_fu_865_p2[19:18]}};
        tmp_41_reg_4560 <= {{add_ln8_1_fu_865_p2[15:14]}};
        tmp_42_reg_4566 <= {{add_ln8_1_fu_865_p2[11:10]}};
        tmp_43_reg_4572 <= {{add_ln8_1_fu_865_p2[7:6]}};
        tmp_44_reg_4578 <= {{add_ln8_1_fu_865_p2[3:2]}};
        tmp_81_reg_4584 <= {{add_ln8_4_fu_1593_p2[29:28]}};
        tmp_82_reg_4589 <= {{add_ln8_3_fu_1587_p2[25:24]}};
        tmp_83_reg_4595 <= {{add_ln8_3_fu_1587_p2[21:20]}};
        tmp_84_reg_4601 <= {{add_ln8_3_fu_1587_p2[17:16]}};
        tmp_85_reg_4607 <= {{add_ln8_3_fu_1587_p2[13:12]}};
        tmp_86_reg_4613 <= {{add_ln8_3_fu_1587_p2[9:8]}};
        tmp_87_reg_4619 <= {{add_ln8_3_fu_1587_p2[5:4]}};
        tmp_88_reg_4631 <= {{s0_1_fu_1599_p2[31:30]}};
        tmp_89_reg_4636 <= {{add_ln8_3_fu_1587_p2[27:26]}};
        tmp_90_reg_4642 <= {{add_ln8_3_fu_1587_p2[23:22]}};
        tmp_91_reg_4648 <= {{add_ln8_3_fu_1587_p2[19:18]}};
        tmp_92_reg_4654 <= {{add_ln8_3_fu_1587_p2[15:14]}};
        tmp_93_reg_4660 <= {{add_ln8_3_fu_1587_p2[11:10]}};
        tmp_94_reg_4666 <= {{add_ln8_3_fu_1587_p2[7:6]}};
        tmp_95_reg_4672 <= {{add_ln8_3_fu_1587_p2[3:2]}};
        tmp_s_reg_4490 <= {{add_ln8_fu_871_p2[29:28]}};
        trunc_ln18_1_reg_4457 <= trunc_ln18_1_fu_256_p1;
        trunc_ln18_reg_4452 <= trunc_ln18_fu_252_p1;
        trunc_ln9_1_reg_4625 <= trunc_ln9_1_fu_1675_p1;
        trunc_ln9_2_reg_4719 <= trunc_ln9_2_fu_2387_p1;
        trunc_ln9_3_reg_4813 <= trunc_ln9_3_fu_3099_p1;
        trunc_ln9_reg_4531 <= trunc_ln9_fu_953_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        n21_load_reg_4462_pp0_iter2_reg <= n21_load_reg_4462_pp0_iter1_reg;
        n21_load_reg_4462_pp0_iter3_reg <= n21_load_reg_4462_pp0_iter2_reg;
        s4_1_reg_4967 <= s4_1_fu_4033_p2;
        s4_2_reg_4972 <= s4_2_fu_4101_p2;
        s4_3_reg_4977 <= s4_3_fu_4169_p2;
        s4_reg_4962 <= s4_fu_3965_p2;
        tmp_149_reg_4914 <= {{add_ln10_2_fu_3683_p2[19:16]}};
        tmp_150_reg_4920 <= {{add_ln10_2_fu_3683_p2[11:8]}};
        tmp_151_reg_4933 <= {{add_ln10_2_fu_3683_p2[27:24]}};
        tmp_200_reg_4938 <= {{add_ln10_3_fu_3863_p2[19:16]}};
        tmp_201_reg_4944 <= {{add_ln10_3_fu_3863_p2[11:8]}};
        tmp_202_reg_4957 <= {{add_ln10_3_fu_3863_p2[27:24]}};
        tmp_46_reg_4866 <= {{add_ln10_fu_3323_p2[19:16]}};
        tmp_47_reg_4872 <= {{add_ln10_fu_3323_p2[11:8]}};
        tmp_48_reg_4885 <= {{add_ln10_fu_3323_p2[27:24]}};
        tmp_97_reg_4890 <= {{add_ln10_1_fu_3503_p2[19:16]}};
        tmp_98_reg_4896 <= {{add_ln10_1_fu_3503_p2[11:8]}};
        tmp_99_reg_4909 <= {{add_ln10_1_fu_3503_p2[27:24]}};
        trunc_ln10_1_reg_4903 <= trunc_ln10_1_fu_3529_p1;
        trunc_ln10_reg_4879 <= trunc_ln10_fu_3349_p1;
        trunc_ln11_1_reg_4951 <= trunc_ln11_1_fu_3889_p1;
        trunc_ln11_reg_4927 <= trunc_ln11_fu_3709_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (n21_load_reg_4462_pp0_iter3_reg == 4'd6))) begin
        output_10_fu_162[8 : 1] <= add_ln60_1_fu_4199_p2[8 : 1];
        output_11_fu_158[8 : 1] <= add_ln60_3_fu_4229_p2[8 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((~(n21_load_reg_4462_pp0_iter3_reg == 4'd6) & ~(n21_load_reg_4462_pp0_iter3_reg == 4'd4) & ~(n21_load_reg_4462_pp0_iter3_reg == 4'd2) & ~(n21_load_reg_4462_pp0_iter3_reg == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        output_12_fu_154[8 : 1] <= add_ln60_1_fu_4199_p2[8 : 1];
        output_13_fu_150[8 : 1] <= add_ln60_3_fu_4229_p2[8 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (n21_load_reg_4462_pp0_iter3_reg == 4'd0))) begin
        output_5_fu_182[8 : 1] <= add_ln60_3_fu_4229_p2[8 : 1];
        output_fu_186[8 : 1] <= add_ln60_1_fu_4199_p2[8 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (n21_load_reg_4462_pp0_iter3_reg == 4'd2))) begin
        output_6_fu_178[8 : 1] <= add_ln60_1_fu_4199_p2[8 : 1];
        output_7_fu_174[8 : 1] <= add_ln60_3_fu_4229_p2[8 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (n21_load_reg_4462_pp0_iter3_reg == 4'd4))) begin
        output_8_fu_170[8 : 1] <= add_ln60_1_fu_4199_p2[8 : 1];
        output_9_fu_166[8 : 1] <= add_ln60_3_fu_4229_p2[8 : 1];
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_304_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_return_0 = ap_sig_allocacmp_output_load;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_return_1 = ap_sig_allocacmp_output_5_load;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_return_2 = ap_sig_allocacmp_output_6_load;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_return_3 = ap_sig_allocacmp_output_7_load;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_return_4 = ap_sig_allocacmp_output_8_load;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_return_5 = ap_sig_allocacmp_output_9_load;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_return_6 = ap_sig_allocacmp_output_10_load;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_return_7 = ap_sig_allocacmp_output_11_load;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_return_8 = ap_sig_allocacmp_output_12_load;
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_return_9 = ap_sig_allocacmp_output_13_load;
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_n21_load = 4'd0;
    end else begin
        ap_sig_allocacmp_n21_load = n21_fu_146;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (n21_load_reg_4462_pp0_iter3_reg == 4'd6))) begin
        ap_sig_allocacmp_output_10_load = add_ln60_1_fu_4199_p2;
    end else begin
        ap_sig_allocacmp_output_10_load = output_10_fu_162;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (n21_load_reg_4462_pp0_iter3_reg == 4'd6))) begin
        ap_sig_allocacmp_output_11_load = add_ln60_3_fu_4229_p2;
    end else begin
        ap_sig_allocacmp_output_11_load = output_11_fu_158;
    end
end

always @ (*) begin
    if ((~(n21_load_reg_4462_pp0_iter3_reg == 4'd6) & ~(n21_load_reg_4462_pp0_iter3_reg == 4'd4) & ~(n21_load_reg_4462_pp0_iter3_reg == 4'd2) & ~(n21_load_reg_4462_pp0_iter3_reg == 4'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_output_12_load = add_ln60_1_fu_4199_p2;
    end else begin
        ap_sig_allocacmp_output_12_load = output_12_fu_154;
    end
end

always @ (*) begin
    if ((~(n21_load_reg_4462_pp0_iter3_reg == 4'd6) & ~(n21_load_reg_4462_pp0_iter3_reg == 4'd4) & ~(n21_load_reg_4462_pp0_iter3_reg == 4'd2) & ~(n21_load_reg_4462_pp0_iter3_reg == 4'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_output_13_load = add_ln60_3_fu_4229_p2;
    end else begin
        ap_sig_allocacmp_output_13_load = output_13_fu_150;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (n21_load_reg_4462_pp0_iter3_reg == 4'd0))) begin
        ap_sig_allocacmp_output_5_load = add_ln60_3_fu_4229_p2;
    end else begin
        ap_sig_allocacmp_output_5_load = output_5_fu_182;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (n21_load_reg_4462_pp0_iter3_reg == 4'd2))) begin
        ap_sig_allocacmp_output_6_load = add_ln60_1_fu_4199_p2;
    end else begin
        ap_sig_allocacmp_output_6_load = output_6_fu_178;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (n21_load_reg_4462_pp0_iter3_reg == 4'd2))) begin
        ap_sig_allocacmp_output_7_load = add_ln60_3_fu_4229_p2;
    end else begin
        ap_sig_allocacmp_output_7_load = output_7_fu_174;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (n21_load_reg_4462_pp0_iter3_reg == 4'd4))) begin
        ap_sig_allocacmp_output_8_load = add_ln60_1_fu_4199_p2;
    end else begin
        ap_sig_allocacmp_output_8_load = output_8_fu_170;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (n21_load_reg_4462_pp0_iter3_reg == 4'd4))) begin
        ap_sig_allocacmp_output_9_load = add_ln60_3_fu_4229_p2;
    end else begin
        ap_sig_allocacmp_output_9_load = output_9_fu_166;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (n21_load_reg_4462_pp0_iter3_reg == 4'd0))) begin
        ap_sig_allocacmp_output_load = add_ln60_1_fu_4199_p2;
    end else begin
        ap_sig_allocacmp_output_load = output_fu_186;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL9golden_w3_0_ce0_local = 1'b1;
    end else begin
        p_ZL9golden_w3_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL9golden_w3_0_ce1_local = 1'b1;
    end else begin
        p_ZL9golden_w3_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL9golden_w3_1_ce0_local = 1'b1;
    end else begin
        p_ZL9golden_w3_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL9golden_w3_1_ce1_local = 1'b1;
    end else begin
        p_ZL9golden_w3_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_1_fu_3503_p2 = (zext_ln10_1_fu_3499_p1 + add_ln9_2_fu_3477_p2);

assign add_ln10_2_fu_3683_p2 = (zext_ln10_2_fu_3679_p1 + add_ln10_4_fu_3657_p2);

assign add_ln10_3_fu_3863_p2 = (zext_ln10_3_fu_3859_p1 + add_ln10_5_fu_3837_p2);

assign add_ln10_4_fu_3657_p2 = (zext_ln9_13_fu_3649_p1 + zext_ln9_12_fu_3592_p1);

assign add_ln10_5_fu_3837_p2 = (zext_ln9_15_fu_3829_p1 + zext_ln9_14_fu_3772_p1);

assign add_ln10_fu_3323_p2 = (zext_ln10_fu_3319_p1 + add_ln9_fu_3297_p2);

assign add_ln11_2_fu_4007_p2 = (zext_ln11_11_fu_4000_p1 + zext_ln11_10_fu_3982_p1);

assign add_ln11_fu_3939_p2 = (zext_ln11_9_fu_3932_p1 + zext_ln11_8_fu_3914_p1);

assign add_ln12_2_fu_4143_p2 = (zext_ln11_15_fu_4136_p1 + zext_ln11_14_fu_4118_p1);

assign add_ln12_fu_4075_p2 = (zext_ln11_13_fu_4068_p1 + zext_ln11_12_fu_4050_p1);

assign add_ln60_1_fu_4199_p2 = ($signed(zext_ln60_1_fu_4195_p1) + $signed(9'd448));

assign add_ln60_2_fu_4211_p2 = (zext_ln60_2_fu_4208_p1 + zext_ln56_1_fu_4205_p1);

assign add_ln60_3_fu_4229_p2 = ($signed(zext_ln60_3_fu_4225_p1) + $signed(9'd448));

assign add_ln60_fu_4181_p2 = (zext_ln60_fu_4178_p1 + zext_ln56_fu_4175_p1);

assign add_ln8_10_fu_3017_p2 = (zext_ln8_15_fu_3003_p1 + zext_ln8_14_fu_2739_p1);

assign add_ln8_1_fu_865_p2 = (and_ln8_1_cast1_fu_795_p30 + and_ln8_cast1_fu_531_p30);

assign add_ln8_3_fu_1587_p2 = (and_ln8_3_cast1_fu_1517_p30 + and_ln8_2_cast1_fu_1253_p30);

assign add_ln8_4_fu_1593_p2 = (zext_ln8_11_fu_1579_p1 + zext_ln8_10_fu_1315_p1);

assign add_ln8_6_fu_2299_p2 = (and_ln8_5_cast1_fu_2229_p30 + and_ln8_4_cast1_fu_1965_p30);

assign add_ln8_7_fu_2305_p2 = (zext_ln8_13_fu_2291_p1 + zext_ln8_12_fu_2027_p1);

assign add_ln8_9_fu_3011_p2 = (and_ln8_7_cast1_fu_2941_p30 + and_ln8_6_cast1_fu_2677_p30);

assign add_ln8_fu_871_p2 = (zext_ln8_9_fu_857_p1 + zext_ln8_8_fu_593_p1);

assign add_ln9_2_fu_3477_p2 = (zext_ln9_11_fu_3469_p1 + zext_ln9_10_fu_3412_p1);

assign add_ln9_fu_3297_p2 = (zext_ln9_9_fu_3289_p1 + zext_ln9_8_fu_3232_p1);

assign and_ln10_1_fu_3971_p6 = {{{{{tmp_97_reg_4890}, {4'd0}}, {tmp_98_reg_4896}}, {4'd0}}, {trunc_ln10_1_reg_4903}};

assign and_ln11_1_fu_3989_p6 = {{{{{tmp_99_reg_4909}, {4'd0}}, {tmp_97_reg_4890}}, {4'd0}}, {tmp_98_reg_4896}};

assign and_ln11_2_fu_4039_p6 = {{{{{tmp_149_reg_4914}, {4'd0}}, {tmp_150_reg_4920}}, {4'd0}}, {trunc_ln11_reg_4927}};

assign and_ln11_3_fu_4057_p6 = {{{{{tmp_151_reg_4933}, {4'd0}}, {tmp_149_reg_4914}}, {4'd0}}, {tmp_150_reg_4920}};

assign and_ln11_4_fu_4107_p6 = {{{{{tmp_200_reg_4938}, {4'd0}}, {tmp_201_reg_4944}}, {4'd0}}, {trunc_ln11_1_reg_4951}};

assign and_ln11_5_fu_4125_p6 = {{{{{tmp_202_reg_4957}, {4'd0}}, {tmp_200_reg_4938}}, {4'd0}}, {tmp_201_reg_4944}};

assign and_ln1_fu_3921_p6 = {{{{{tmp_48_reg_4885}, {4'd0}}, {tmp_46_reg_4866}}, {4'd0}}, {tmp_47_reg_4872}};

assign and_ln8_1_cast1_fu_795_p30 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_16_fu_609_p3}, {1'd0}}, {tmp_17_fu_617_p3}}, {1'd0}}, {tmp_18_fu_625_p3}}, {1'd0}}, {tmp_19_fu_633_p3}}, {1'd0}}, {tmp_20_fu_641_p3}}, {1'd0}}, {tmp_21_fu_649_p3}}, {1'd0}}, {tmp_22_fu_657_p3}}, {1'd0}}, {tmp_23_fu_665_p3}}, {1'd0}}, {tmp_24_fu_673_p3}}, {1'd0}}, {tmp_25_fu_681_p3}}, {1'd0}}, {tmp_26_fu_689_p3}}, {1'd0}}, {tmp_27_fu_697_p3}}, {1'd0}}, {tmp_28_fu_705_p3}}, {1'd0}}, {tmp_29_fu_713_p3}}, {1'd0}}, {tmp_30_fu_721_p3}};

assign and_ln8_1_fu_729_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_15_fu_601_p3}, {1'd0}}, {tmp_16_fu_609_p3}}, {1'd0}}, {tmp_17_fu_617_p3}}, {1'd0}}, {tmp_18_fu_625_p3}}, {1'd0}}, {tmp_19_fu_633_p3}}, {1'd0}}, {tmp_20_fu_641_p3}}, {1'd0}}, {tmp_21_fu_649_p3}}, {1'd0}}, {tmp_22_fu_657_p3}}, {1'd0}}, {tmp_23_fu_665_p3}}, {1'd0}}, {tmp_24_fu_673_p3}}, {1'd0}}, {tmp_25_fu_681_p3}}, {1'd0}}, {tmp_26_fu_689_p3}}, {1'd0}}, {tmp_27_fu_697_p3}}, {1'd0}}, {tmp_28_fu_705_p3}}, {1'd0}}, {tmp_29_fu_713_p3}}, {1'd0}}, {tmp_30_fu_721_p3}};

assign and_ln8_2_cast1_fu_1253_p30 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_51_fu_1071_p3}, {1'd0}}, {tmp_52_fu_1079_p3}}, {1'd0}}, {tmp_53_fu_1087_p3}}, {1'd0}}, {tmp_54_fu_1095_p3}}, {1'd0}}, {tmp_55_fu_1103_p3}}, {1'd0}}, {tmp_56_fu_1111_p3}}, {1'd0}}, {tmp_57_fu_1119_p3}}, {1'd0}}, {tmp_58_fu_1127_p3}}, {1'd0}}, {tmp_59_fu_1135_p3}}, {1'd0}}, {tmp_60_fu_1143_p3}}, {1'd0}}, {tmp_61_fu_1151_p3}}, {1'd0}}, {tmp_62_fu_1159_p3}}, {1'd0}}, {tmp_63_fu_1167_p3}}, {1'd0}}, {tmp_64_fu_1175_p3}}, {1'd0}}, {trunc_ln8_1_fu_1183_p1}};

assign and_ln8_2_fu_1187_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_50_fu_1063_p3}, {1'd0}}, {tmp_51_fu_1071_p3}}, {1'd0}}, {tmp_52_fu_1079_p3}}, {1'd0}}, {tmp_53_fu_1087_p3}}, {1'd0}}, {tmp_54_fu_1095_p3}}, {1'd0}}, {tmp_55_fu_1103_p3}}, {1'd0}}, {tmp_56_fu_1111_p3}}, {1'd0}}, {tmp_57_fu_1119_p3}}, {1'd0}}, {tmp_58_fu_1127_p3}}, {1'd0}}, {tmp_59_fu_1135_p3}}, {1'd0}}, {tmp_60_fu_1143_p3}}, {1'd0}}, {tmp_61_fu_1151_p3}}, {1'd0}}, {tmp_62_fu_1159_p3}}, {1'd0}}, {tmp_63_fu_1167_p3}}, {1'd0}}, {tmp_64_fu_1175_p3}}, {1'd0}}, {trunc_ln8_1_fu_1183_p1}};

assign and_ln8_3_cast1_fu_1517_p30 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_66_fu_1331_p3}, {1'd0}}, {tmp_67_fu_1339_p3}}, {1'd0}}, {tmp_68_fu_1347_p3}}, {1'd0}}, {tmp_69_fu_1355_p3}}, {1'd0}}, {tmp_70_fu_1363_p3}}, {1'd0}}, {tmp_71_fu_1371_p3}}, {1'd0}}, {tmp_72_fu_1379_p3}}, {1'd0}}, {tmp_73_fu_1387_p3}}, {1'd0}}, {tmp_74_fu_1395_p3}}, {1'd0}}, {tmp_75_fu_1403_p3}}, {1'd0}}, {tmp_76_fu_1411_p3}}, {1'd0}}, {tmp_77_fu_1419_p3}}, {1'd0}}, {tmp_78_fu_1427_p3}}, {1'd0}}, {tmp_79_fu_1435_p3}}, {1'd0}}, {tmp_80_fu_1443_p3}};

assign and_ln8_3_fu_1451_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_65_fu_1323_p3}, {1'd0}}, {tmp_66_fu_1331_p3}}, {1'd0}}, {tmp_67_fu_1339_p3}}, {1'd0}}, {tmp_68_fu_1347_p3}}, {1'd0}}, {tmp_69_fu_1355_p3}}, {1'd0}}, {tmp_70_fu_1363_p3}}, {1'd0}}, {tmp_71_fu_1371_p3}}, {1'd0}}, {tmp_72_fu_1379_p3}}, {1'd0}}, {tmp_73_fu_1387_p3}}, {1'd0}}, {tmp_74_fu_1395_p3}}, {1'd0}}, {tmp_75_fu_1403_p3}}, {1'd0}}, {tmp_76_fu_1411_p3}}, {1'd0}}, {tmp_77_fu_1419_p3}}, {1'd0}}, {tmp_78_fu_1427_p3}}, {1'd0}}, {tmp_79_fu_1435_p3}}, {1'd0}}, {tmp_80_fu_1443_p3}};

assign and_ln8_4_cast1_fu_1965_p30 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_103_fu_1783_p3}, {1'd0}}, {tmp_104_fu_1791_p3}}, {1'd0}}, {tmp_105_fu_1799_p3}}, {1'd0}}, {tmp_106_fu_1807_p3}}, {1'd0}}, {tmp_107_fu_1815_p3}}, {1'd0}}, {tmp_108_fu_1823_p3}}, {1'd0}}, {tmp_109_fu_1831_p3}}, {1'd0}}, {tmp_110_fu_1839_p3}}, {1'd0}}, {tmp_111_fu_1847_p3}}, {1'd0}}, {tmp_112_fu_1855_p3}}, {1'd0}}, {tmp_113_fu_1863_p3}}, {1'd0}}, {tmp_114_fu_1871_p3}}, {1'd0}}, {tmp_115_fu_1879_p3}}, {1'd0}}, {tmp_116_fu_1887_p3}}, {1'd0}}, {trunc_ln8_2_fu_1895_p1}};

assign and_ln8_4_fu_1899_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_102_fu_1775_p3}, {1'd0}}, {tmp_103_fu_1783_p3}}, {1'd0}}, {tmp_104_fu_1791_p3}}, {1'd0}}, {tmp_105_fu_1799_p3}}, {1'd0}}, {tmp_106_fu_1807_p3}}, {1'd0}}, {tmp_107_fu_1815_p3}}, {1'd0}}, {tmp_108_fu_1823_p3}}, {1'd0}}, {tmp_109_fu_1831_p3}}, {1'd0}}, {tmp_110_fu_1839_p3}}, {1'd0}}, {tmp_111_fu_1847_p3}}, {1'd0}}, {tmp_112_fu_1855_p3}}, {1'd0}}, {tmp_113_fu_1863_p3}}, {1'd0}}, {tmp_114_fu_1871_p3}}, {1'd0}}, {tmp_115_fu_1879_p3}}, {1'd0}}, {tmp_116_fu_1887_p3}}, {1'd0}}, {trunc_ln8_2_fu_1895_p1}};

assign and_ln8_5_cast1_fu_2229_p30 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_118_fu_2043_p3}, {1'd0}}, {tmp_119_fu_2051_p3}}, {1'd0}}, {tmp_120_fu_2059_p3}}, {1'd0}}, {tmp_121_fu_2067_p3}}, {1'd0}}, {tmp_122_fu_2075_p3}}, {1'd0}}, {tmp_123_fu_2083_p3}}, {1'd0}}, {tmp_124_fu_2091_p3}}, {1'd0}}, {tmp_125_fu_2099_p3}}, {1'd0}}, {tmp_126_fu_2107_p3}}, {1'd0}}, {tmp_127_fu_2115_p3}}, {1'd0}}, {tmp_128_fu_2123_p3}}, {1'd0}}, {tmp_129_fu_2131_p3}}, {1'd0}}, {tmp_130_fu_2139_p3}}, {1'd0}}, {tmp_131_fu_2147_p3}}, {1'd0}}, {tmp_132_fu_2155_p3}};

assign and_ln8_5_fu_2163_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_117_fu_2035_p3}, {1'd0}}, {tmp_118_fu_2043_p3}}, {1'd0}}, {tmp_119_fu_2051_p3}}, {1'd0}}, {tmp_120_fu_2059_p3}}, {1'd0}}, {tmp_121_fu_2067_p3}}, {1'd0}}, {tmp_122_fu_2075_p3}}, {1'd0}}, {tmp_123_fu_2083_p3}}, {1'd0}}, {tmp_124_fu_2091_p3}}, {1'd0}}, {tmp_125_fu_2099_p3}}, {1'd0}}, {tmp_126_fu_2107_p3}}, {1'd0}}, {tmp_127_fu_2115_p3}}, {1'd0}}, {tmp_128_fu_2123_p3}}, {1'd0}}, {tmp_129_fu_2131_p3}}, {1'd0}}, {tmp_130_fu_2139_p3}}, {1'd0}}, {tmp_131_fu_2147_p3}}, {1'd0}}, {tmp_132_fu_2155_p3}};

assign and_ln8_6_cast1_fu_2677_p30 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_154_fu_2495_p3}, {1'd0}}, {tmp_155_fu_2503_p3}}, {1'd0}}, {tmp_156_fu_2511_p3}}, {1'd0}}, {tmp_157_fu_2519_p3}}, {1'd0}}, {tmp_158_fu_2527_p3}}, {1'd0}}, {tmp_159_fu_2535_p3}}, {1'd0}}, {tmp_160_fu_2543_p3}}, {1'd0}}, {tmp_161_fu_2551_p3}}, {1'd0}}, {tmp_162_fu_2559_p3}}, {1'd0}}, {tmp_163_fu_2567_p3}}, {1'd0}}, {tmp_164_fu_2575_p3}}, {1'd0}}, {tmp_165_fu_2583_p3}}, {1'd0}}, {tmp_166_fu_2591_p3}}, {1'd0}}, {tmp_167_fu_2599_p3}}, {1'd0}}, {trunc_ln8_3_fu_2607_p1}};

assign and_ln8_6_fu_2611_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_153_fu_2487_p3}, {1'd0}}, {tmp_154_fu_2495_p3}}, {1'd0}}, {tmp_155_fu_2503_p3}}, {1'd0}}, {tmp_156_fu_2511_p3}}, {1'd0}}, {tmp_157_fu_2519_p3}}, {1'd0}}, {tmp_158_fu_2527_p3}}, {1'd0}}, {tmp_159_fu_2535_p3}}, {1'd0}}, {tmp_160_fu_2543_p3}}, {1'd0}}, {tmp_161_fu_2551_p3}}, {1'd0}}, {tmp_162_fu_2559_p3}}, {1'd0}}, {tmp_163_fu_2567_p3}}, {1'd0}}, {tmp_164_fu_2575_p3}}, {1'd0}}, {tmp_165_fu_2583_p3}}, {1'd0}}, {tmp_166_fu_2591_p3}}, {1'd0}}, {tmp_167_fu_2599_p3}}, {1'd0}}, {trunc_ln8_3_fu_2607_p1}};

assign and_ln8_7_cast1_fu_2941_p30 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_169_fu_2755_p3}, {1'd0}}, {tmp_170_fu_2763_p3}}, {1'd0}}, {tmp_171_fu_2771_p3}}, {1'd0}}, {tmp_172_fu_2779_p3}}, {1'd0}}, {tmp_173_fu_2787_p3}}, {1'd0}}, {tmp_174_fu_2795_p3}}, {1'd0}}, {tmp_175_fu_2803_p3}}, {1'd0}}, {tmp_176_fu_2811_p3}}, {1'd0}}, {tmp_177_fu_2819_p3}}, {1'd0}}, {tmp_178_fu_2827_p3}}, {1'd0}}, {tmp_179_fu_2835_p3}}, {1'd0}}, {tmp_180_fu_2843_p3}}, {1'd0}}, {tmp_181_fu_2851_p3}}, {1'd0}}, {tmp_182_fu_2859_p3}}, {1'd0}}, {tmp_183_fu_2867_p3}};

assign and_ln8_7_fu_2875_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_168_fu_2747_p3}, {1'd0}}, {tmp_169_fu_2755_p3}}, {1'd0}}, {tmp_170_fu_2763_p3}}, {1'd0}}, {tmp_171_fu_2771_p3}}, {1'd0}}, {tmp_172_fu_2779_p3}}, {1'd0}}, {tmp_173_fu_2787_p3}}, {1'd0}}, {tmp_174_fu_2795_p3}}, {1'd0}}, {tmp_175_fu_2803_p3}}, {1'd0}}, {tmp_176_fu_2811_p3}}, {1'd0}}, {tmp_177_fu_2819_p3}}, {1'd0}}, {tmp_178_fu_2827_p3}}, {1'd0}}, {tmp_179_fu_2835_p3}}, {1'd0}}, {tmp_180_fu_2843_p3}}, {1'd0}}, {tmp_181_fu_2851_p3}}, {1'd0}}, {tmp_182_fu_2859_p3}}, {1'd0}}, {tmp_183_fu_2867_p3}};

assign and_ln8_cast1_fu_531_p30 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_1_fu_349_p3}, {1'd0}}, {tmp_2_fu_357_p3}}, {1'd0}}, {tmp_3_fu_365_p3}}, {1'd0}}, {tmp_4_fu_373_p3}}, {1'd0}}, {tmp_5_fu_381_p3}}, {1'd0}}, {tmp_6_fu_389_p3}}, {1'd0}}, {tmp_7_fu_397_p3}}, {1'd0}}, {tmp_8_fu_405_p3}}, {1'd0}}, {tmp_9_fu_413_p3}}, {1'd0}}, {tmp_10_fu_421_p3}}, {1'd0}}, {tmp_11_fu_429_p3}}, {1'd0}}, {tmp_12_fu_437_p3}}, {1'd0}}, {tmp_13_fu_445_p3}}, {1'd0}}, {tmp_14_fu_453_p3}}, {1'd0}}, {trunc_ln8_fu_461_p1}};

assign and_ln8_fu_465_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_fu_341_p3}, {1'd0}}, {tmp_1_fu_349_p3}}, {1'd0}}, {tmp_2_fu_357_p3}}, {1'd0}}, {tmp_3_fu_365_p3}}, {1'd0}}, {tmp_4_fu_373_p3}}, {1'd0}}, {tmp_5_fu_381_p3}}, {1'd0}}, {tmp_6_fu_389_p3}}, {1'd0}}, {tmp_7_fu_397_p3}}, {1'd0}}, {tmp_8_fu_405_p3}}, {1'd0}}, {tmp_9_fu_413_p3}}, {1'd0}}, {tmp_10_fu_421_p3}}, {1'd0}}, {tmp_11_fu_429_p3}}, {1'd0}}, {tmp_12_fu_437_p3}}, {1'd0}}, {tmp_13_fu_445_p3}}, {1'd0}}, {tmp_14_fu_453_p3}}, {1'd0}}, {trunc_ln8_fu_461_p1}};

assign and_ln9_1_cast1_fu_3266_p14 = {{{{{{{{{{{{{tmp_38_reg_4542}, {2'd0}}, {tmp_39_reg_4548}}, {2'd0}}, {tmp_40_reg_4554}}, {2'd0}}, {tmp_41_reg_4560}}, {2'd0}}, {tmp_42_reg_4566}}, {2'd0}}, {tmp_43_reg_4572}}, {2'd0}}, {tmp_44_reg_4578}};

assign and_ln9_1_fu_3240_p16 = {{{{{{{{{{{{{{{tmp_37_reg_4537}, {2'd0}}, {tmp_38_reg_4542}}, {2'd0}}, {tmp_39_reg_4548}}, {2'd0}}, {tmp_40_reg_4554}}, {2'd0}}, {tmp_41_reg_4560}}, {2'd0}}, {tmp_42_reg_4566}}, {2'd0}}, {tmp_43_reg_4572}}, {2'd0}}, {tmp_44_reg_4578}};

assign and_ln9_2_cast1_fu_3389_p14 = {{{{{{{{{{{{{tmp_82_reg_4589}, {2'd0}}, {tmp_83_reg_4595}}, {2'd0}}, {tmp_84_reg_4601}}, {2'd0}}, {tmp_85_reg_4607}}, {2'd0}}, {tmp_86_reg_4613}}, {2'd0}}, {tmp_87_reg_4619}}, {2'd0}}, {trunc_ln9_1_reg_4625}};

assign and_ln9_2_fu_3363_p16 = {{{{{{{{{{{{{{{tmp_81_reg_4584}, {2'd0}}, {tmp_82_reg_4589}}, {2'd0}}, {tmp_83_reg_4595}}, {2'd0}}, {tmp_84_reg_4601}}, {2'd0}}, {tmp_85_reg_4607}}, {2'd0}}, {tmp_86_reg_4613}}, {2'd0}}, {tmp_87_reg_4619}}, {2'd0}}, {trunc_ln9_1_reg_4625}};

assign and_ln9_3_cast1_fu_3446_p14 = {{{{{{{{{{{{{tmp_89_reg_4636}, {2'd0}}, {tmp_90_reg_4642}}, {2'd0}}, {tmp_91_reg_4648}}, {2'd0}}, {tmp_92_reg_4654}}, {2'd0}}, {tmp_93_reg_4660}}, {2'd0}}, {tmp_94_reg_4666}}, {2'd0}}, {tmp_95_reg_4672}};

assign and_ln9_3_fu_3420_p16 = {{{{{{{{{{{{{{{tmp_88_reg_4631}, {2'd0}}, {tmp_89_reg_4636}}, {2'd0}}, {tmp_90_reg_4642}}, {2'd0}}, {tmp_91_reg_4648}}, {2'd0}}, {tmp_92_reg_4654}}, {2'd0}}, {tmp_93_reg_4660}}, {2'd0}}, {tmp_94_reg_4666}}, {2'd0}}, {tmp_95_reg_4672}};

assign and_ln9_4_cast1_fu_3569_p14 = {{{{{{{{{{{{{tmp_134_reg_4683}, {2'd0}}, {tmp_135_reg_4689}}, {2'd0}}, {tmp_136_reg_4695}}, {2'd0}}, {tmp_137_reg_4701}}, {2'd0}}, {tmp_138_reg_4707}}, {2'd0}}, {tmp_139_reg_4713}}, {2'd0}}, {trunc_ln9_2_reg_4719}};

assign and_ln9_4_fu_3543_p16 = {{{{{{{{{{{{{{{tmp_133_reg_4678}, {2'd0}}, {tmp_134_reg_4683}}, {2'd0}}, {tmp_135_reg_4689}}, {2'd0}}, {tmp_136_reg_4695}}, {2'd0}}, {tmp_137_reg_4701}}, {2'd0}}, {tmp_138_reg_4707}}, {2'd0}}, {tmp_139_reg_4713}}, {2'd0}}, {trunc_ln9_2_reg_4719}};

assign and_ln9_5_cast1_fu_3626_p14 = {{{{{{{{{{{{{tmp_141_reg_4730}, {2'd0}}, {tmp_142_reg_4736}}, {2'd0}}, {tmp_143_reg_4742}}, {2'd0}}, {tmp_144_reg_4748}}, {2'd0}}, {tmp_145_reg_4754}}, {2'd0}}, {tmp_146_reg_4760}}, {2'd0}}, {tmp_147_reg_4766}};

assign and_ln9_5_fu_3600_p16 = {{{{{{{{{{{{{{{tmp_140_reg_4725}, {2'd0}}, {tmp_141_reg_4730}}, {2'd0}}, {tmp_142_reg_4736}}, {2'd0}}, {tmp_143_reg_4742}}, {2'd0}}, {tmp_144_reg_4748}}, {2'd0}}, {tmp_145_reg_4754}}, {2'd0}}, {tmp_146_reg_4760}}, {2'd0}}, {tmp_147_reg_4766}};

assign and_ln9_6_cast1_fu_3749_p14 = {{{{{{{{{{{{{tmp_185_reg_4777}, {2'd0}}, {tmp_186_reg_4783}}, {2'd0}}, {tmp_187_reg_4789}}, {2'd0}}, {tmp_188_reg_4795}}, {2'd0}}, {tmp_189_reg_4801}}, {2'd0}}, {tmp_190_reg_4807}}, {2'd0}}, {trunc_ln9_3_reg_4813}};

assign and_ln9_6_fu_3723_p16 = {{{{{{{{{{{{{{{tmp_184_reg_4772}, {2'd0}}, {tmp_185_reg_4777}}, {2'd0}}, {tmp_186_reg_4783}}, {2'd0}}, {tmp_187_reg_4789}}, {2'd0}}, {tmp_188_reg_4795}}, {2'd0}}, {tmp_189_reg_4801}}, {2'd0}}, {tmp_190_reg_4807}}, {2'd0}}, {trunc_ln9_3_reg_4813}};

assign and_ln9_7_cast1_fu_3806_p14 = {{{{{{{{{{{{{tmp_192_reg_4824}, {2'd0}}, {tmp_193_reg_4830}}, {2'd0}}, {tmp_194_reg_4836}}, {2'd0}}, {tmp_195_reg_4842}}, {2'd0}}, {tmp_196_reg_4848}}, {2'd0}}, {tmp_197_reg_4854}}, {2'd0}}, {tmp_198_reg_4860}};

assign and_ln9_7_fu_3780_p16 = {{{{{{{{{{{{{{{tmp_191_reg_4819}, {2'd0}}, {tmp_192_reg_4824}}, {2'd0}}, {tmp_193_reg_4830}}, {2'd0}}, {tmp_194_reg_4836}}, {2'd0}}, {tmp_195_reg_4842}}, {2'd0}}, {tmp_196_reg_4848}}, {2'd0}}, {tmp_197_reg_4854}}, {2'd0}}, {tmp_198_reg_4860}};

assign and_ln9_cast1_fu_3209_p14 = {{{{{{{{{{{{{tmp_31_reg_4495}, {2'd0}}, {tmp_32_reg_4501}}, {2'd0}}, {tmp_33_reg_4507}}, {2'd0}}, {tmp_34_reg_4513}}, {2'd0}}, {tmp_35_reg_4519}}, {2'd0}}, {tmp_36_reg_4525}}, {2'd0}}, {trunc_ln9_reg_4531}};

assign and_ln9_fu_3183_p16 = {{{{{{{{{{{{{{{tmp_s_reg_4490}, {2'd0}}, {tmp_31_reg_4495}}, {2'd0}}, {tmp_32_reg_4501}}, {2'd0}}, {tmp_33_reg_4507}}, {2'd0}}, {tmp_34_reg_4513}}, {2'd0}}, {tmp_35_reg_4519}}, {2'd0}}, {tmp_36_reg_4525}}, {2'd0}}, {trunc_ln9_reg_4531}};

assign and_ln_fu_3903_p6 = {{{{{tmp_46_reg_4866}, {4'd0}}, {tmp_47_reg_4872}}, {4'd0}}, {trunc_ln10_reg_4879}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_condition_357 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln34_fu_304_p2 = ((n_fu_298_p2 < 4'd10) ? 1'b1 : 1'b0);

assign n_fu_298_p2 = (ap_sig_allocacmp_n21_load + 4'd2);

assign or_ln_fu_284_p3 = {{tmp_101_fu_274_p4}, {1'd1}};

assign p_ZL9golden_w3_0_address0 = zext_ln45_fu_292_p1;

assign p_ZL9golden_w3_0_address1 = zext_ln34_fu_268_p1;

assign p_ZL9golden_w3_1_address0 = zext_ln45_fu_292_p1;

assign p_ZL9golden_w3_1_address1 = zext_ln34_fu_268_p1;

assign s0_1_fu_1599_p2 = (zext_ln8_3_fu_1583_p1 + zext_ln8_2_fu_1319_p1);

assign s0_2_fu_2311_p2 = (zext_ln8_5_fu_2295_p1 + zext_ln8_4_fu_2031_p1);

assign s0_3_fu_3023_p2 = (zext_ln8_7_fu_3007_p1 + zext_ln8_6_fu_2743_p1);

assign s0_fu_877_p2 = (zext_ln8_1_fu_861_p1 + zext_ln8_fu_597_p1);

assign s1_1_fu_3483_p2 = (zext_ln9_3_fu_3473_p1 + zext_ln9_2_fu_3416_p1);

assign s1_2_fu_3663_p2 = (zext_ln9_5_fu_3653_p1 + zext_ln9_4_fu_3596_p1);

assign s1_3_fu_3843_p2 = (zext_ln9_7_fu_3833_p1 + zext_ln9_6_fu_3776_p1);

assign s1_fu_3303_p2 = (zext_ln9_1_fu_3293_p1 + zext_ln9_fu_3236_p1);

assign s3_1_fu_4013_p2 = (zext_ln11_3_fu_4003_p1 + zext_ln11_2_fu_3985_p1);

assign s3_2_fu_4081_p2 = (zext_ln11_5_fu_4071_p1 + zext_ln11_4_fu_4053_p1);

assign s3_3_fu_4149_p2 = (zext_ln11_7_fu_4139_p1 + zext_ln11_6_fu_4121_p1);

assign s3_fu_3945_p2 = (zext_ln11_1_fu_3935_p1 + zext_ln11_fu_3917_p1);

assign s4_1_fu_4033_p2 = (zext_ln12_1_fu_4029_p1 + add_ln11_2_fu_4007_p2);

assign s4_2_fu_4101_p2 = (zext_ln12_2_fu_4097_p1 + add_ln12_fu_4075_p2);

assign s4_3_fu_4169_p2 = (zext_ln12_3_fu_4165_p1 + add_ln12_2_fu_4143_p2);

assign s4_fu_3965_p2 = (zext_ln12_fu_3961_p1 + add_ln11_fu_3939_p2);

assign shl_ln60_1_fu_4217_p3 = {{add_ln60_2_fu_4211_p2}, {1'd0}};

assign shl_ln_fu_4187_p3 = {{add_ln60_fu_4181_p2}, {1'd0}};

assign tmp_100_fu_4019_p4 = {{s3_1_fu_4013_p2[20:16]}};

assign tmp_101_fu_274_p4 = {{ap_sig_allocacmp_n21_load[3:1]}};

assign tmp_102_fu_1775_p3 = xor_ln8_fu_1769_p2[32'd30];

assign tmp_103_fu_1783_p3 = xor_ln8_fu_1769_p2[32'd28];

assign tmp_104_fu_1791_p3 = xor_ln8_fu_1769_p2[32'd26];

assign tmp_105_fu_1799_p3 = xor_ln8_fu_1769_p2[32'd24];

assign tmp_106_fu_1807_p3 = xor_ln8_fu_1769_p2[32'd22];

assign tmp_107_fu_1815_p3 = xor_ln8_fu_1769_p2[32'd20];

assign tmp_108_fu_1823_p3 = xor_ln8_fu_1769_p2[32'd18];

assign tmp_109_fu_1831_p3 = xor_ln8_fu_1769_p2[32'd16];

assign tmp_10_fu_421_p3 = xor_ln46_fu_335_p2[32'd10];

assign tmp_110_fu_1839_p3 = xor_ln8_fu_1769_p2[32'd14];

assign tmp_111_fu_1847_p3 = xor_ln8_fu_1769_p2[32'd12];

assign tmp_112_fu_1855_p3 = xor_ln8_fu_1769_p2[32'd10];

assign tmp_113_fu_1863_p3 = xor_ln8_fu_1769_p2[32'd8];

assign tmp_114_fu_1871_p3 = xor_ln8_fu_1769_p2[32'd6];

assign tmp_115_fu_1879_p3 = xor_ln8_fu_1769_p2[32'd4];

assign tmp_116_fu_1887_p3 = xor_ln8_fu_1769_p2[32'd2];

assign tmp_117_fu_2035_p3 = xnr_2_fu_1763_p2[32'd31];

assign tmp_118_fu_2043_p3 = xnr_2_fu_1763_p2[32'd29];

assign tmp_119_fu_2051_p3 = xnr_2_fu_1763_p2[32'd27];

assign tmp_11_fu_429_p3 = xor_ln46_fu_335_p2[32'd8];

assign tmp_120_fu_2059_p3 = xnr_2_fu_1763_p2[32'd25];

assign tmp_121_fu_2067_p3 = xnr_2_fu_1763_p2[32'd23];

assign tmp_122_fu_2075_p3 = xnr_2_fu_1763_p2[32'd21];

assign tmp_123_fu_2083_p3 = xnr_2_fu_1763_p2[32'd19];

assign tmp_124_fu_2091_p3 = xnr_2_fu_1763_p2[32'd17];

assign tmp_125_fu_2099_p3 = xnr_2_fu_1763_p2[32'd15];

assign tmp_126_fu_2107_p3 = xnr_2_fu_1763_p2[32'd13];

assign tmp_127_fu_2115_p3 = xnr_2_fu_1763_p2[32'd11];

assign tmp_128_fu_2123_p3 = xnr_2_fu_1763_p2[32'd9];

assign tmp_129_fu_2131_p3 = xnr_2_fu_1763_p2[32'd7];

assign tmp_12_fu_437_p3 = xor_ln46_fu_335_p2[32'd6];

assign tmp_130_fu_2139_p3 = xnr_2_fu_1763_p2[32'd5];

assign tmp_131_fu_2147_p3 = xnr_2_fu_1763_p2[32'd3];

assign tmp_132_fu_2155_p3 = xnr_2_fu_1763_p2[32'd1];

assign tmp_13_fu_445_p3 = xor_ln46_fu_335_p2[32'd4];

assign tmp_148_fu_3669_p4 = {{s1_2_fu_3663_p2[30:4]}};

assign tmp_14_fu_453_p3 = xor_ln46_fu_335_p2[32'd2];

assign tmp_152_fu_4087_p4 = {{s3_2_fu_4081_p2[20:16]}};

assign tmp_153_fu_2487_p3 = xor_ln8_1_fu_2481_p2[32'd30];

assign tmp_154_fu_2495_p3 = xor_ln8_1_fu_2481_p2[32'd28];

assign tmp_155_fu_2503_p3 = xor_ln8_1_fu_2481_p2[32'd26];

assign tmp_156_fu_2511_p3 = xor_ln8_1_fu_2481_p2[32'd24];

assign tmp_157_fu_2519_p3 = xor_ln8_1_fu_2481_p2[32'd22];

assign tmp_158_fu_2527_p3 = xor_ln8_1_fu_2481_p2[32'd20];

assign tmp_159_fu_2535_p3 = xor_ln8_1_fu_2481_p2[32'd18];

assign tmp_15_fu_601_p3 = xnr_fu_329_p2[32'd31];

assign tmp_160_fu_2543_p3 = xor_ln8_1_fu_2481_p2[32'd16];

assign tmp_161_fu_2551_p3 = xor_ln8_1_fu_2481_p2[32'd14];

assign tmp_162_fu_2559_p3 = xor_ln8_1_fu_2481_p2[32'd12];

assign tmp_163_fu_2567_p3 = xor_ln8_1_fu_2481_p2[32'd10];

assign tmp_164_fu_2575_p3 = xor_ln8_1_fu_2481_p2[32'd8];

assign tmp_165_fu_2583_p3 = xor_ln8_1_fu_2481_p2[32'd6];

assign tmp_166_fu_2591_p3 = xor_ln8_1_fu_2481_p2[32'd4];

assign tmp_167_fu_2599_p3 = xor_ln8_1_fu_2481_p2[32'd2];

assign tmp_168_fu_2747_p3 = xnr_3_fu_2475_p2[32'd31];

assign tmp_169_fu_2755_p3 = xnr_3_fu_2475_p2[32'd29];

assign tmp_16_fu_609_p3 = xnr_fu_329_p2[32'd29];

assign tmp_170_fu_2763_p3 = xnr_3_fu_2475_p2[32'd27];

assign tmp_171_fu_2771_p3 = xnr_3_fu_2475_p2[32'd25];

assign tmp_172_fu_2779_p3 = xnr_3_fu_2475_p2[32'd23];

assign tmp_173_fu_2787_p3 = xnr_3_fu_2475_p2[32'd21];

assign tmp_174_fu_2795_p3 = xnr_3_fu_2475_p2[32'd19];

assign tmp_175_fu_2803_p3 = xnr_3_fu_2475_p2[32'd17];

assign tmp_176_fu_2811_p3 = xnr_3_fu_2475_p2[32'd15];

assign tmp_177_fu_2819_p3 = xnr_3_fu_2475_p2[32'd13];

assign tmp_178_fu_2827_p3 = xnr_3_fu_2475_p2[32'd11];

assign tmp_179_fu_2835_p3 = xnr_3_fu_2475_p2[32'd9];

assign tmp_17_fu_617_p3 = xnr_fu_329_p2[32'd27];

assign tmp_180_fu_2843_p3 = xnr_3_fu_2475_p2[32'd7];

assign tmp_181_fu_2851_p3 = xnr_3_fu_2475_p2[32'd5];

assign tmp_182_fu_2859_p3 = xnr_3_fu_2475_p2[32'd3];

assign tmp_183_fu_2867_p3 = xnr_3_fu_2475_p2[32'd1];

assign tmp_18_fu_625_p3 = xnr_fu_329_p2[32'd25];

assign tmp_199_fu_3849_p4 = {{s1_3_fu_3843_p2[30:4]}};

assign tmp_19_fu_633_p3 = xnr_fu_329_p2[32'd23];

assign tmp_1_fu_349_p3 = xor_ln46_fu_335_p2[32'd28];

assign tmp_203_fu_4155_p4 = {{s3_3_fu_4149_p2[20:16]}};

assign tmp_20_fu_641_p3 = xnr_fu_329_p2[32'd21];

assign tmp_21_fu_649_p3 = xnr_fu_329_p2[32'd19];

assign tmp_22_fu_657_p3 = xnr_fu_329_p2[32'd17];

assign tmp_23_fu_665_p3 = xnr_fu_329_p2[32'd15];

assign tmp_24_fu_673_p3 = xnr_fu_329_p2[32'd13];

assign tmp_25_fu_681_p3 = xnr_fu_329_p2[32'd11];

assign tmp_26_fu_689_p3 = xnr_fu_329_p2[32'd9];

assign tmp_27_fu_697_p3 = xnr_fu_329_p2[32'd7];

assign tmp_28_fu_705_p3 = xnr_fu_329_p2[32'd5];

assign tmp_29_fu_713_p3 = xnr_fu_329_p2[32'd3];

assign tmp_2_fu_357_p3 = xor_ln46_fu_335_p2[32'd26];

assign tmp_30_fu_721_p3 = xnr_fu_329_p2[32'd1];

assign tmp_3_fu_365_p3 = xor_ln46_fu_335_p2[32'd24];

assign tmp_45_fu_3309_p4 = {{s1_fu_3303_p2[30:4]}};

assign tmp_49_fu_3951_p4 = {{s3_fu_3945_p2[20:16]}};

assign tmp_4_fu_373_p3 = xor_ln46_fu_335_p2[32'd22];

assign tmp_50_fu_1063_p3 = xor_ln46_1_fu_1057_p2[32'd30];

assign tmp_51_fu_1071_p3 = xor_ln46_1_fu_1057_p2[32'd28];

assign tmp_52_fu_1079_p3 = xor_ln46_1_fu_1057_p2[32'd26];

assign tmp_53_fu_1087_p3 = xor_ln46_1_fu_1057_p2[32'd24];

assign tmp_54_fu_1095_p3 = xor_ln46_1_fu_1057_p2[32'd22];

assign tmp_55_fu_1103_p3 = xor_ln46_1_fu_1057_p2[32'd20];

assign tmp_56_fu_1111_p3 = xor_ln46_1_fu_1057_p2[32'd18];

assign tmp_57_fu_1119_p3 = xor_ln46_1_fu_1057_p2[32'd16];

assign tmp_58_fu_1127_p3 = xor_ln46_1_fu_1057_p2[32'd14];

assign tmp_59_fu_1135_p3 = xor_ln46_1_fu_1057_p2[32'd12];

assign tmp_5_fu_381_p3 = xor_ln46_fu_335_p2[32'd20];

assign tmp_60_fu_1143_p3 = xor_ln46_1_fu_1057_p2[32'd10];

assign tmp_61_fu_1151_p3 = xor_ln46_1_fu_1057_p2[32'd8];

assign tmp_62_fu_1159_p3 = xor_ln46_1_fu_1057_p2[32'd6];

assign tmp_63_fu_1167_p3 = xor_ln46_1_fu_1057_p2[32'd4];

assign tmp_64_fu_1175_p3 = xor_ln46_1_fu_1057_p2[32'd2];

assign tmp_65_fu_1323_p3 = xnr_1_fu_1051_p2[32'd31];

assign tmp_66_fu_1331_p3 = xnr_1_fu_1051_p2[32'd29];

assign tmp_67_fu_1339_p3 = xnr_1_fu_1051_p2[32'd27];

assign tmp_68_fu_1347_p3 = xnr_1_fu_1051_p2[32'd25];

assign tmp_69_fu_1355_p3 = xnr_1_fu_1051_p2[32'd23];

assign tmp_6_fu_389_p3 = xor_ln46_fu_335_p2[32'd18];

assign tmp_70_fu_1363_p3 = xnr_1_fu_1051_p2[32'd21];

assign tmp_71_fu_1371_p3 = xnr_1_fu_1051_p2[32'd19];

assign tmp_72_fu_1379_p3 = xnr_1_fu_1051_p2[32'd17];

assign tmp_73_fu_1387_p3 = xnr_1_fu_1051_p2[32'd15];

assign tmp_74_fu_1395_p3 = xnr_1_fu_1051_p2[32'd13];

assign tmp_75_fu_1403_p3 = xnr_1_fu_1051_p2[32'd11];

assign tmp_76_fu_1411_p3 = xnr_1_fu_1051_p2[32'd9];

assign tmp_77_fu_1419_p3 = xnr_1_fu_1051_p2[32'd7];

assign tmp_78_fu_1427_p3 = xnr_1_fu_1051_p2[32'd5];

assign tmp_79_fu_1435_p3 = xnr_1_fu_1051_p2[32'd3];

assign tmp_7_fu_397_p3 = xor_ln46_fu_335_p2[32'd16];

assign tmp_80_fu_1443_p3 = xnr_1_fu_1051_p2[32'd1];

assign tmp_8_fu_405_p3 = xor_ln46_fu_335_p2[32'd14];

assign tmp_96_fu_3489_p4 = {{s1_1_fu_3483_p2[30:4]}};

assign tmp_9_fu_413_p3 = xor_ln46_fu_335_p2[32'd12];

assign tmp_fu_341_p3 = xor_ln46_fu_335_p2[32'd30];

assign trunc_ln10_1_fu_3529_p1 = add_ln10_1_fu_3503_p2[3:0];

assign trunc_ln10_fu_3349_p1 = add_ln10_fu_3323_p2[3:0];

assign trunc_ln11_1_fu_3889_p1 = add_ln10_3_fu_3863_p2[3:0];

assign trunc_ln11_fu_3709_p1 = add_ln10_2_fu_3683_p2[3:0];

assign trunc_ln18_1_fu_256_p1 = p_read1[30:0];

assign trunc_ln18_2_fu_325_p1 = p_ZL9golden_w3_0_q1[30:0];

assign trunc_ln18_3_fu_1047_p1 = p_ZL9golden_w3_1_q1[30:0];

assign trunc_ln18_4_fu_1759_p1 = p_ZL9golden_w3_0_q0[30:0];

assign trunc_ln18_5_fu_2471_p1 = p_ZL9golden_w3_1_q0[30:0];

assign trunc_ln18_fu_252_p1 = p_read[30:0];

assign trunc_ln8_1_fu_1183_p1 = xor_ln46_1_fu_1057_p2[0:0];

assign trunc_ln8_2_fu_1895_p1 = xor_ln8_fu_1769_p2[0:0];

assign trunc_ln8_3_fu_2607_p1 = xor_ln8_1_fu_2481_p2[0:0];

assign trunc_ln8_fu_461_p1 = xor_ln46_fu_335_p2[0:0];

assign trunc_ln9_1_fu_1675_p1 = add_ln8_3_fu_1587_p2[1:0];

assign trunc_ln9_2_fu_2387_p1 = add_ln8_6_fu_2299_p2[1:0];

assign trunc_ln9_3_fu_3099_p1 = add_ln8_9_fu_3011_p2[1:0];

assign trunc_ln9_fu_953_p1 = add_ln8_1_fu_865_p2[1:0];

assign xnr_1_fu_1051_p2 = (xor_ln18_2_fu_1037_p2 ^ p_ZL9golden_w3_1_q1);

assign xnr_2_fu_1763_p2 = (xor_ln18_fu_315_p2 ^ p_ZL9golden_w3_0_q0);

assign xnr_3_fu_2475_p2 = (xor_ln18_2_fu_1037_p2 ^ p_ZL9golden_w3_1_q0);

assign xnr_fu_329_p2 = (xor_ln18_fu_315_p2 ^ p_ZL9golden_w3_0_q1);

assign xor_ln18_1_fu_320_p2 = (trunc_ln18_reg_4452 ^ 31'd1431655765);

assign xor_ln18_2_fu_1037_p2 = (p_read1121_reg_4382 ^ 32'd4294967295);

assign xor_ln18_4_fu_1042_p2 = (trunc_ln18_1_reg_4457 ^ 31'd1431655765);

assign xor_ln18_fu_315_p2 = (p_read120_reg_4387 ^ 32'd4294967295);

assign xor_ln46_1_fu_1057_p2 = (xor_ln18_4_fu_1042_p2 ^ trunc_ln18_3_fu_1047_p1);

assign xor_ln46_fu_335_p2 = (xor_ln18_1_fu_320_p2 ^ trunc_ln18_2_fu_325_p1);

assign xor_ln8_1_fu_2481_p2 = (xor_ln18_4_fu_1042_p2 ^ trunc_ln18_5_fu_2471_p1);

assign xor_ln8_fu_1769_p2 = (xor_ln18_1_fu_320_p2 ^ trunc_ln18_4_fu_1759_p1);

assign zext_ln10_1_fu_3499_p1 = tmp_96_fu_3489_p4;

assign zext_ln10_2_fu_3679_p1 = tmp_148_fu_3669_p4;

assign zext_ln10_3_fu_3859_p1 = tmp_199_fu_3849_p4;

assign zext_ln10_fu_3319_p1 = tmp_45_fu_3309_p4;

assign zext_ln11_10_fu_3982_p1 = trunc_ln10_1_reg_4903;

assign zext_ln11_11_fu_4000_p1 = tmp_98_reg_4896;

assign zext_ln11_12_fu_4050_p1 = trunc_ln11_reg_4927;

assign zext_ln11_13_fu_4068_p1 = tmp_150_reg_4920;

assign zext_ln11_14_fu_4118_p1 = trunc_ln11_1_reg_4951;

assign zext_ln11_15_fu_4136_p1 = tmp_201_reg_4944;

assign zext_ln11_1_fu_3935_p1 = and_ln1_fu_3921_p6;

assign zext_ln11_2_fu_3985_p1 = and_ln10_1_fu_3971_p6;

assign zext_ln11_3_fu_4003_p1 = and_ln11_1_fu_3989_p6;

assign zext_ln11_4_fu_4053_p1 = and_ln11_2_fu_4039_p6;

assign zext_ln11_5_fu_4071_p1 = and_ln11_3_fu_4057_p6;

assign zext_ln11_6_fu_4121_p1 = and_ln11_4_fu_4107_p6;

assign zext_ln11_7_fu_4139_p1 = and_ln11_5_fu_4125_p6;

assign zext_ln11_8_fu_3914_p1 = trunc_ln10_reg_4879;

assign zext_ln11_9_fu_3932_p1 = tmp_47_reg_4872;

assign zext_ln11_fu_3917_p1 = and_ln_fu_3903_p6;

assign zext_ln12_1_fu_4029_p1 = tmp_100_fu_4019_p4;

assign zext_ln12_2_fu_4097_p1 = tmp_152_fu_4087_p4;

assign zext_ln12_3_fu_4165_p1 = tmp_203_fu_4155_p4;

assign zext_ln12_fu_3961_p1 = tmp_49_fu_3951_p4;

assign zext_ln34_fu_268_p1 = ap_sig_allocacmp_n21_load;

assign zext_ln45_fu_292_p1 = or_ln_fu_284_p3;

assign zext_ln56_1_fu_4205_p1 = s4_2_reg_4972;

assign zext_ln56_fu_4175_p1 = s4_reg_4962;

assign zext_ln60_1_fu_4195_p1 = shl_ln_fu_4187_p3;

assign zext_ln60_2_fu_4208_p1 = s4_3_reg_4977;

assign zext_ln60_3_fu_4225_p1 = shl_ln60_1_fu_4217_p3;

assign zext_ln60_fu_4178_p1 = s4_1_reg_4967;

assign zext_ln8_10_fu_1315_p1 = and_ln8_2_cast1_fu_1253_p30;

assign zext_ln8_11_fu_1579_p1 = and_ln8_3_cast1_fu_1517_p30;

assign zext_ln8_12_fu_2027_p1 = and_ln8_4_cast1_fu_1965_p30;

assign zext_ln8_13_fu_2291_p1 = and_ln8_5_cast1_fu_2229_p30;

assign zext_ln8_14_fu_2739_p1 = and_ln8_6_cast1_fu_2677_p30;

assign zext_ln8_15_fu_3003_p1 = and_ln8_7_cast1_fu_2941_p30;

assign zext_ln8_1_fu_861_p1 = and_ln8_1_fu_729_p32;

assign zext_ln8_2_fu_1319_p1 = and_ln8_2_fu_1187_p32;

assign zext_ln8_3_fu_1583_p1 = and_ln8_3_fu_1451_p32;

assign zext_ln8_4_fu_2031_p1 = and_ln8_4_fu_1899_p32;

assign zext_ln8_5_fu_2295_p1 = and_ln8_5_fu_2163_p32;

assign zext_ln8_6_fu_2743_p1 = and_ln8_6_fu_2611_p32;

assign zext_ln8_7_fu_3007_p1 = and_ln8_7_fu_2875_p32;

assign zext_ln8_8_fu_593_p1 = and_ln8_cast1_fu_531_p30;

assign zext_ln8_9_fu_857_p1 = and_ln8_1_cast1_fu_795_p30;

assign zext_ln8_fu_597_p1 = and_ln8_fu_465_p32;

assign zext_ln9_10_fu_3412_p1 = and_ln9_2_cast1_fu_3389_p14;

assign zext_ln9_11_fu_3469_p1 = and_ln9_3_cast1_fu_3446_p14;

assign zext_ln9_12_fu_3592_p1 = and_ln9_4_cast1_fu_3569_p14;

assign zext_ln9_13_fu_3649_p1 = and_ln9_5_cast1_fu_3626_p14;

assign zext_ln9_14_fu_3772_p1 = and_ln9_6_cast1_fu_3749_p14;

assign zext_ln9_15_fu_3829_p1 = and_ln9_7_cast1_fu_3806_p14;

assign zext_ln9_1_fu_3293_p1 = and_ln9_1_fu_3240_p16;

assign zext_ln9_2_fu_3416_p1 = and_ln9_2_fu_3363_p16;

assign zext_ln9_3_fu_3473_p1 = and_ln9_3_fu_3420_p16;

assign zext_ln9_4_fu_3596_p1 = and_ln9_4_fu_3543_p16;

assign zext_ln9_5_fu_3653_p1 = and_ln9_5_fu_3600_p16;

assign zext_ln9_6_fu_3776_p1 = and_ln9_6_fu_3723_p16;

assign zext_ln9_7_fu_3833_p1 = and_ln9_7_fu_3780_p16;

assign zext_ln9_8_fu_3232_p1 = and_ln9_cast1_fu_3209_p14;

assign zext_ln9_9_fu_3289_p1 = and_ln9_1_cast1_fu_3266_p14;

assign zext_ln9_fu_3236_p1 = and_ln9_fu_3183_p16;

always @ (posedge ap_clk) begin
    output_13_fu_150[0] <= 1'b0;
    output_12_fu_154[0] <= 1'b0;
    output_11_fu_158[0] <= 1'b0;
    output_10_fu_162[0] <= 1'b0;
    output_9_fu_166[0] <= 1'b0;
    output_8_fu_170[0] <= 1'b0;
    output_7_fu_174[0] <= 1'b0;
    output_6_fu_178[0] <= 1'b0;
    output_5_fu_182[0] <= 1'b0;
    output_fu_186[0] <= 1'b0;
    ap_return_0_preg[0] <= 1'b0;
    ap_return_1_preg[0] <= 1'b0;
    ap_return_2_preg[0] <= 1'b0;
    ap_return_3_preg[0] <= 1'b0;
    ap_return_4_preg[0] <= 1'b0;
    ap_return_5_preg[0] <= 1'b0;
    ap_return_6_preg[0] <= 1'b0;
    ap_return_7_preg[0] <= 1'b0;
    ap_return_8_preg[0] <= 1'b0;
    ap_return_9_preg[0] <= 1'b0;
end

endmodule //bnn_dense_layer_3
