-- ==============================================================
-- Generated by Vitis HLS v2024.2.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bnn_sign_and_quantize is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_0_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_1_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_2_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_3_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_4_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_5_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_6_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_7_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_8_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_9_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_10_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_11_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_12_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_13_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_14_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_15_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_16_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_17_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_18_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_19_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_20_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_21_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_22_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_23_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_24_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_25_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_26_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_27_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_28_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_29_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_30_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_31_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_32_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_33_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_34_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_35_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_36_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_37_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_38_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_39_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_40_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_41_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_42_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_43_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_44_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_45_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_46_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_47_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_48_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_49_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_50_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_51_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_52_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_53_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_54_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_55_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_56_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_57_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_58_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_59_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_60_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_61_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_62_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_63_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_64_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_65_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_66_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_67_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_68_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_69_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_70_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_71_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_72_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_73_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_74_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_75_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_76_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_77_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_78_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_79_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_80_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_81_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_82_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_83_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_84_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_85_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_86_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_87_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_88_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_89_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_90_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_91_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_92_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_93_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_94_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_95_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_96_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_97_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_98_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_99_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_100_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_101_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_102_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_103_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_104_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_105_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_106_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_107_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_108_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_109_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_110_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_111_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_112_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_113_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_114_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_115_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_116_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_117_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_118_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_119_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_120_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_121_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_122_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_123_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_124_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_125_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_126_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_127_val : IN STD_LOGIC_VECTOR (10 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of bnn_sign_and_quantize is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln85_fu_1382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal i_2_reg_2185 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_fu_1398_p259 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_reg_2194 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_fu_566 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln85_fu_1388_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal or3_fu_570 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or1_fu_2082_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_or3_load : STD_LOGIC_VECTOR (31 downto 0);
    signal or6_fu_574 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or4_fu_2068_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_or6_load : STD_LOGIC_VECTOR (31 downto 0);
    signal or9_fu_578 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or7_fu_2054_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_or9_load : STD_LOGIC_VECTOR (31 downto 0);
    signal or12_fu_582 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal or10_fu_2040_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_or12_load : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_1398_p257 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_1398_p258 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln88_fu_1935_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal bit_pos_fu_1947_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln89_fu_1953_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_1968_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_1968_p10 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln88_4_fu_1938_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_1968_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln92_fu_1962_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln91_fu_1957_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_1_fu_2004_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_2_fu_2010_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln92_2_fu_2022_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_fu_1998_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln92_1_fu_2028_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln91_fu_2016_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln92_3_fu_2034_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln92_fu_1992_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln92_fu_2048_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln92_1_fu_2062_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln92_2_fu_2076_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_fu_1398_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p5 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p7 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p9 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p11 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p13 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p15 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p17 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p19 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p21 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p23 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p25 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p27 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p29 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p31 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p33 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p35 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p37 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p39 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p41 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p43 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p45 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p47 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p49 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p51 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p53 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p55 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p57 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p59 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p61 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p63 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p65 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p67 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p69 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p71 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p73 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p75 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p77 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p79 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p81 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p83 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p85 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p87 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p89 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p91 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p93 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p95 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p97 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p99 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p101 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p103 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p105 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p107 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p109 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p111 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p113 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p115 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p117 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p119 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p121 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p123 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p125 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p127 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p129 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p131 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p133 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p135 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p137 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p139 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p141 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p143 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p145 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p147 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p149 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p151 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p153 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p155 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p157 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p159 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p161 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p163 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p165 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p167 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p169 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p171 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p173 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p175 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p177 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p179 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p181 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p183 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p185 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p187 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p189 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p191 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p193 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p195 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p197 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p199 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p201 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p203 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p205 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p207 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p209 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p211 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p213 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p215 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p217 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p219 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p221 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p223 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p225 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p227 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p229 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p231 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p233 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p235 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p237 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p239 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p241 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p243 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p245 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p247 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p249 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p251 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p253 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_1398_p255 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_2_fu_1968_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_1968_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_1968_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_1968_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component bnn_sparsemux_257_7_11_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (6 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (6 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (6 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (6 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (6 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (6 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (6 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (6 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (6 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (6 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (6 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (6 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (6 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (6 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (6 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (6 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (6 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (6 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (6 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (6 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (6 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (6 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (6 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (6 downto 0);
        din23_WIDTH : INTEGER;
        CASE24 : STD_LOGIC_VECTOR (6 downto 0);
        din24_WIDTH : INTEGER;
        CASE25 : STD_LOGIC_VECTOR (6 downto 0);
        din25_WIDTH : INTEGER;
        CASE26 : STD_LOGIC_VECTOR (6 downto 0);
        din26_WIDTH : INTEGER;
        CASE27 : STD_LOGIC_VECTOR (6 downto 0);
        din27_WIDTH : INTEGER;
        CASE28 : STD_LOGIC_VECTOR (6 downto 0);
        din28_WIDTH : INTEGER;
        CASE29 : STD_LOGIC_VECTOR (6 downto 0);
        din29_WIDTH : INTEGER;
        CASE30 : STD_LOGIC_VECTOR (6 downto 0);
        din30_WIDTH : INTEGER;
        CASE31 : STD_LOGIC_VECTOR (6 downto 0);
        din31_WIDTH : INTEGER;
        CASE32 : STD_LOGIC_VECTOR (6 downto 0);
        din32_WIDTH : INTEGER;
        CASE33 : STD_LOGIC_VECTOR (6 downto 0);
        din33_WIDTH : INTEGER;
        CASE34 : STD_LOGIC_VECTOR (6 downto 0);
        din34_WIDTH : INTEGER;
        CASE35 : STD_LOGIC_VECTOR (6 downto 0);
        din35_WIDTH : INTEGER;
        CASE36 : STD_LOGIC_VECTOR (6 downto 0);
        din36_WIDTH : INTEGER;
        CASE37 : STD_LOGIC_VECTOR (6 downto 0);
        din37_WIDTH : INTEGER;
        CASE38 : STD_LOGIC_VECTOR (6 downto 0);
        din38_WIDTH : INTEGER;
        CASE39 : STD_LOGIC_VECTOR (6 downto 0);
        din39_WIDTH : INTEGER;
        CASE40 : STD_LOGIC_VECTOR (6 downto 0);
        din40_WIDTH : INTEGER;
        CASE41 : STD_LOGIC_VECTOR (6 downto 0);
        din41_WIDTH : INTEGER;
        CASE42 : STD_LOGIC_VECTOR (6 downto 0);
        din42_WIDTH : INTEGER;
        CASE43 : STD_LOGIC_VECTOR (6 downto 0);
        din43_WIDTH : INTEGER;
        CASE44 : STD_LOGIC_VECTOR (6 downto 0);
        din44_WIDTH : INTEGER;
        CASE45 : STD_LOGIC_VECTOR (6 downto 0);
        din45_WIDTH : INTEGER;
        CASE46 : STD_LOGIC_VECTOR (6 downto 0);
        din46_WIDTH : INTEGER;
        CASE47 : STD_LOGIC_VECTOR (6 downto 0);
        din47_WIDTH : INTEGER;
        CASE48 : STD_LOGIC_VECTOR (6 downto 0);
        din48_WIDTH : INTEGER;
        CASE49 : STD_LOGIC_VECTOR (6 downto 0);
        din49_WIDTH : INTEGER;
        CASE50 : STD_LOGIC_VECTOR (6 downto 0);
        din50_WIDTH : INTEGER;
        CASE51 : STD_LOGIC_VECTOR (6 downto 0);
        din51_WIDTH : INTEGER;
        CASE52 : STD_LOGIC_VECTOR (6 downto 0);
        din52_WIDTH : INTEGER;
        CASE53 : STD_LOGIC_VECTOR (6 downto 0);
        din53_WIDTH : INTEGER;
        CASE54 : STD_LOGIC_VECTOR (6 downto 0);
        din54_WIDTH : INTEGER;
        CASE55 : STD_LOGIC_VECTOR (6 downto 0);
        din55_WIDTH : INTEGER;
        CASE56 : STD_LOGIC_VECTOR (6 downto 0);
        din56_WIDTH : INTEGER;
        CASE57 : STD_LOGIC_VECTOR (6 downto 0);
        din57_WIDTH : INTEGER;
        CASE58 : STD_LOGIC_VECTOR (6 downto 0);
        din58_WIDTH : INTEGER;
        CASE59 : STD_LOGIC_VECTOR (6 downto 0);
        din59_WIDTH : INTEGER;
        CASE60 : STD_LOGIC_VECTOR (6 downto 0);
        din60_WIDTH : INTEGER;
        CASE61 : STD_LOGIC_VECTOR (6 downto 0);
        din61_WIDTH : INTEGER;
        CASE62 : STD_LOGIC_VECTOR (6 downto 0);
        din62_WIDTH : INTEGER;
        CASE63 : STD_LOGIC_VECTOR (6 downto 0);
        din63_WIDTH : INTEGER;
        CASE64 : STD_LOGIC_VECTOR (6 downto 0);
        din64_WIDTH : INTEGER;
        CASE65 : STD_LOGIC_VECTOR (6 downto 0);
        din65_WIDTH : INTEGER;
        CASE66 : STD_LOGIC_VECTOR (6 downto 0);
        din66_WIDTH : INTEGER;
        CASE67 : STD_LOGIC_VECTOR (6 downto 0);
        din67_WIDTH : INTEGER;
        CASE68 : STD_LOGIC_VECTOR (6 downto 0);
        din68_WIDTH : INTEGER;
        CASE69 : STD_LOGIC_VECTOR (6 downto 0);
        din69_WIDTH : INTEGER;
        CASE70 : STD_LOGIC_VECTOR (6 downto 0);
        din70_WIDTH : INTEGER;
        CASE71 : STD_LOGIC_VECTOR (6 downto 0);
        din71_WIDTH : INTEGER;
        CASE72 : STD_LOGIC_VECTOR (6 downto 0);
        din72_WIDTH : INTEGER;
        CASE73 : STD_LOGIC_VECTOR (6 downto 0);
        din73_WIDTH : INTEGER;
        CASE74 : STD_LOGIC_VECTOR (6 downto 0);
        din74_WIDTH : INTEGER;
        CASE75 : STD_LOGIC_VECTOR (6 downto 0);
        din75_WIDTH : INTEGER;
        CASE76 : STD_LOGIC_VECTOR (6 downto 0);
        din76_WIDTH : INTEGER;
        CASE77 : STD_LOGIC_VECTOR (6 downto 0);
        din77_WIDTH : INTEGER;
        CASE78 : STD_LOGIC_VECTOR (6 downto 0);
        din78_WIDTH : INTEGER;
        CASE79 : STD_LOGIC_VECTOR (6 downto 0);
        din79_WIDTH : INTEGER;
        CASE80 : STD_LOGIC_VECTOR (6 downto 0);
        din80_WIDTH : INTEGER;
        CASE81 : STD_LOGIC_VECTOR (6 downto 0);
        din81_WIDTH : INTEGER;
        CASE82 : STD_LOGIC_VECTOR (6 downto 0);
        din82_WIDTH : INTEGER;
        CASE83 : STD_LOGIC_VECTOR (6 downto 0);
        din83_WIDTH : INTEGER;
        CASE84 : STD_LOGIC_VECTOR (6 downto 0);
        din84_WIDTH : INTEGER;
        CASE85 : STD_LOGIC_VECTOR (6 downto 0);
        din85_WIDTH : INTEGER;
        CASE86 : STD_LOGIC_VECTOR (6 downto 0);
        din86_WIDTH : INTEGER;
        CASE87 : STD_LOGIC_VECTOR (6 downto 0);
        din87_WIDTH : INTEGER;
        CASE88 : STD_LOGIC_VECTOR (6 downto 0);
        din88_WIDTH : INTEGER;
        CASE89 : STD_LOGIC_VECTOR (6 downto 0);
        din89_WIDTH : INTEGER;
        CASE90 : STD_LOGIC_VECTOR (6 downto 0);
        din90_WIDTH : INTEGER;
        CASE91 : STD_LOGIC_VECTOR (6 downto 0);
        din91_WIDTH : INTEGER;
        CASE92 : STD_LOGIC_VECTOR (6 downto 0);
        din92_WIDTH : INTEGER;
        CASE93 : STD_LOGIC_VECTOR (6 downto 0);
        din93_WIDTH : INTEGER;
        CASE94 : STD_LOGIC_VECTOR (6 downto 0);
        din94_WIDTH : INTEGER;
        CASE95 : STD_LOGIC_VECTOR (6 downto 0);
        din95_WIDTH : INTEGER;
        CASE96 : STD_LOGIC_VECTOR (6 downto 0);
        din96_WIDTH : INTEGER;
        CASE97 : STD_LOGIC_VECTOR (6 downto 0);
        din97_WIDTH : INTEGER;
        CASE98 : STD_LOGIC_VECTOR (6 downto 0);
        din98_WIDTH : INTEGER;
        CASE99 : STD_LOGIC_VECTOR (6 downto 0);
        din99_WIDTH : INTEGER;
        CASE100 : STD_LOGIC_VECTOR (6 downto 0);
        din100_WIDTH : INTEGER;
        CASE101 : STD_LOGIC_VECTOR (6 downto 0);
        din101_WIDTH : INTEGER;
        CASE102 : STD_LOGIC_VECTOR (6 downto 0);
        din102_WIDTH : INTEGER;
        CASE103 : STD_LOGIC_VECTOR (6 downto 0);
        din103_WIDTH : INTEGER;
        CASE104 : STD_LOGIC_VECTOR (6 downto 0);
        din104_WIDTH : INTEGER;
        CASE105 : STD_LOGIC_VECTOR (6 downto 0);
        din105_WIDTH : INTEGER;
        CASE106 : STD_LOGIC_VECTOR (6 downto 0);
        din106_WIDTH : INTEGER;
        CASE107 : STD_LOGIC_VECTOR (6 downto 0);
        din107_WIDTH : INTEGER;
        CASE108 : STD_LOGIC_VECTOR (6 downto 0);
        din108_WIDTH : INTEGER;
        CASE109 : STD_LOGIC_VECTOR (6 downto 0);
        din109_WIDTH : INTEGER;
        CASE110 : STD_LOGIC_VECTOR (6 downto 0);
        din110_WIDTH : INTEGER;
        CASE111 : STD_LOGIC_VECTOR (6 downto 0);
        din111_WIDTH : INTEGER;
        CASE112 : STD_LOGIC_VECTOR (6 downto 0);
        din112_WIDTH : INTEGER;
        CASE113 : STD_LOGIC_VECTOR (6 downto 0);
        din113_WIDTH : INTEGER;
        CASE114 : STD_LOGIC_VECTOR (6 downto 0);
        din114_WIDTH : INTEGER;
        CASE115 : STD_LOGIC_VECTOR (6 downto 0);
        din115_WIDTH : INTEGER;
        CASE116 : STD_LOGIC_VECTOR (6 downto 0);
        din116_WIDTH : INTEGER;
        CASE117 : STD_LOGIC_VECTOR (6 downto 0);
        din117_WIDTH : INTEGER;
        CASE118 : STD_LOGIC_VECTOR (6 downto 0);
        din118_WIDTH : INTEGER;
        CASE119 : STD_LOGIC_VECTOR (6 downto 0);
        din119_WIDTH : INTEGER;
        CASE120 : STD_LOGIC_VECTOR (6 downto 0);
        din120_WIDTH : INTEGER;
        CASE121 : STD_LOGIC_VECTOR (6 downto 0);
        din121_WIDTH : INTEGER;
        CASE122 : STD_LOGIC_VECTOR (6 downto 0);
        din122_WIDTH : INTEGER;
        CASE123 : STD_LOGIC_VECTOR (6 downto 0);
        din123_WIDTH : INTEGER;
        CASE124 : STD_LOGIC_VECTOR (6 downto 0);
        din124_WIDTH : INTEGER;
        CASE125 : STD_LOGIC_VECTOR (6 downto 0);
        din125_WIDTH : INTEGER;
        CASE126 : STD_LOGIC_VECTOR (6 downto 0);
        din126_WIDTH : INTEGER;
        CASE127 : STD_LOGIC_VECTOR (6 downto 0);
        din127_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        din2 : IN STD_LOGIC_VECTOR (10 downto 0);
        din3 : IN STD_LOGIC_VECTOR (10 downto 0);
        din4 : IN STD_LOGIC_VECTOR (10 downto 0);
        din5 : IN STD_LOGIC_VECTOR (10 downto 0);
        din6 : IN STD_LOGIC_VECTOR (10 downto 0);
        din7 : IN STD_LOGIC_VECTOR (10 downto 0);
        din8 : IN STD_LOGIC_VECTOR (10 downto 0);
        din9 : IN STD_LOGIC_VECTOR (10 downto 0);
        din10 : IN STD_LOGIC_VECTOR (10 downto 0);
        din11 : IN STD_LOGIC_VECTOR (10 downto 0);
        din12 : IN STD_LOGIC_VECTOR (10 downto 0);
        din13 : IN STD_LOGIC_VECTOR (10 downto 0);
        din14 : IN STD_LOGIC_VECTOR (10 downto 0);
        din15 : IN STD_LOGIC_VECTOR (10 downto 0);
        din16 : IN STD_LOGIC_VECTOR (10 downto 0);
        din17 : IN STD_LOGIC_VECTOR (10 downto 0);
        din18 : IN STD_LOGIC_VECTOR (10 downto 0);
        din19 : IN STD_LOGIC_VECTOR (10 downto 0);
        din20 : IN STD_LOGIC_VECTOR (10 downto 0);
        din21 : IN STD_LOGIC_VECTOR (10 downto 0);
        din22 : IN STD_LOGIC_VECTOR (10 downto 0);
        din23 : IN STD_LOGIC_VECTOR (10 downto 0);
        din24 : IN STD_LOGIC_VECTOR (10 downto 0);
        din25 : IN STD_LOGIC_VECTOR (10 downto 0);
        din26 : IN STD_LOGIC_VECTOR (10 downto 0);
        din27 : IN STD_LOGIC_VECTOR (10 downto 0);
        din28 : IN STD_LOGIC_VECTOR (10 downto 0);
        din29 : IN STD_LOGIC_VECTOR (10 downto 0);
        din30 : IN STD_LOGIC_VECTOR (10 downto 0);
        din31 : IN STD_LOGIC_VECTOR (10 downto 0);
        din32 : IN STD_LOGIC_VECTOR (10 downto 0);
        din33 : IN STD_LOGIC_VECTOR (10 downto 0);
        din34 : IN STD_LOGIC_VECTOR (10 downto 0);
        din35 : IN STD_LOGIC_VECTOR (10 downto 0);
        din36 : IN STD_LOGIC_VECTOR (10 downto 0);
        din37 : IN STD_LOGIC_VECTOR (10 downto 0);
        din38 : IN STD_LOGIC_VECTOR (10 downto 0);
        din39 : IN STD_LOGIC_VECTOR (10 downto 0);
        din40 : IN STD_LOGIC_VECTOR (10 downto 0);
        din41 : IN STD_LOGIC_VECTOR (10 downto 0);
        din42 : IN STD_LOGIC_VECTOR (10 downto 0);
        din43 : IN STD_LOGIC_VECTOR (10 downto 0);
        din44 : IN STD_LOGIC_VECTOR (10 downto 0);
        din45 : IN STD_LOGIC_VECTOR (10 downto 0);
        din46 : IN STD_LOGIC_VECTOR (10 downto 0);
        din47 : IN STD_LOGIC_VECTOR (10 downto 0);
        din48 : IN STD_LOGIC_VECTOR (10 downto 0);
        din49 : IN STD_LOGIC_VECTOR (10 downto 0);
        din50 : IN STD_LOGIC_VECTOR (10 downto 0);
        din51 : IN STD_LOGIC_VECTOR (10 downto 0);
        din52 : IN STD_LOGIC_VECTOR (10 downto 0);
        din53 : IN STD_LOGIC_VECTOR (10 downto 0);
        din54 : IN STD_LOGIC_VECTOR (10 downto 0);
        din55 : IN STD_LOGIC_VECTOR (10 downto 0);
        din56 : IN STD_LOGIC_VECTOR (10 downto 0);
        din57 : IN STD_LOGIC_VECTOR (10 downto 0);
        din58 : IN STD_LOGIC_VECTOR (10 downto 0);
        din59 : IN STD_LOGIC_VECTOR (10 downto 0);
        din60 : IN STD_LOGIC_VECTOR (10 downto 0);
        din61 : IN STD_LOGIC_VECTOR (10 downto 0);
        din62 : IN STD_LOGIC_VECTOR (10 downto 0);
        din63 : IN STD_LOGIC_VECTOR (10 downto 0);
        din64 : IN STD_LOGIC_VECTOR (10 downto 0);
        din65 : IN STD_LOGIC_VECTOR (10 downto 0);
        din66 : IN STD_LOGIC_VECTOR (10 downto 0);
        din67 : IN STD_LOGIC_VECTOR (10 downto 0);
        din68 : IN STD_LOGIC_VECTOR (10 downto 0);
        din69 : IN STD_LOGIC_VECTOR (10 downto 0);
        din70 : IN STD_LOGIC_VECTOR (10 downto 0);
        din71 : IN STD_LOGIC_VECTOR (10 downto 0);
        din72 : IN STD_LOGIC_VECTOR (10 downto 0);
        din73 : IN STD_LOGIC_VECTOR (10 downto 0);
        din74 : IN STD_LOGIC_VECTOR (10 downto 0);
        din75 : IN STD_LOGIC_VECTOR (10 downto 0);
        din76 : IN STD_LOGIC_VECTOR (10 downto 0);
        din77 : IN STD_LOGIC_VECTOR (10 downto 0);
        din78 : IN STD_LOGIC_VECTOR (10 downto 0);
        din79 : IN STD_LOGIC_VECTOR (10 downto 0);
        din80 : IN STD_LOGIC_VECTOR (10 downto 0);
        din81 : IN STD_LOGIC_VECTOR (10 downto 0);
        din82 : IN STD_LOGIC_VECTOR (10 downto 0);
        din83 : IN STD_LOGIC_VECTOR (10 downto 0);
        din84 : IN STD_LOGIC_VECTOR (10 downto 0);
        din85 : IN STD_LOGIC_VECTOR (10 downto 0);
        din86 : IN STD_LOGIC_VECTOR (10 downto 0);
        din87 : IN STD_LOGIC_VECTOR (10 downto 0);
        din88 : IN STD_LOGIC_VECTOR (10 downto 0);
        din89 : IN STD_LOGIC_VECTOR (10 downto 0);
        din90 : IN STD_LOGIC_VECTOR (10 downto 0);
        din91 : IN STD_LOGIC_VECTOR (10 downto 0);
        din92 : IN STD_LOGIC_VECTOR (10 downto 0);
        din93 : IN STD_LOGIC_VECTOR (10 downto 0);
        din94 : IN STD_LOGIC_VECTOR (10 downto 0);
        din95 : IN STD_LOGIC_VECTOR (10 downto 0);
        din96 : IN STD_LOGIC_VECTOR (10 downto 0);
        din97 : IN STD_LOGIC_VECTOR (10 downto 0);
        din98 : IN STD_LOGIC_VECTOR (10 downto 0);
        din99 : IN STD_LOGIC_VECTOR (10 downto 0);
        din100 : IN STD_LOGIC_VECTOR (10 downto 0);
        din101 : IN STD_LOGIC_VECTOR (10 downto 0);
        din102 : IN STD_LOGIC_VECTOR (10 downto 0);
        din103 : IN STD_LOGIC_VECTOR (10 downto 0);
        din104 : IN STD_LOGIC_VECTOR (10 downto 0);
        din105 : IN STD_LOGIC_VECTOR (10 downto 0);
        din106 : IN STD_LOGIC_VECTOR (10 downto 0);
        din107 : IN STD_LOGIC_VECTOR (10 downto 0);
        din108 : IN STD_LOGIC_VECTOR (10 downto 0);
        din109 : IN STD_LOGIC_VECTOR (10 downto 0);
        din110 : IN STD_LOGIC_VECTOR (10 downto 0);
        din111 : IN STD_LOGIC_VECTOR (10 downto 0);
        din112 : IN STD_LOGIC_VECTOR (10 downto 0);
        din113 : IN STD_LOGIC_VECTOR (10 downto 0);
        din114 : IN STD_LOGIC_VECTOR (10 downto 0);
        din115 : IN STD_LOGIC_VECTOR (10 downto 0);
        din116 : IN STD_LOGIC_VECTOR (10 downto 0);
        din117 : IN STD_LOGIC_VECTOR (10 downto 0);
        din118 : IN STD_LOGIC_VECTOR (10 downto 0);
        din119 : IN STD_LOGIC_VECTOR (10 downto 0);
        din120 : IN STD_LOGIC_VECTOR (10 downto 0);
        din121 : IN STD_LOGIC_VECTOR (10 downto 0);
        din122 : IN STD_LOGIC_VECTOR (10 downto 0);
        din123 : IN STD_LOGIC_VECTOR (10 downto 0);
        din124 : IN STD_LOGIC_VECTOR (10 downto 0);
        din125 : IN STD_LOGIC_VECTOR (10 downto 0);
        din126 : IN STD_LOGIC_VECTOR (10 downto 0);
        din127 : IN STD_LOGIC_VECTOR (10 downto 0);
        def : IN STD_LOGIC_VECTOR (10 downto 0);
        sel : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component bnn_sparsemux_9_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component bnn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_257_7_11_1_1_U206 : component bnn_sparsemux_257_7_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000000",
        din0_WIDTH => 11,
        CASE1 => "0000001",
        din1_WIDTH => 11,
        CASE2 => "0000010",
        din2_WIDTH => 11,
        CASE3 => "0000011",
        din3_WIDTH => 11,
        CASE4 => "0000100",
        din4_WIDTH => 11,
        CASE5 => "0000101",
        din5_WIDTH => 11,
        CASE6 => "0000110",
        din6_WIDTH => 11,
        CASE7 => "0000111",
        din7_WIDTH => 11,
        CASE8 => "0001000",
        din8_WIDTH => 11,
        CASE9 => "0001001",
        din9_WIDTH => 11,
        CASE10 => "0001010",
        din10_WIDTH => 11,
        CASE11 => "0001011",
        din11_WIDTH => 11,
        CASE12 => "0001100",
        din12_WIDTH => 11,
        CASE13 => "0001101",
        din13_WIDTH => 11,
        CASE14 => "0001110",
        din14_WIDTH => 11,
        CASE15 => "0001111",
        din15_WIDTH => 11,
        CASE16 => "0010000",
        din16_WIDTH => 11,
        CASE17 => "0010001",
        din17_WIDTH => 11,
        CASE18 => "0010010",
        din18_WIDTH => 11,
        CASE19 => "0010011",
        din19_WIDTH => 11,
        CASE20 => "0010100",
        din20_WIDTH => 11,
        CASE21 => "0010101",
        din21_WIDTH => 11,
        CASE22 => "0010110",
        din22_WIDTH => 11,
        CASE23 => "0010111",
        din23_WIDTH => 11,
        CASE24 => "0011000",
        din24_WIDTH => 11,
        CASE25 => "0011001",
        din25_WIDTH => 11,
        CASE26 => "0011010",
        din26_WIDTH => 11,
        CASE27 => "0011011",
        din27_WIDTH => 11,
        CASE28 => "0011100",
        din28_WIDTH => 11,
        CASE29 => "0011101",
        din29_WIDTH => 11,
        CASE30 => "0011110",
        din30_WIDTH => 11,
        CASE31 => "0011111",
        din31_WIDTH => 11,
        CASE32 => "0100000",
        din32_WIDTH => 11,
        CASE33 => "0100001",
        din33_WIDTH => 11,
        CASE34 => "0100010",
        din34_WIDTH => 11,
        CASE35 => "0100011",
        din35_WIDTH => 11,
        CASE36 => "0100100",
        din36_WIDTH => 11,
        CASE37 => "0100101",
        din37_WIDTH => 11,
        CASE38 => "0100110",
        din38_WIDTH => 11,
        CASE39 => "0100111",
        din39_WIDTH => 11,
        CASE40 => "0101000",
        din40_WIDTH => 11,
        CASE41 => "0101001",
        din41_WIDTH => 11,
        CASE42 => "0101010",
        din42_WIDTH => 11,
        CASE43 => "0101011",
        din43_WIDTH => 11,
        CASE44 => "0101100",
        din44_WIDTH => 11,
        CASE45 => "0101101",
        din45_WIDTH => 11,
        CASE46 => "0101110",
        din46_WIDTH => 11,
        CASE47 => "0101111",
        din47_WIDTH => 11,
        CASE48 => "0110000",
        din48_WIDTH => 11,
        CASE49 => "0110001",
        din49_WIDTH => 11,
        CASE50 => "0110010",
        din50_WIDTH => 11,
        CASE51 => "0110011",
        din51_WIDTH => 11,
        CASE52 => "0110100",
        din52_WIDTH => 11,
        CASE53 => "0110101",
        din53_WIDTH => 11,
        CASE54 => "0110110",
        din54_WIDTH => 11,
        CASE55 => "0110111",
        din55_WIDTH => 11,
        CASE56 => "0111000",
        din56_WIDTH => 11,
        CASE57 => "0111001",
        din57_WIDTH => 11,
        CASE58 => "0111010",
        din58_WIDTH => 11,
        CASE59 => "0111011",
        din59_WIDTH => 11,
        CASE60 => "0111100",
        din60_WIDTH => 11,
        CASE61 => "0111101",
        din61_WIDTH => 11,
        CASE62 => "0111110",
        din62_WIDTH => 11,
        CASE63 => "0111111",
        din63_WIDTH => 11,
        CASE64 => "1000000",
        din64_WIDTH => 11,
        CASE65 => "1000001",
        din65_WIDTH => 11,
        CASE66 => "1000010",
        din66_WIDTH => 11,
        CASE67 => "1000011",
        din67_WIDTH => 11,
        CASE68 => "1000100",
        din68_WIDTH => 11,
        CASE69 => "1000101",
        din69_WIDTH => 11,
        CASE70 => "1000110",
        din70_WIDTH => 11,
        CASE71 => "1000111",
        din71_WIDTH => 11,
        CASE72 => "1001000",
        din72_WIDTH => 11,
        CASE73 => "1001001",
        din73_WIDTH => 11,
        CASE74 => "1001010",
        din74_WIDTH => 11,
        CASE75 => "1001011",
        din75_WIDTH => 11,
        CASE76 => "1001100",
        din76_WIDTH => 11,
        CASE77 => "1001101",
        din77_WIDTH => 11,
        CASE78 => "1001110",
        din78_WIDTH => 11,
        CASE79 => "1001111",
        din79_WIDTH => 11,
        CASE80 => "1010000",
        din80_WIDTH => 11,
        CASE81 => "1010001",
        din81_WIDTH => 11,
        CASE82 => "1010010",
        din82_WIDTH => 11,
        CASE83 => "1010011",
        din83_WIDTH => 11,
        CASE84 => "1010100",
        din84_WIDTH => 11,
        CASE85 => "1010101",
        din85_WIDTH => 11,
        CASE86 => "1010110",
        din86_WIDTH => 11,
        CASE87 => "1010111",
        din87_WIDTH => 11,
        CASE88 => "1011000",
        din88_WIDTH => 11,
        CASE89 => "1011001",
        din89_WIDTH => 11,
        CASE90 => "1011010",
        din90_WIDTH => 11,
        CASE91 => "1011011",
        din91_WIDTH => 11,
        CASE92 => "1011100",
        din92_WIDTH => 11,
        CASE93 => "1011101",
        din93_WIDTH => 11,
        CASE94 => "1011110",
        din94_WIDTH => 11,
        CASE95 => "1011111",
        din95_WIDTH => 11,
        CASE96 => "1100000",
        din96_WIDTH => 11,
        CASE97 => "1100001",
        din97_WIDTH => 11,
        CASE98 => "1100010",
        din98_WIDTH => 11,
        CASE99 => "1100011",
        din99_WIDTH => 11,
        CASE100 => "1100100",
        din100_WIDTH => 11,
        CASE101 => "1100101",
        din101_WIDTH => 11,
        CASE102 => "1100110",
        din102_WIDTH => 11,
        CASE103 => "1100111",
        din103_WIDTH => 11,
        CASE104 => "1101000",
        din104_WIDTH => 11,
        CASE105 => "1101001",
        din105_WIDTH => 11,
        CASE106 => "1101010",
        din106_WIDTH => 11,
        CASE107 => "1101011",
        din107_WIDTH => 11,
        CASE108 => "1101100",
        din108_WIDTH => 11,
        CASE109 => "1101101",
        din109_WIDTH => 11,
        CASE110 => "1101110",
        din110_WIDTH => 11,
        CASE111 => "1101111",
        din111_WIDTH => 11,
        CASE112 => "1110000",
        din112_WIDTH => 11,
        CASE113 => "1110001",
        din113_WIDTH => 11,
        CASE114 => "1110010",
        din114_WIDTH => 11,
        CASE115 => "1110011",
        din115_WIDTH => 11,
        CASE116 => "1110100",
        din116_WIDTH => 11,
        CASE117 => "1110101",
        din117_WIDTH => 11,
        CASE118 => "1110110",
        din118_WIDTH => 11,
        CASE119 => "1110111",
        din119_WIDTH => 11,
        CASE120 => "1111000",
        din120_WIDTH => 11,
        CASE121 => "1111001",
        din121_WIDTH => 11,
        CASE122 => "1111010",
        din122_WIDTH => 11,
        CASE123 => "1111011",
        din123_WIDTH => 11,
        CASE124 => "1111100",
        din124_WIDTH => 11,
        CASE125 => "1111101",
        din125_WIDTH => 11,
        CASE126 => "1111110",
        din126_WIDTH => 11,
        CASE127 => "1111111",
        din127_WIDTH => 11,
        def_WIDTH => 11,
        sel_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => input_0_val,
        din1 => input_1_val,
        din2 => input_2_val,
        din3 => input_3_val,
        din4 => input_4_val,
        din5 => input_5_val,
        din6 => input_6_val,
        din7 => input_7_val,
        din8 => input_8_val,
        din9 => input_9_val,
        din10 => input_10_val,
        din11 => input_11_val,
        din12 => input_12_val,
        din13 => input_13_val,
        din14 => input_14_val,
        din15 => input_15_val,
        din16 => input_16_val,
        din17 => input_17_val,
        din18 => input_18_val,
        din19 => input_19_val,
        din20 => input_20_val,
        din21 => input_21_val,
        din22 => input_22_val,
        din23 => input_23_val,
        din24 => input_24_val,
        din25 => input_25_val,
        din26 => input_26_val,
        din27 => input_27_val,
        din28 => input_28_val,
        din29 => input_29_val,
        din30 => input_30_val,
        din31 => input_31_val,
        din32 => input_32_val,
        din33 => input_33_val,
        din34 => input_34_val,
        din35 => input_35_val,
        din36 => input_36_val,
        din37 => input_37_val,
        din38 => input_38_val,
        din39 => input_39_val,
        din40 => input_40_val,
        din41 => input_41_val,
        din42 => input_42_val,
        din43 => input_43_val,
        din44 => input_44_val,
        din45 => input_45_val,
        din46 => input_46_val,
        din47 => input_47_val,
        din48 => input_48_val,
        din49 => input_49_val,
        din50 => input_50_val,
        din51 => input_51_val,
        din52 => input_52_val,
        din53 => input_53_val,
        din54 => input_54_val,
        din55 => input_55_val,
        din56 => input_56_val,
        din57 => input_57_val,
        din58 => input_58_val,
        din59 => input_59_val,
        din60 => input_60_val,
        din61 => input_61_val,
        din62 => input_62_val,
        din63 => input_63_val,
        din64 => input_64_val,
        din65 => input_65_val,
        din66 => input_66_val,
        din67 => input_67_val,
        din68 => input_68_val,
        din69 => input_69_val,
        din70 => input_70_val,
        din71 => input_71_val,
        din72 => input_72_val,
        din73 => input_73_val,
        din74 => input_74_val,
        din75 => input_75_val,
        din76 => input_76_val,
        din77 => input_77_val,
        din78 => input_78_val,
        din79 => input_79_val,
        din80 => input_80_val,
        din81 => input_81_val,
        din82 => input_82_val,
        din83 => input_83_val,
        din84 => input_84_val,
        din85 => input_85_val,
        din86 => input_86_val,
        din87 => input_87_val,
        din88 => input_88_val,
        din89 => input_89_val,
        din90 => input_90_val,
        din91 => input_91_val,
        din92 => input_92_val,
        din93 => input_93_val,
        din94 => input_94_val,
        din95 => input_95_val,
        din96 => input_96_val,
        din97 => input_97_val,
        din98 => input_98_val,
        din99 => input_99_val,
        din100 => input_100_val,
        din101 => input_101_val,
        din102 => input_102_val,
        din103 => input_103_val,
        din104 => input_104_val,
        din105 => input_105_val,
        din106 => input_106_val,
        din107 => input_107_val,
        din108 => input_108_val,
        din109 => input_109_val,
        din110 => input_110_val,
        din111 => input_111_val,
        din112 => input_112_val,
        din113 => input_113_val,
        din114 => input_114_val,
        din115 => input_115_val,
        din116 => input_116_val,
        din117 => input_117_val,
        din118 => input_118_val,
        din119 => input_119_val,
        din120 => input_120_val,
        din121 => input_121_val,
        din122 => input_122_val,
        din123 => input_123_val,
        din124 => input_124_val,
        din125 => input_125_val,
        din126 => input_126_val,
        din127 => input_127_val,
        def => tmp_fu_1398_p257,
        sel => tmp_fu_1398_p258,
        dout => tmp_fu_1398_p259);

    sparsemux_9_2_32_1_1_U207 : component bnn_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => or3_fu_570,
        din1 => or6_fu_574,
        din2 => or9_fu_578,
        din3 => or12_fu_582,
        def => tmp_2_fu_1968_p9,
        sel => tmp_2_fu_1968_p10,
        dout => tmp_2_fu_1968_p11);

    flow_control_loop_pipe_sequential_init_U : component bnn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_566_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln85_fu_1382_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_566 <= add_ln85_fu_1388_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_566 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    or12_fu_582_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    or12_fu_582 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    or12_fu_582 <= or10_fu_2040_p3;
                end if;
            end if; 
        end if;
    end process;

    or3_fu_570_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    or3_fu_570 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    or3_fu_570 <= or1_fu_2082_p3;
                end if;
            end if; 
        end if;
    end process;

    or6_fu_574_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    or6_fu_574 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    or6_fu_574 <= or4_fu_2068_p3;
                end if;
            end if; 
        end if;
    end process;

    or9_fu_578_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    or9_fu_578 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    or9_fu_578 <= or7_fu_2054_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                i_2_reg_2185 <= ap_sig_allocacmp_i_2;
                tmp_reg_2194 <= tmp_fu_1398_p259;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln85_fu_1388_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv8_1));
    and_ln92_1_fu_2062_p2 <= (icmp_ln92_1_fu_2004_p2 and icmp_ln91_fu_1957_p2);
    and_ln92_2_fu_2076_p2 <= (icmp_ln92_fu_1998_p2 and icmp_ln91_fu_1957_p2);
    and_ln92_fu_2048_p2 <= (icmp_ln92_2_fu_2010_p2 and icmp_ln91_fu_1957_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln85_fu_1382_p2)
    begin
        if (((icmp_ln85_fu_1382_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= ap_sig_allocacmp_or3_load;
    ap_return_1 <= ap_sig_allocacmp_or6_load;
    ap_return_2 <= ap_sig_allocacmp_or9_load;
    ap_return_3 <= ap_sig_allocacmp_or12_load;

    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_pp0_stage0, i_fu_566, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_566;
        end if; 
    end process;


    ap_sig_allocacmp_or12_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_loop_init, ap_block_pp0_stage0, or12_fu_582, or10_fu_2040_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_or12_load <= ap_const_lv32_0;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_or12_load <= or10_fu_2040_p3;
            else 
                ap_sig_allocacmp_or12_load <= or12_fu_582;
            end if;
        else 
            ap_sig_allocacmp_or12_load <= or12_fu_582;
        end if; 
    end process;


    ap_sig_allocacmp_or3_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_loop_init, ap_block_pp0_stage0, or3_fu_570, or1_fu_2082_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_or3_load <= ap_const_lv32_0;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_or3_load <= or1_fu_2082_p3;
            else 
                ap_sig_allocacmp_or3_load <= or3_fu_570;
            end if;
        else 
            ap_sig_allocacmp_or3_load <= or3_fu_570;
        end if; 
    end process;


    ap_sig_allocacmp_or6_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_loop_init, ap_block_pp0_stage0, or6_fu_574, or4_fu_2068_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_or6_load <= ap_const_lv32_0;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_or6_load <= or4_fu_2068_p3;
            else 
                ap_sig_allocacmp_or6_load <= or6_fu_574;
            end if;
        else 
            ap_sig_allocacmp_or6_load <= or6_fu_574;
        end if; 
    end process;


    ap_sig_allocacmp_or9_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_loop_init, ap_block_pp0_stage0, or9_fu_578, or7_fu_2054_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_or9_load <= ap_const_lv32_0;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_or9_load <= or7_fu_2054_p3;
            else 
                ap_sig_allocacmp_or9_load <= or9_fu_578;
            end if;
        else 
            ap_sig_allocacmp_or9_load <= or9_fu_578;
        end if; 
    end process;

    bit_pos_fu_1947_p2 <= (trunc_ln88_fu_1935_p1 xor ap_const_lv5_1F);
    icmp_ln85_fu_1382_p2 <= "1" when (ap_sig_allocacmp_i_2 = ap_const_lv8_80) else "0";
    icmp_ln91_fu_1957_p2 <= "1" when (signed(tmp_reg_2194) < signed(ap_const_lv11_1)) else "0";
    icmp_ln92_1_fu_2004_p2 <= "1" when (trunc_ln88_4_fu_1938_p4 = ap_const_lv2_1) else "0";
    icmp_ln92_2_fu_2010_p2 <= "1" when (trunc_ln88_4_fu_1938_p4 = ap_const_lv2_2) else "0";
    icmp_ln92_fu_1998_p2 <= "1" when (trunc_ln88_4_fu_1938_p4 = ap_const_lv2_0) else "0";
    or10_fu_2040_p3 <= 
        or12_fu_582 when (or_ln92_3_fu_2034_p2(0) = '1') else 
        or_ln92_fu_1992_p2;
    or1_fu_2082_p3 <= 
        or_ln92_fu_1992_p2 when (and_ln92_2_fu_2076_p2(0) = '1') else 
        or3_fu_570;
    or4_fu_2068_p3 <= 
        or_ln92_fu_1992_p2 when (and_ln92_1_fu_2062_p2(0) = '1') else 
        or6_fu_574;
    or7_fu_2054_p3 <= 
        or_ln92_fu_1992_p2 when (and_ln92_fu_2048_p2(0) = '1') else 
        or9_fu_578;
    or_ln92_1_fu_2028_p2 <= (or_ln92_2_fu_2022_p2 or icmp_ln92_fu_1998_p2);
    or_ln92_2_fu_2022_p2 <= (icmp_ln92_2_fu_2010_p2 or icmp_ln92_1_fu_2004_p2);
    or_ln92_3_fu_2034_p2 <= (xor_ln91_fu_2016_p2 or or_ln92_1_fu_2028_p2);
    or_ln92_fu_1992_p2 <= (tmp_2_fu_1968_p11 or shl_ln92_fu_1962_p2);
    shl_ln92_fu_1962_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv32_1),to_integer(unsigned('0' & zext_ln89_fu_1953_p1(31-1 downto 0)))));
    tmp_2_fu_1968_p10 <= i_2_reg_2185(6 downto 5);
    tmp_2_fu_1968_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_fu_1398_p257 <= "XXXXXXXXXXX";
    tmp_fu_1398_p258 <= ap_sig_allocacmp_i_2(7 - 1 downto 0);
    trunc_ln88_4_fu_1938_p4 <= i_2_reg_2185(6 downto 5);
    trunc_ln88_fu_1935_p1 <= i_2_reg_2185(5 - 1 downto 0);
    xor_ln91_fu_2016_p2 <= (icmp_ln91_fu_1957_p2 xor ap_const_lv1_1);
    zext_ln89_fu_1953_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bit_pos_fu_1947_p2),32));
end behav;
