// ==============================================================
// Generated by Vitis HLS v2024.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bnn_sign_and_quantize (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_0_val,
        input_1_val,
        input_2_val,
        input_3_val,
        input_4_val,
        input_5_val,
        input_6_val,
        input_7_val,
        input_8_val,
        input_9_val,
        input_10_val,
        input_11_val,
        input_12_val,
        input_13_val,
        input_14_val,
        input_15_val,
        input_16_val,
        input_17_val,
        input_18_val,
        input_19_val,
        input_20_val,
        input_21_val,
        input_22_val,
        input_23_val,
        input_24_val,
        input_25_val,
        input_26_val,
        input_27_val,
        input_28_val,
        input_29_val,
        input_30_val,
        input_31_val,
        input_32_val,
        input_33_val,
        input_34_val,
        input_35_val,
        input_36_val,
        input_37_val,
        input_38_val,
        input_39_val,
        input_40_val,
        input_41_val,
        input_42_val,
        input_43_val,
        input_44_val,
        input_45_val,
        input_46_val,
        input_47_val,
        input_48_val,
        input_49_val,
        input_50_val,
        input_51_val,
        input_52_val,
        input_53_val,
        input_54_val,
        input_55_val,
        input_56_val,
        input_57_val,
        input_58_val,
        input_59_val,
        input_60_val,
        input_61_val,
        input_62_val,
        input_63_val,
        input_64_val,
        input_65_val,
        input_66_val,
        input_67_val,
        input_68_val,
        input_69_val,
        input_70_val,
        input_71_val,
        input_72_val,
        input_73_val,
        input_74_val,
        input_75_val,
        input_76_val,
        input_77_val,
        input_78_val,
        input_79_val,
        input_80_val,
        input_81_val,
        input_82_val,
        input_83_val,
        input_84_val,
        input_85_val,
        input_86_val,
        input_87_val,
        input_88_val,
        input_89_val,
        input_90_val,
        input_91_val,
        input_92_val,
        input_93_val,
        input_94_val,
        input_95_val,
        input_96_val,
        input_97_val,
        input_98_val,
        input_99_val,
        input_100_val,
        input_101_val,
        input_102_val,
        input_103_val,
        input_104_val,
        input_105_val,
        input_106_val,
        input_107_val,
        input_108_val,
        input_109_val,
        input_110_val,
        input_111_val,
        input_112_val,
        input_113_val,
        input_114_val,
        input_115_val,
        input_116_val,
        input_117_val,
        input_118_val,
        input_119_val,
        input_120_val,
        input_121_val,
        input_122_val,
        input_123_val,
        input_124_val,
        input_125_val,
        input_126_val,
        input_127_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [10:0] input_0_val;
input  [10:0] input_1_val;
input  [10:0] input_2_val;
input  [10:0] input_3_val;
input  [10:0] input_4_val;
input  [10:0] input_5_val;
input  [10:0] input_6_val;
input  [10:0] input_7_val;
input  [10:0] input_8_val;
input  [10:0] input_9_val;
input  [10:0] input_10_val;
input  [10:0] input_11_val;
input  [10:0] input_12_val;
input  [10:0] input_13_val;
input  [10:0] input_14_val;
input  [10:0] input_15_val;
input  [10:0] input_16_val;
input  [10:0] input_17_val;
input  [10:0] input_18_val;
input  [10:0] input_19_val;
input  [10:0] input_20_val;
input  [10:0] input_21_val;
input  [10:0] input_22_val;
input  [10:0] input_23_val;
input  [10:0] input_24_val;
input  [10:0] input_25_val;
input  [10:0] input_26_val;
input  [10:0] input_27_val;
input  [10:0] input_28_val;
input  [10:0] input_29_val;
input  [10:0] input_30_val;
input  [10:0] input_31_val;
input  [10:0] input_32_val;
input  [10:0] input_33_val;
input  [10:0] input_34_val;
input  [10:0] input_35_val;
input  [10:0] input_36_val;
input  [10:0] input_37_val;
input  [10:0] input_38_val;
input  [10:0] input_39_val;
input  [10:0] input_40_val;
input  [10:0] input_41_val;
input  [10:0] input_42_val;
input  [10:0] input_43_val;
input  [10:0] input_44_val;
input  [10:0] input_45_val;
input  [10:0] input_46_val;
input  [10:0] input_47_val;
input  [10:0] input_48_val;
input  [10:0] input_49_val;
input  [10:0] input_50_val;
input  [10:0] input_51_val;
input  [10:0] input_52_val;
input  [10:0] input_53_val;
input  [10:0] input_54_val;
input  [10:0] input_55_val;
input  [10:0] input_56_val;
input  [10:0] input_57_val;
input  [10:0] input_58_val;
input  [10:0] input_59_val;
input  [10:0] input_60_val;
input  [10:0] input_61_val;
input  [10:0] input_62_val;
input  [10:0] input_63_val;
input  [10:0] input_64_val;
input  [10:0] input_65_val;
input  [10:0] input_66_val;
input  [10:0] input_67_val;
input  [10:0] input_68_val;
input  [10:0] input_69_val;
input  [10:0] input_70_val;
input  [10:0] input_71_val;
input  [10:0] input_72_val;
input  [10:0] input_73_val;
input  [10:0] input_74_val;
input  [10:0] input_75_val;
input  [10:0] input_76_val;
input  [10:0] input_77_val;
input  [10:0] input_78_val;
input  [10:0] input_79_val;
input  [10:0] input_80_val;
input  [10:0] input_81_val;
input  [10:0] input_82_val;
input  [10:0] input_83_val;
input  [10:0] input_84_val;
input  [10:0] input_85_val;
input  [10:0] input_86_val;
input  [10:0] input_87_val;
input  [10:0] input_88_val;
input  [10:0] input_89_val;
input  [10:0] input_90_val;
input  [10:0] input_91_val;
input  [10:0] input_92_val;
input  [10:0] input_93_val;
input  [10:0] input_94_val;
input  [10:0] input_95_val;
input  [10:0] input_96_val;
input  [10:0] input_97_val;
input  [10:0] input_98_val;
input  [10:0] input_99_val;
input  [10:0] input_100_val;
input  [10:0] input_101_val;
input  [10:0] input_102_val;
input  [10:0] input_103_val;
input  [10:0] input_104_val;
input  [10:0] input_105_val;
input  [10:0] input_106_val;
input  [10:0] input_107_val;
input  [10:0] input_108_val;
input  [10:0] input_109_val;
input  [10:0] input_110_val;
input  [10:0] input_111_val;
input  [10:0] input_112_val;
input  [10:0] input_113_val;
input  [10:0] input_114_val;
input  [10:0] input_115_val;
input  [10:0] input_116_val;
input  [10:0] input_117_val;
input  [10:0] input_118_val;
input  [10:0] input_119_val;
input  [10:0] input_120_val;
input  [10:0] input_121_val;
input  [10:0] input_122_val;
input  [10:0] input_123_val;
input  [10:0] input_124_val;
input  [10:0] input_125_val;
input  [10:0] input_126_val;
input  [10:0] input_127_val;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln85_fu_1382_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [7:0] i_2_reg_2185;
wire    ap_block_pp0_stage0_11001;
wire   [10:0] tmp_fu_1398_p259;
reg   [10:0] tmp_reg_2194;
reg   [7:0] i_fu_566;
wire   [7:0] add_ln85_fu_1388_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i_2;
wire    ap_block_pp0_stage0;
reg   [31:0] or3_fu_570;
wire   [31:0] or1_fu_2082_p3;
reg   [31:0] ap_sig_allocacmp_or3_load;
reg   [31:0] or6_fu_574;
wire   [31:0] or4_fu_2068_p3;
reg   [31:0] ap_sig_allocacmp_or6_load;
reg   [31:0] or9_fu_578;
wire   [31:0] or7_fu_2054_p3;
reg   [31:0] ap_sig_allocacmp_or9_load;
reg   [31:0] or12_fu_582;
wire   [31:0] or10_fu_2040_p3;
reg   [31:0] ap_sig_allocacmp_or12_load;
wire   [10:0] tmp_fu_1398_p257;
wire   [6:0] tmp_fu_1398_p258;
wire   [4:0] trunc_ln88_fu_1935_p1;
wire   [4:0] bit_pos_fu_1947_p2;
wire   [31:0] zext_ln89_fu_1953_p1;
wire   [31:0] tmp_2_fu_1968_p9;
wire   [1:0] tmp_2_fu_1968_p10;
wire   [1:0] trunc_ln88_4_fu_1938_p4;
wire   [31:0] tmp_2_fu_1968_p11;
wire   [31:0] shl_ln92_fu_1962_p2;
wire   [0:0] icmp_ln91_fu_1957_p2;
wire   [0:0] icmp_ln92_1_fu_2004_p2;
wire   [0:0] icmp_ln92_2_fu_2010_p2;
wire   [0:0] or_ln92_2_fu_2022_p2;
wire   [0:0] icmp_ln92_fu_1998_p2;
wire   [0:0] or_ln92_1_fu_2028_p2;
wire   [0:0] xor_ln91_fu_2016_p2;
wire   [0:0] or_ln92_3_fu_2034_p2;
wire   [31:0] or_ln92_fu_1992_p2;
wire   [0:0] and_ln92_fu_2048_p2;
wire   [0:0] and_ln92_1_fu_2062_p2;
wire   [0:0] and_ln92_2_fu_2076_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [6:0] tmp_fu_1398_p1;
wire   [6:0] tmp_fu_1398_p3;
wire   [6:0] tmp_fu_1398_p5;
wire   [6:0] tmp_fu_1398_p7;
wire   [6:0] tmp_fu_1398_p9;
wire   [6:0] tmp_fu_1398_p11;
wire   [6:0] tmp_fu_1398_p13;
wire   [6:0] tmp_fu_1398_p15;
wire   [6:0] tmp_fu_1398_p17;
wire   [6:0] tmp_fu_1398_p19;
wire   [6:0] tmp_fu_1398_p21;
wire   [6:0] tmp_fu_1398_p23;
wire   [6:0] tmp_fu_1398_p25;
wire   [6:0] tmp_fu_1398_p27;
wire   [6:0] tmp_fu_1398_p29;
wire   [6:0] tmp_fu_1398_p31;
wire   [6:0] tmp_fu_1398_p33;
wire   [6:0] tmp_fu_1398_p35;
wire   [6:0] tmp_fu_1398_p37;
wire   [6:0] tmp_fu_1398_p39;
wire   [6:0] tmp_fu_1398_p41;
wire   [6:0] tmp_fu_1398_p43;
wire   [6:0] tmp_fu_1398_p45;
wire   [6:0] tmp_fu_1398_p47;
wire   [6:0] tmp_fu_1398_p49;
wire   [6:0] tmp_fu_1398_p51;
wire   [6:0] tmp_fu_1398_p53;
wire   [6:0] tmp_fu_1398_p55;
wire   [6:0] tmp_fu_1398_p57;
wire   [6:0] tmp_fu_1398_p59;
wire   [6:0] tmp_fu_1398_p61;
wire   [6:0] tmp_fu_1398_p63;
wire   [6:0] tmp_fu_1398_p65;
wire   [6:0] tmp_fu_1398_p67;
wire   [6:0] tmp_fu_1398_p69;
wire   [6:0] tmp_fu_1398_p71;
wire   [6:0] tmp_fu_1398_p73;
wire   [6:0] tmp_fu_1398_p75;
wire   [6:0] tmp_fu_1398_p77;
wire   [6:0] tmp_fu_1398_p79;
wire   [6:0] tmp_fu_1398_p81;
wire   [6:0] tmp_fu_1398_p83;
wire   [6:0] tmp_fu_1398_p85;
wire   [6:0] tmp_fu_1398_p87;
wire   [6:0] tmp_fu_1398_p89;
wire   [6:0] tmp_fu_1398_p91;
wire   [6:0] tmp_fu_1398_p93;
wire   [6:0] tmp_fu_1398_p95;
wire   [6:0] tmp_fu_1398_p97;
wire   [6:0] tmp_fu_1398_p99;
wire   [6:0] tmp_fu_1398_p101;
wire   [6:0] tmp_fu_1398_p103;
wire   [6:0] tmp_fu_1398_p105;
wire   [6:0] tmp_fu_1398_p107;
wire   [6:0] tmp_fu_1398_p109;
wire   [6:0] tmp_fu_1398_p111;
wire   [6:0] tmp_fu_1398_p113;
wire   [6:0] tmp_fu_1398_p115;
wire   [6:0] tmp_fu_1398_p117;
wire   [6:0] tmp_fu_1398_p119;
wire   [6:0] tmp_fu_1398_p121;
wire   [6:0] tmp_fu_1398_p123;
wire   [6:0] tmp_fu_1398_p125;
wire   [6:0] tmp_fu_1398_p127;
wire  signed [6:0] tmp_fu_1398_p129;
wire  signed [6:0] tmp_fu_1398_p131;
wire  signed [6:0] tmp_fu_1398_p133;
wire  signed [6:0] tmp_fu_1398_p135;
wire  signed [6:0] tmp_fu_1398_p137;
wire  signed [6:0] tmp_fu_1398_p139;
wire  signed [6:0] tmp_fu_1398_p141;
wire  signed [6:0] tmp_fu_1398_p143;
wire  signed [6:0] tmp_fu_1398_p145;
wire  signed [6:0] tmp_fu_1398_p147;
wire  signed [6:0] tmp_fu_1398_p149;
wire  signed [6:0] tmp_fu_1398_p151;
wire  signed [6:0] tmp_fu_1398_p153;
wire  signed [6:0] tmp_fu_1398_p155;
wire  signed [6:0] tmp_fu_1398_p157;
wire  signed [6:0] tmp_fu_1398_p159;
wire  signed [6:0] tmp_fu_1398_p161;
wire  signed [6:0] tmp_fu_1398_p163;
wire  signed [6:0] tmp_fu_1398_p165;
wire  signed [6:0] tmp_fu_1398_p167;
wire  signed [6:0] tmp_fu_1398_p169;
wire  signed [6:0] tmp_fu_1398_p171;
wire  signed [6:0] tmp_fu_1398_p173;
wire  signed [6:0] tmp_fu_1398_p175;
wire  signed [6:0] tmp_fu_1398_p177;
wire  signed [6:0] tmp_fu_1398_p179;
wire  signed [6:0] tmp_fu_1398_p181;
wire  signed [6:0] tmp_fu_1398_p183;
wire  signed [6:0] tmp_fu_1398_p185;
wire  signed [6:0] tmp_fu_1398_p187;
wire  signed [6:0] tmp_fu_1398_p189;
wire  signed [6:0] tmp_fu_1398_p191;
wire  signed [6:0] tmp_fu_1398_p193;
wire  signed [6:0] tmp_fu_1398_p195;
wire  signed [6:0] tmp_fu_1398_p197;
wire  signed [6:0] tmp_fu_1398_p199;
wire  signed [6:0] tmp_fu_1398_p201;
wire  signed [6:0] tmp_fu_1398_p203;
wire  signed [6:0] tmp_fu_1398_p205;
wire  signed [6:0] tmp_fu_1398_p207;
wire  signed [6:0] tmp_fu_1398_p209;
wire  signed [6:0] tmp_fu_1398_p211;
wire  signed [6:0] tmp_fu_1398_p213;
wire  signed [6:0] tmp_fu_1398_p215;
wire  signed [6:0] tmp_fu_1398_p217;
wire  signed [6:0] tmp_fu_1398_p219;
wire  signed [6:0] tmp_fu_1398_p221;
wire  signed [6:0] tmp_fu_1398_p223;
wire  signed [6:0] tmp_fu_1398_p225;
wire  signed [6:0] tmp_fu_1398_p227;
wire  signed [6:0] tmp_fu_1398_p229;
wire  signed [6:0] tmp_fu_1398_p231;
wire  signed [6:0] tmp_fu_1398_p233;
wire  signed [6:0] tmp_fu_1398_p235;
wire  signed [6:0] tmp_fu_1398_p237;
wire  signed [6:0] tmp_fu_1398_p239;
wire  signed [6:0] tmp_fu_1398_p241;
wire  signed [6:0] tmp_fu_1398_p243;
wire  signed [6:0] tmp_fu_1398_p245;
wire  signed [6:0] tmp_fu_1398_p247;
wire  signed [6:0] tmp_fu_1398_p249;
wire  signed [6:0] tmp_fu_1398_p251;
wire  signed [6:0] tmp_fu_1398_p253;
wire  signed [6:0] tmp_fu_1398_p255;
wire   [1:0] tmp_2_fu_1968_p1;
wire   [1:0] tmp_2_fu_1968_p3;
wire  signed [1:0] tmp_2_fu_1968_p5;
wire  signed [1:0] tmp_2_fu_1968_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_fu_566 = 8'd0;
#0 or3_fu_570 = 32'd0;
#0 or6_fu_574 = 32'd0;
#0 or9_fu_578 = 32'd0;
#0 or12_fu_582 = 32'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_257_7_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 7'h0 ),
    .din0_WIDTH( 11 ),
    .CASE1( 7'h1 ),
    .din1_WIDTH( 11 ),
    .CASE2( 7'h2 ),
    .din2_WIDTH( 11 ),
    .CASE3( 7'h3 ),
    .din3_WIDTH( 11 ),
    .CASE4( 7'h4 ),
    .din4_WIDTH( 11 ),
    .CASE5( 7'h5 ),
    .din5_WIDTH( 11 ),
    .CASE6( 7'h6 ),
    .din6_WIDTH( 11 ),
    .CASE7( 7'h7 ),
    .din7_WIDTH( 11 ),
    .CASE8( 7'h8 ),
    .din8_WIDTH( 11 ),
    .CASE9( 7'h9 ),
    .din9_WIDTH( 11 ),
    .CASE10( 7'hA ),
    .din10_WIDTH( 11 ),
    .CASE11( 7'hB ),
    .din11_WIDTH( 11 ),
    .CASE12( 7'hC ),
    .din12_WIDTH( 11 ),
    .CASE13( 7'hD ),
    .din13_WIDTH( 11 ),
    .CASE14( 7'hE ),
    .din14_WIDTH( 11 ),
    .CASE15( 7'hF ),
    .din15_WIDTH( 11 ),
    .CASE16( 7'h10 ),
    .din16_WIDTH( 11 ),
    .CASE17( 7'h11 ),
    .din17_WIDTH( 11 ),
    .CASE18( 7'h12 ),
    .din18_WIDTH( 11 ),
    .CASE19( 7'h13 ),
    .din19_WIDTH( 11 ),
    .CASE20( 7'h14 ),
    .din20_WIDTH( 11 ),
    .CASE21( 7'h15 ),
    .din21_WIDTH( 11 ),
    .CASE22( 7'h16 ),
    .din22_WIDTH( 11 ),
    .CASE23( 7'h17 ),
    .din23_WIDTH( 11 ),
    .CASE24( 7'h18 ),
    .din24_WIDTH( 11 ),
    .CASE25( 7'h19 ),
    .din25_WIDTH( 11 ),
    .CASE26( 7'h1A ),
    .din26_WIDTH( 11 ),
    .CASE27( 7'h1B ),
    .din27_WIDTH( 11 ),
    .CASE28( 7'h1C ),
    .din28_WIDTH( 11 ),
    .CASE29( 7'h1D ),
    .din29_WIDTH( 11 ),
    .CASE30( 7'h1E ),
    .din30_WIDTH( 11 ),
    .CASE31( 7'h1F ),
    .din31_WIDTH( 11 ),
    .CASE32( 7'h20 ),
    .din32_WIDTH( 11 ),
    .CASE33( 7'h21 ),
    .din33_WIDTH( 11 ),
    .CASE34( 7'h22 ),
    .din34_WIDTH( 11 ),
    .CASE35( 7'h23 ),
    .din35_WIDTH( 11 ),
    .CASE36( 7'h24 ),
    .din36_WIDTH( 11 ),
    .CASE37( 7'h25 ),
    .din37_WIDTH( 11 ),
    .CASE38( 7'h26 ),
    .din38_WIDTH( 11 ),
    .CASE39( 7'h27 ),
    .din39_WIDTH( 11 ),
    .CASE40( 7'h28 ),
    .din40_WIDTH( 11 ),
    .CASE41( 7'h29 ),
    .din41_WIDTH( 11 ),
    .CASE42( 7'h2A ),
    .din42_WIDTH( 11 ),
    .CASE43( 7'h2B ),
    .din43_WIDTH( 11 ),
    .CASE44( 7'h2C ),
    .din44_WIDTH( 11 ),
    .CASE45( 7'h2D ),
    .din45_WIDTH( 11 ),
    .CASE46( 7'h2E ),
    .din46_WIDTH( 11 ),
    .CASE47( 7'h2F ),
    .din47_WIDTH( 11 ),
    .CASE48( 7'h30 ),
    .din48_WIDTH( 11 ),
    .CASE49( 7'h31 ),
    .din49_WIDTH( 11 ),
    .CASE50( 7'h32 ),
    .din50_WIDTH( 11 ),
    .CASE51( 7'h33 ),
    .din51_WIDTH( 11 ),
    .CASE52( 7'h34 ),
    .din52_WIDTH( 11 ),
    .CASE53( 7'h35 ),
    .din53_WIDTH( 11 ),
    .CASE54( 7'h36 ),
    .din54_WIDTH( 11 ),
    .CASE55( 7'h37 ),
    .din55_WIDTH( 11 ),
    .CASE56( 7'h38 ),
    .din56_WIDTH( 11 ),
    .CASE57( 7'h39 ),
    .din57_WIDTH( 11 ),
    .CASE58( 7'h3A ),
    .din58_WIDTH( 11 ),
    .CASE59( 7'h3B ),
    .din59_WIDTH( 11 ),
    .CASE60( 7'h3C ),
    .din60_WIDTH( 11 ),
    .CASE61( 7'h3D ),
    .din61_WIDTH( 11 ),
    .CASE62( 7'h3E ),
    .din62_WIDTH( 11 ),
    .CASE63( 7'h3F ),
    .din63_WIDTH( 11 ),
    .CASE64( 7'h40 ),
    .din64_WIDTH( 11 ),
    .CASE65( 7'h41 ),
    .din65_WIDTH( 11 ),
    .CASE66( 7'h42 ),
    .din66_WIDTH( 11 ),
    .CASE67( 7'h43 ),
    .din67_WIDTH( 11 ),
    .CASE68( 7'h44 ),
    .din68_WIDTH( 11 ),
    .CASE69( 7'h45 ),
    .din69_WIDTH( 11 ),
    .CASE70( 7'h46 ),
    .din70_WIDTH( 11 ),
    .CASE71( 7'h47 ),
    .din71_WIDTH( 11 ),
    .CASE72( 7'h48 ),
    .din72_WIDTH( 11 ),
    .CASE73( 7'h49 ),
    .din73_WIDTH( 11 ),
    .CASE74( 7'h4A ),
    .din74_WIDTH( 11 ),
    .CASE75( 7'h4B ),
    .din75_WIDTH( 11 ),
    .CASE76( 7'h4C ),
    .din76_WIDTH( 11 ),
    .CASE77( 7'h4D ),
    .din77_WIDTH( 11 ),
    .CASE78( 7'h4E ),
    .din78_WIDTH( 11 ),
    .CASE79( 7'h4F ),
    .din79_WIDTH( 11 ),
    .CASE80( 7'h50 ),
    .din80_WIDTH( 11 ),
    .CASE81( 7'h51 ),
    .din81_WIDTH( 11 ),
    .CASE82( 7'h52 ),
    .din82_WIDTH( 11 ),
    .CASE83( 7'h53 ),
    .din83_WIDTH( 11 ),
    .CASE84( 7'h54 ),
    .din84_WIDTH( 11 ),
    .CASE85( 7'h55 ),
    .din85_WIDTH( 11 ),
    .CASE86( 7'h56 ),
    .din86_WIDTH( 11 ),
    .CASE87( 7'h57 ),
    .din87_WIDTH( 11 ),
    .CASE88( 7'h58 ),
    .din88_WIDTH( 11 ),
    .CASE89( 7'h59 ),
    .din89_WIDTH( 11 ),
    .CASE90( 7'h5A ),
    .din90_WIDTH( 11 ),
    .CASE91( 7'h5B ),
    .din91_WIDTH( 11 ),
    .CASE92( 7'h5C ),
    .din92_WIDTH( 11 ),
    .CASE93( 7'h5D ),
    .din93_WIDTH( 11 ),
    .CASE94( 7'h5E ),
    .din94_WIDTH( 11 ),
    .CASE95( 7'h5F ),
    .din95_WIDTH( 11 ),
    .CASE96( 7'h60 ),
    .din96_WIDTH( 11 ),
    .CASE97( 7'h61 ),
    .din97_WIDTH( 11 ),
    .CASE98( 7'h62 ),
    .din98_WIDTH( 11 ),
    .CASE99( 7'h63 ),
    .din99_WIDTH( 11 ),
    .CASE100( 7'h64 ),
    .din100_WIDTH( 11 ),
    .CASE101( 7'h65 ),
    .din101_WIDTH( 11 ),
    .CASE102( 7'h66 ),
    .din102_WIDTH( 11 ),
    .CASE103( 7'h67 ),
    .din103_WIDTH( 11 ),
    .CASE104( 7'h68 ),
    .din104_WIDTH( 11 ),
    .CASE105( 7'h69 ),
    .din105_WIDTH( 11 ),
    .CASE106( 7'h6A ),
    .din106_WIDTH( 11 ),
    .CASE107( 7'h6B ),
    .din107_WIDTH( 11 ),
    .CASE108( 7'h6C ),
    .din108_WIDTH( 11 ),
    .CASE109( 7'h6D ),
    .din109_WIDTH( 11 ),
    .CASE110( 7'h6E ),
    .din110_WIDTH( 11 ),
    .CASE111( 7'h6F ),
    .din111_WIDTH( 11 ),
    .CASE112( 7'h70 ),
    .din112_WIDTH( 11 ),
    .CASE113( 7'h71 ),
    .din113_WIDTH( 11 ),
    .CASE114( 7'h72 ),
    .din114_WIDTH( 11 ),
    .CASE115( 7'h73 ),
    .din115_WIDTH( 11 ),
    .CASE116( 7'h74 ),
    .din116_WIDTH( 11 ),
    .CASE117( 7'h75 ),
    .din117_WIDTH( 11 ),
    .CASE118( 7'h76 ),
    .din118_WIDTH( 11 ),
    .CASE119( 7'h77 ),
    .din119_WIDTH( 11 ),
    .CASE120( 7'h78 ),
    .din120_WIDTH( 11 ),
    .CASE121( 7'h79 ),
    .din121_WIDTH( 11 ),
    .CASE122( 7'h7A ),
    .din122_WIDTH( 11 ),
    .CASE123( 7'h7B ),
    .din123_WIDTH( 11 ),
    .CASE124( 7'h7C ),
    .din124_WIDTH( 11 ),
    .CASE125( 7'h7D ),
    .din125_WIDTH( 11 ),
    .CASE126( 7'h7E ),
    .din126_WIDTH( 11 ),
    .CASE127( 7'h7F ),
    .din127_WIDTH( 11 ),
    .def_WIDTH( 11 ),
    .sel_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
sparsemux_257_7_11_1_1_U206(
    .din0(input_0_val),
    .din1(input_1_val),
    .din2(input_2_val),
    .din3(input_3_val),
    .din4(input_4_val),
    .din5(input_5_val),
    .din6(input_6_val),
    .din7(input_7_val),
    .din8(input_8_val),
    .din9(input_9_val),
    .din10(input_10_val),
    .din11(input_11_val),
    .din12(input_12_val),
    .din13(input_13_val),
    .din14(input_14_val),
    .din15(input_15_val),
    .din16(input_16_val),
    .din17(input_17_val),
    .din18(input_18_val),
    .din19(input_19_val),
    .din20(input_20_val),
    .din21(input_21_val),
    .din22(input_22_val),
    .din23(input_23_val),
    .din24(input_24_val),
    .din25(input_25_val),
    .din26(input_26_val),
    .din27(input_27_val),
    .din28(input_28_val),
    .din29(input_29_val),
    .din30(input_30_val),
    .din31(input_31_val),
    .din32(input_32_val),
    .din33(input_33_val),
    .din34(input_34_val),
    .din35(input_35_val),
    .din36(input_36_val),
    .din37(input_37_val),
    .din38(input_38_val),
    .din39(input_39_val),
    .din40(input_40_val),
    .din41(input_41_val),
    .din42(input_42_val),
    .din43(input_43_val),
    .din44(input_44_val),
    .din45(input_45_val),
    .din46(input_46_val),
    .din47(input_47_val),
    .din48(input_48_val),
    .din49(input_49_val),
    .din50(input_50_val),
    .din51(input_51_val),
    .din52(input_52_val),
    .din53(input_53_val),
    .din54(input_54_val),
    .din55(input_55_val),
    .din56(input_56_val),
    .din57(input_57_val),
    .din58(input_58_val),
    .din59(input_59_val),
    .din60(input_60_val),
    .din61(input_61_val),
    .din62(input_62_val),
    .din63(input_63_val),
    .din64(input_64_val),
    .din65(input_65_val),
    .din66(input_66_val),
    .din67(input_67_val),
    .din68(input_68_val),
    .din69(input_69_val),
    .din70(input_70_val),
    .din71(input_71_val),
    .din72(input_72_val),
    .din73(input_73_val),
    .din74(input_74_val),
    .din75(input_75_val),
    .din76(input_76_val),
    .din77(input_77_val),
    .din78(input_78_val),
    .din79(input_79_val),
    .din80(input_80_val),
    .din81(input_81_val),
    .din82(input_82_val),
    .din83(input_83_val),
    .din84(input_84_val),
    .din85(input_85_val),
    .din86(input_86_val),
    .din87(input_87_val),
    .din88(input_88_val),
    .din89(input_89_val),
    .din90(input_90_val),
    .din91(input_91_val),
    .din92(input_92_val),
    .din93(input_93_val),
    .din94(input_94_val),
    .din95(input_95_val),
    .din96(input_96_val),
    .din97(input_97_val),
    .din98(input_98_val),
    .din99(input_99_val),
    .din100(input_100_val),
    .din101(input_101_val),
    .din102(input_102_val),
    .din103(input_103_val),
    .din104(input_104_val),
    .din105(input_105_val),
    .din106(input_106_val),
    .din107(input_107_val),
    .din108(input_108_val),
    .din109(input_109_val),
    .din110(input_110_val),
    .din111(input_111_val),
    .din112(input_112_val),
    .din113(input_113_val),
    .din114(input_114_val),
    .din115(input_115_val),
    .din116(input_116_val),
    .din117(input_117_val),
    .din118(input_118_val),
    .din119(input_119_val),
    .din120(input_120_val),
    .din121(input_121_val),
    .din122(input_122_val),
    .din123(input_123_val),
    .din124(input_124_val),
    .din125(input_125_val),
    .din126(input_126_val),
    .din127(input_127_val),
    .def(tmp_fu_1398_p257),
    .sel(tmp_fu_1398_p258),
    .dout(tmp_fu_1398_p259)
);

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U207(
    .din0(or3_fu_570),
    .din1(or6_fu_574),
    .din2(or9_fu_578),
    .din3(or12_fu_582),
    .def(tmp_2_fu_1968_p9),
    .sel(tmp_2_fu_1968_p10),
    .dout(tmp_2_fu_1968_p11)
);

bnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln85_fu_1382_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_566 <= add_ln85_fu_1388_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_566 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            or12_fu_582 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            or12_fu_582 <= or10_fu_2040_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            or3_fu_570 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            or3_fu_570 <= or1_fu_2082_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            or6_fu_574 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            or6_fu_574 <= or4_fu_2068_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            or9_fu_578 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            or9_fu_578 <= or7_fu_2054_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_2_reg_2185 <= ap_sig_allocacmp_i_2;
        tmp_reg_2194 <= tmp_fu_1398_p259;
    end
end

always @ (*) begin
    if (((icmp_ln85_fu_1382_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_566;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_or12_load = 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_or12_load = or10_fu_2040_p3;
        end else begin
            ap_sig_allocacmp_or12_load = or12_fu_582;
        end
    end else begin
        ap_sig_allocacmp_or12_load = or12_fu_582;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_or3_load = 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_or3_load = or1_fu_2082_p3;
        end else begin
            ap_sig_allocacmp_or3_load = or3_fu_570;
        end
    end else begin
        ap_sig_allocacmp_or3_load = or3_fu_570;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_or6_load = 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_or6_load = or4_fu_2068_p3;
        end else begin
            ap_sig_allocacmp_or6_load = or6_fu_574;
        end
    end else begin
        ap_sig_allocacmp_or6_load = or6_fu_574;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_or9_load = 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_or9_load = or7_fu_2054_p3;
        end else begin
            ap_sig_allocacmp_or9_load = or9_fu_578;
        end
    end else begin
        ap_sig_allocacmp_or9_load = or9_fu_578;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln85_fu_1388_p2 = (ap_sig_allocacmp_i_2 + 8'd1);

assign and_ln92_1_fu_2062_p2 = (icmp_ln92_1_fu_2004_p2 & icmp_ln91_fu_1957_p2);

assign and_ln92_2_fu_2076_p2 = (icmp_ln92_fu_1998_p2 & icmp_ln91_fu_1957_p2);

assign and_ln92_fu_2048_p2 = (icmp_ln92_2_fu_2010_p2 & icmp_ln91_fu_1957_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign ap_return_0 = ap_sig_allocacmp_or3_load;

assign ap_return_1 = ap_sig_allocacmp_or6_load;

assign ap_return_2 = ap_sig_allocacmp_or9_load;

assign ap_return_3 = ap_sig_allocacmp_or12_load;

assign bit_pos_fu_1947_p2 = (trunc_ln88_fu_1935_p1 ^ 5'd31);

assign icmp_ln85_fu_1382_p2 = ((ap_sig_allocacmp_i_2 == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln91_fu_1957_p2 = (($signed(tmp_reg_2194) < $signed(11'd1)) ? 1'b1 : 1'b0);

assign icmp_ln92_1_fu_2004_p2 = ((trunc_ln88_4_fu_1938_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln92_2_fu_2010_p2 = ((trunc_ln88_4_fu_1938_p4 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln92_fu_1998_p2 = ((trunc_ln88_4_fu_1938_p4 == 2'd0) ? 1'b1 : 1'b0);

assign or10_fu_2040_p3 = ((or_ln92_3_fu_2034_p2[0:0] == 1'b1) ? or12_fu_582 : or_ln92_fu_1992_p2);

assign or1_fu_2082_p3 = ((and_ln92_2_fu_2076_p2[0:0] == 1'b1) ? or_ln92_fu_1992_p2 : or3_fu_570);

assign or4_fu_2068_p3 = ((and_ln92_1_fu_2062_p2[0:0] == 1'b1) ? or_ln92_fu_1992_p2 : or6_fu_574);

assign or7_fu_2054_p3 = ((and_ln92_fu_2048_p2[0:0] == 1'b1) ? or_ln92_fu_1992_p2 : or9_fu_578);

assign or_ln92_1_fu_2028_p2 = (or_ln92_2_fu_2022_p2 | icmp_ln92_fu_1998_p2);

assign or_ln92_2_fu_2022_p2 = (icmp_ln92_2_fu_2010_p2 | icmp_ln92_1_fu_2004_p2);

assign or_ln92_3_fu_2034_p2 = (xor_ln91_fu_2016_p2 | or_ln92_1_fu_2028_p2);

assign or_ln92_fu_1992_p2 = (tmp_2_fu_1968_p11 | shl_ln92_fu_1962_p2);

assign shl_ln92_fu_1962_p2 = 32'd1 << zext_ln89_fu_1953_p1;

assign tmp_2_fu_1968_p10 = {{i_2_reg_2185[6:5]}};

assign tmp_2_fu_1968_p9 = 'bx;

assign tmp_fu_1398_p257 = 'bx;

assign tmp_fu_1398_p258 = ap_sig_allocacmp_i_2[6:0];

assign trunc_ln88_4_fu_1938_p4 = {{i_2_reg_2185[6:5]}};

assign trunc_ln88_fu_1935_p1 = i_2_reg_2185[4:0];

assign xor_ln91_fu_2016_p2 = (icmp_ln91_fu_1957_p2 ^ 1'd1);

assign zext_ln89_fu_1953_p1 = bit_pos_fu_1947_p2;

endmodule //bnn_sign_and_quantize
